import { test, expect } from '@playwright/test';

const storageKey='workshopgirl.workshop.operations.v1';
function readyStore(){
  const at='2026-09-28T10:00:00.000Z';
  return {version:1,customers:[{id:'customer-bill',name:'Browser Billing Customer',phone:'0812345678',address:'1 Workshop Road'}],vehicles:[{id:'vehicle-bill',type:'Motorcycle',plate:'B 1234 TEST',make:'Honda',model:'CB',year:2022,color:'Red',odometer:1000}],jobs:[{id:'job-bill',number:'WI-BILL-E2E',status:'qc',customerId:'customer-bill',vehicleId:'vehicle-bill',intake:{number:'WI-BILL-E2E',complaint:'Brake noise',accessories:[],conditionNotes:'',date:'2026-09-28',arrivalTime:'09:00'},inspection:{findings:'Brake pads worn',checklist:[],recommendedJobs:[],parts:[],labor:[],consumables:0,additionalCost:0,discount:0,taxRate:0},workOrder:{number:'WO-BILL-E2E',date:'2026-09-28',status:'Complete',mechanic:'Tech',approvedWork:[],actualWork:[{id:'actual-bill-1',name:'Replace brake pads',detail:'Front',status:'Complete',mechanic:'Tech'}],parts:[],changes:[],startTime:'09:00',endTime:'10:00',mechanicNotes:'',result:'Complete',recommendations:'',signoff:'Tech'},qc:{number:'QC-BILL-E2E',date:'2026-09-28',inspector:'Inspector',mechanic:'Tech',finalStatus:'Ready for handover',checks:[{name:'Brake check',result:'Pass',note:''}],unresolvedIssues:[],returnedItems:[],roadTest:'Not required',roadTester:'',odometerBefore:1000,odometerAfter:1000,roadTestNotes:'',readinessNotes:'',recommendations:'',customerNotes:'',handoverRecipient:'',handoverStaff:'',handoverDate:'',handoverTime:''},createdAt:at,updatedAt:at}],parts:[{id:'part-bill',sku:'BP-1',name:'Brake pad set',category:'Brake',brand:'Maker',unit:'set',location:'A1',supplier:'',minimumStock:0,compatibility:'Honda CB',active:true,createdAt:at,updatedAt:at}],partMovements:[{id:'opening-bill',partId:'part-bill',type:'OPENING',quantity:8,at,partNameSnapshot:'Brake pad set',partSkuSnapshot:'BP-1',partUnitSnapshot:'set'},{id:'issue-bill',partId:'part-bill',type:'ISSUE_TO_JOB',quantity:3,at,jobId:'job-bill',partNameSnapshot:'Brake pad set',partSkuSnapshot:'BP-1',partUnitSnapshot:'set'},{id:'return-bill',partId:'part-bill',type:'RETURN_FROM_JOB',quantity:1,at,jobId:'job-bill',partNameSnapshot:'Brake pad set',partSkuSnapshot:'BP-1',partUnitSnapshot:'set'}],warranties:[],warrantyClaims:[],nextServices:[],invoices:[],payments:[]};
}
async function openBilling(page:import('@playwright/test').Page){await page.addInitScript(({key,store})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(store));window.print=()=>{};},{key:storageKey,store:readyStore()});await page.goto('/tools/workshop/billing/');await expect(page.getByRole('heading',{name:'Workshop billing.'})).toBeVisible();}

test('normal Billing flow saves Invoice, partial Payments, derived balance and printable receipts',async({page})=>{
  page.on('dialog',dialog=>dialog.accept());await openBilling(page);await expect(page.getByText(/Ready for Pickup/).first()).toBeVisible();await page.getByRole('button',{name:'Create Draft'}).click();
  const prices=page.getByLabel('Selling price per unit (Rp)');await expect(prices).toHaveCount(2);await prices.nth(0).fill('4500000');await prices.nth(1).fill('250000');const confirmations=page.getByLabel('I confirm this customer selling price');await confirmations.nth(0).check();await confirmations.nth(1).check();
  await page.getByRole('button',{name:'Issue Invoice'}).click();await expect(page.getByText(/INV-\d{8}-\d{4} · Issued/)).toBeVisible();await expect(page.getByText('Payment status: Unpaid')).toBeVisible();await expect(page.locator('.billing-total-row.grand strong')).toHaveText('Rp 5.000.000');
  const paymentAmount=page.getByLabel('Amount (whole Rp)');await paymentAmount.fill('2000000');await page.getByRole('button',{name:'Save Payment'}).click();await expect(page.locator('.billing-financial-status')).toContainText('Partially Paid');await expect(page.locator('.billing-financial-status')).toContainText('Outstanding Rp 3.000.000');
  await page.getByLabel('Amount (whole Rp)').fill('3000000');await page.getByRole('button',{name:'Save Payment'}).click();await expect(page.locator('.billing-financial-status')).toContainText('Paid');await expect(page.locator('.billing-financial-status')).toContainText('Outstanding Rp 0');
  await page.getByRole('button',{name:'Print Receipt'}).last().click();await expect(page.locator('#print-title')).toContainText('Payment Receipt RCP-');await expect(page.locator('#print-content')).toContainText('Browser Billing Customer');await expect(page.locator('#print-content')).toContainText('Outstanding after this Payment: Rp 0');
  await page.reload();await page.locator('.billing-invoice-card').first().click();await expect(page.getByText(/Payment status: Paid/)).toBeVisible();await expect(page).toHaveURL(/\/tools\/workshop\/billing\/$/);const search=page.getByRole('searchbox',{name:'Search invoices by number, customer, plate, vehicle or job'});await search.fill('not found');await expect(page.locator('.billing-invoice-card')).toHaveCount(0);await search.fill('INV-');await expect(page.locator('.billing-invoice-card')).toHaveCount(1);await expect(page.getByRole('searchbox',{name:'Search invoices by number, customer, plate, vehicle or job'})).toBeFocused();
  await page.goto('/tools/workshop/queue/');await expect(page.locator('.queue-status-badge').filter({hasText:'Ready for Pickup'})).toBeVisible();await expect(page.getByRole('link',{name:'Billing · Paid'})).toBeVisible();
});

test('Invoice reversal and Void preserve records and allow one replacement Draft',async({page})=>{
  page.on('dialog',async dialog=>{if(dialog.type()==='prompt')await dialog.accept(dialog.message().includes('reversing')?'Duplicate payment':'Correction after review');else await dialog.accept();});await openBilling(page);await page.getByRole('button',{name:'Create Draft'}).click();const prices=page.getByLabel('Selling price per unit (Rp)');await prices.nth(0).fill('500000');await prices.nth(1).fill('100000');const checks=page.getByLabel('I confirm this customer selling price');await checks.nth(0).check();await checks.nth(1).check();await page.getByRole('button',{name:'Issue Invoice'}).click();await page.getByLabel('Amount (whole Rp)').fill('100000');await page.getByRole('button',{name:'Save Payment'}).click();await page.getByRole('button',{name:'Reverse Payment'}).click();await expect(page.getByText(/Payment · Reversed/)).toBeVisible();await page.getByRole('button',{name:'Void Invoice'}).click();await expect(page.getByText(/Void .*Correction after review/)).toBeVisible();await page.getByRole('button',{name:'Create Replacement Draft'}).click();await expect(page.getByText('Invoice Draft · Draft')).toBeVisible();await expect(page.getByText(/Replacement for INV-/)).toBeVisible();
});

test('Billing page stays within requested phone, tablet and desktop widths',async({page})=>{
  await openBilling(page);for(const width of [320,375,390,768,1440]){await page.setViewportSize({width,height:900});await expect(page.locator('h1')).toHaveCount(1);const dimensions=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,content:document.documentElement.scrollWidth}));expect(dimensions.content,`horizontal overflow at ${width}px`).toBeLessThanOrEqual(dimensions.viewport);}
});
