import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyStore, loadStore, saveStore } from '../src/lib/workshop/store.ts';
import { clearWaitingForParts, createPart, partBalance, stockIn } from '../src/lib/workshop/parts.ts';
import { cancelPurchaseNeed, cancelPurchaseOrder, closePurchaseOrder, commitGoodsReceipt, createPurchaseNeed, createPurchaseOrderDraft, createSupplier, issuePurchaseOrder, needProgress, needWorkOrderMismatch, onOrderQuantity, poProgress, purchaseOrderTotal, shortageSuggestions, updateDraftPO, updateSupplier } from '../src/lib/workshop/procurement.ts';
import type { WorkshopJob } from '../src/lib/workshop/model.ts';

const now=new Date('2026-09-28T03:00:00.000Z');
function fixture(){
  const store=emptyStore();
  const part=createPart(store,{sku:'OF-1',name:'Oil Filter',category:'Engine',brand:'Test',unit:'each',location:'A1',supplier:'Legacy vendor text',minimumStock:2,compatibility:'Honda',active:true},0,now);assert.equal(part.ok,true);
  const p=store.parts[0]!;
  const job:WorkshopJob={id:'job-a',number:'WO-001',status:'work-order',customerId:'c1',vehicleId:'v1',intake:{number:'WI-001',complaint:'Service',accessories:[],conditionNotes:'',date:'2026-09-28',arrivalTime:'09:00'},workOrder:{number:'WO-001',date:'2026-09-28',status:'In progress',mechanic:'Tech',approvedWork:[],actualWork:[],parts:[{id:'wp1',partId:p.id,name:p.name,partNumber:p.sku,quantity:2,unit:p.unit,notes:''}],changes:[],startTime:'',endTime:'',mechanicNotes:'',result:'',recommendations:'',signoff:''},operations:{waitingParts:true,history:[]},createdAt:now.toISOString(),updatedAt:now.toISOString()};
  store.jobs.push(job);store.customers.push({id:'c1',name:'Test Customer',phone:'',address:''});store.vehicles.push({id:'v1',type:'Motorcycle',plate:'B 1234 TEST',make:'Honda',model:'CB',year:2020,color:'',odometer:1});
  return {store,part:p,job};
}
function supplier(store:ReturnType<typeof emptyStore>){const r=createSupplier(store,{name:'Supplier A',active:true},now);if(!r.ok)throw Error(r.message);return r.value;}
function jobNeed(f:ReturnType<typeof fixture>,qty=2){const r=createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:f.job.id,quantity:qty,reason:'Job shortage'},now);if(!r.ok)throw Error(r.message);return r.value;}
function issuePO(f:ReturnType<typeof fixture>,needIds:string[]){const s=supplier(f.store);const d=createPurchaseOrderDraft(f.store,needIds,s.supplierId,now);if(!d.ok)throw Error(d.message);const po=d.value;const lines=po.lines.map(l=>({...l,agreedUnitCost:100_000}));const edited=updateDraftPO(f.store,po.poId,{supplierId:s.supplierId,lines},now);if(!edited.ok)throw Error(edited.message);const issued=issuePurchaseOrder(f.store,po.poId,now);if(!issued.ok)throw Error(issued.message);return issued.value;}

test('pre-Phase-3B stores load with empty procurement collections and preserve existing records',()=>{
  const {store,job,part}=fixture();const legacy=structuredClone(store) as unknown as Record<string,unknown>;legacy.version=1;delete legacy.suppliers;delete legacy.purchaseNeeds;delete legacy.purchaseOrders;delete legacy.goodsReceipts;
  const storage={getItem:()=>JSON.stringify(legacy),setItem:()=>{throw Error('should not save on read');}};const loaded=loadStore(storage);assert.equal(loaded.recovered,false);assert.equal(loaded.store.jobs[0]?.id,job.id);assert.equal(loaded.store.parts[0]?.id,part.id);assert.deepEqual(loaded.store.purchaseOrders,[]);assert.deepEqual(loaded.store.goodsReceipts,[]);
});
test('Supplier IDs are stable; edits retain identity and Part supplier text stays independent',()=>{
  const {store,part}=fixture(),s=supplier(store),legacy=part.supplier;assert.equal(updateSupplier(store,s.supplierId,{name:'Supplier A Updated'},now).ok,true);assert.equal(store.suppliers[0]?.supplierId,s.supplierId);assert.equal(part.supplier,legacy);assert.equal(part.defaultSupplierId,undefined);
});
test('shortage is a suggestion only, counts existing open Needs, and never suggests cancelled/completed jobs',()=>{
  const f=fixture();assert.equal(shortageSuggestions(f.store)[0]?.suggested,2);assert.equal(f.store.purchaseNeeds.length,0);jobNeed(f);assert.equal(shortageSuggestions(f.store).length,0);f.job.status='completed';assert.equal(shortageSuggestions(f.store).length,0);
});
test('completed/cancelled Jobs cannot create shortage Needs, while cancelled origin remains readable',()=>{
  const f=fixture(),workOrder=f.job.workOrder!;workOrder.status='Complete';workOrder.actualWork=[{id:'actual',name:'Service',detail:'',mechanic:'Tech',status:'Complete'}];f.job.qc={number:'QC-1',date:'2026-09-28',inspector:'Inspector',mechanic:'Tech',finalStatus:'Ready for handover',checks:[{name:'Check',result:'Pass',note:''}],unresolvedIssues:[],returnedItems:[],roadTest:'Not required',roadTester:'',odometerBefore:1,odometerAfter:1,roadTestNotes:'',readinessNotes:'',recommendations:'',customerNotes:'',handoverRecipient:'Customer',handoverStaff:'Advisor',handoverDate:'2026-09-28',handoverTime:'11:00'};f.job.status='completed';assert.equal(createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:f.job.id,quantity:2},now).ok,false);f.job.status='work-order';workOrder.status='In progress';f.job.qc=undefined;const n=jobNeed(f);workOrder.status='Cancelled';assert.equal(createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:f.job.id,quantity:1},now).ok,false);assert.equal(needProgress(f.store,n).state,'Open');
});
test('manual Need requires a reason; replenishment is explicitly quantity-driven',()=>{
  const {store,part}=fixture();assert.equal(createPurchaseNeed(store,{source:'MANUAL',partId:part.id,quantity:1},now).ok,false);assert.equal(createPurchaseNeed(store,{source:'MANUAL',partId:part.id,quantity:1,reason:'Emergency supply'},now).ok,true);const r=createPurchaseNeed(store,{source:'REPLENISHMENT',partId:part.id,quantity:7,reason:'Restock shelf'},now);assert.equal(r.ok,true);if(r.ok)assert.equal(r.value.requestedQuantity,7);
});
test('Need cancellation requires a reason and preserves partial receipt history',()=>{
  const f=fixture(),need=jobNeed(f),po=issuePO(f,[need.needId]),line=po.lines[0]!;const r=commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:1,acceptedQuantity:1,rejectedQuantity:0,acceptedNeedAllocations:[{needId:need.needId,quantity:1}]}]},now);assert.equal(r.ok,true);assert.equal(cancelPurchaseNeed(f.store,need.needId,'',now).ok,false);assert.equal(cancelPurchaseNeed(f.store,need.needId,'Job no longer needs remainder',now).ok,true);assert.equal(needProgress(f.store,need).state,'Cancelled');assert.equal(f.store.goodsReceipts[0]?.lines[0]?.acceptedQuantity,1);
});
test('PO draft has no inventory effect; Issue validates Supplier/allocations, snapshots data, and numbers locally',()=>{
  const f=fixture(),need=jobNeed(f),s=supplier(f.store),d=createPurchaseOrderDraft(f.store,[need.needId],s.supplierId,now);assert.equal(d.ok,true);if(!d.ok)return;const po=d.value;assert.equal(po.status,'Draft');assert.equal(po.poNumber,undefined);assert.equal(partBalance(f.store,f.part.id),0);assert.equal(onOrderQuantity(f.store,f.part.id),0);po.lines[0]!.agreedUnitCost=125_000;const issued=issuePurchaseOrder(f.store,po.poId,now);assert.equal(issued.ok,true);if(!issued.ok)return;assert.match(issued.value.poNumber!,/^PO-20260928-\d{4}$/);assert.equal(issued.value.supplierSnapshot?.name,'Supplier A');assert.equal(partBalance(f.store,f.part.id),0);assert.equal(onOrderQuantity(f.store,f.part.id),2);assert.equal(purchaseOrderTotal(issued.value),250_000);assert.equal(updateDraftPO(f.store,po.poId,{notes:'mutate issued'},now).ok,false);assert.equal(updateSupplier(f.store,s.supplierId,{name:'Renamed Supplier'},now).ok,true);assert.equal(issued.value.supplierSnapshot?.name,'Supplier A');
});
test('one PO consolidates multiple Jobs and replenishment with quantity-per-Need allocations',()=>{
  const f=fixture(),a=jobNeed(f,2),jobB={...f.job,id:'job-b',number:'WO-002',workOrder:{...f.job.workOrder!,parts:[{...f.job.workOrder!.parts[0]!,id:'wp2',quantity:1}]}};f.store.jobs.push(jobB);const b=createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:jobB.id,quantity:1},now);assert.equal(b.ok,true);if(!b.ok)return;const rest=createPurchaseNeed(f.store,{source:'REPLENISHMENT',partId:f.part.id,quantity:7},now);assert.equal(rest.ok,true);if(!rest.ok)return;const po=issuePO(f,[a.needId,b.value.needId,rest.value.needId]);assert.equal(po.lines.length,1);assert.equal(po.lines[0]?.orderedQuantity,10);assert.deepEqual(po.lines[0]?.sourceAllocations.map(x=>x.quantity),[2,1,7]);assert.equal(po.lines[0]?.sourceAllocations.reduce((n,x)=>n+x.quantity,0),10);
});
test('draft and issued allocations cannot exceed Need procurement demand',()=>{
  const f=fixture(),n=jobNeed(f),s=supplier(f.store),a=createPurchaseOrderDraft(f.store,[n.needId],s.supplierId,now),b=createPurchaseOrderDraft(f.store,[n.needId],s.supplierId,now);assert.equal(a.ok,true);assert.equal(b.ok,false);
});
test('partial receiving records accepted and rejected quantities, actual cost, stock once, and closes on full receipt',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!;assert.equal(commitGoodsReceipt(f.store,po.poId,{receiptId:'receipt-1',receivedAt:'2026-09-28',confirmCostVariance:true,lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:1,rejectedQuantity:1,rejectionNote:'Damaged seal',actualUnitCost:105_000,acceptedNeedAllocations:[{needId:n.needId,quantity:1}]}]},now).ok,true);assert.equal(partBalance(f.store,f.part.id),1);assert.equal(onOrderQuantity(f.store,f.part.id),1);assert.equal(needProgress(f.store,n).state,'Partially Received');assert.equal(f.store.partMovements.filter(x=>x.sourceType==='PURCHASE_RECEIPT').length,1);const retry=commitGoodsReceipt(f.store,po.poId,{receiptId:'receipt-1',receivedAt:'2026-09-28',lines:[]},now);assert.equal(retry.ok,true);assert.equal(f.store.partMovements.filter(x=>x.sourceType==='PURCHASE_RECEIPT').length,1);assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:1,acceptedQuantity:1,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:1}]}]},now).ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(po.status,'Closed');assert.equal(poProgress(f.store,po),'Fully Received');assert.equal(needProgress(f.store,n).state,'Fulfilled');
});
test('cost variance requires explicit confirmation; actual cost does not modify PO agreed cost',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!,input={receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,actualUnitCost:105_000,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]};assert.equal(commitGoodsReceipt(f.store,po.poId,input,now).ok,false);assert.equal(commitGoodsReceipt(f.store,po.poId,{...input,confirmCostVariance:true},now).ok,true);assert.equal(line.agreedUnitCost,100_000);assert.equal(f.store.partMovements.at(-1)?.unitCost,105_000);
});
test('over-acceptance, allocation mismatch, rejection without reason, and invalid costs are blocked',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!;const base={poLineId:line.lineId,deliveredQuantity:3,acceptedQuantity:3,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:3}]};assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[base]},now).ok,false);assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{...base,deliveredQuantity:2,acceptedQuantity:2}]},now).ok,false);assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{...base,deliveredQuantity:2,acceptedQuantity:1,rejectedQuantity:1,acceptedNeedAllocations:[{needId:n.needId,quantity:1}]}]},now).ok,false);
});
test('cancelling/closing a partial PO retains received stock and reopens only its unreceived Need balance',()=>{
  const f=fixture(),need=createPurchaseNeed(f.store,{source:'REPLENISHMENT',partId:f.part.id,quantity:4},now);assert.equal(need.ok,true);if(!need.ok)return;const n=need.value,po=issuePO(f,[n.needId]),line=po.lines[0]!;assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]},now).ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(cancelPurchaseOrder(f.store,po.poId,'Supplier cancelled balance',now).ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(needProgress(f.store,n).open,2);assert.equal(needProgress(f.store,n).state,'Partially Received');
});
test('closing an Issued PO with outstanding quantity requires a reason and reopens its Need',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]);assert.equal(closePurchaseOrder(f.store,po.poId,'',now).ok,false);assert.equal(closePurchaseOrder(f.store,po.poId,'No longer available',now).ok,true);assert.equal(needProgress(f.store,n).open,2);assert.equal(onOrderQuantity(f.store,f.part.id),0);
});
test('manual Stock In changes ledger only and never fulfills a Purchase Need or PO',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]);assert.equal(stockIn(f.store,f.part.id,2,{unitCost:90_000,supplier:'Walk-in supplier'},now).ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(needProgress(f.store,n).received,0);assert.equal(needProgress(f.store,n).state,'Ordered');assert.equal(poProgress(f.store,po),'Not Received');
});
test('receipt and STOCK_IN persist together in the existing local store namespace',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!,saved=new Map<string,string>(),storage={getItem:(k:string)=>saved.get(k)??null,setItem:(k:string,v:string)=>{saved.set(k,v);}};assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]},now).ok,true);assert.equal(saveStore(f.store,storage).ok,true);const raw=JSON.parse(saved.get('workshopgirl.workshop.operations.v1')!);assert.equal(raw.goodsReceipts.length,1);assert.equal(raw.partMovements.filter((m:Record<string,unknown>)=>m.sourceType==='PURCHASE_RECEIPT').length,1);assert.equal(raw.invoices.length,0);assert.equal(raw.payments.length,0);
});

test('Work Order changes are flagged against the saved Need quantity snapshot',()=>{
  const f=fixture(),n=jobNeed(f,2);assert.equal(createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:f.job.id,quantity:1},now).ok,false);const before=n.requestedQuantity;f.job.workOrder!.parts[0]!.quantity=1;assert.equal(needWorkOrderMismatch(f.store,n),1);assert.equal(n.requestedQuantity,before);
});
test('receipt allocation validates aggregate duplicate Need rows and supports split multi-Need partial receipts',()=>{
  const f=fixture(),a=jobNeed(f,2),jobB={...f.job,id:'job-b',number:'WO-002',workOrder:{...f.job.workOrder!,parts:[{...f.job.workOrder!.parts[0]!,id:'wp2',quantity:3}]}};f.store.jobs.push(jobB);const created=createPurchaseNeed(f.store,{source:'JOB_SHORTAGE',partId:f.part.id,jobId:jobB.id,quantity:3},now);assert.equal(created.ok,true);if(!created.ok)return;const b=created.value,po=issuePO(f,[a.needId,b.needId]),line=po.lines[0]!;const bad=commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:3,acceptedQuantity:3,rejectedQuantity:0,acceptedNeedAllocations:[{needId:a.needId,quantity:1.5},{needId:a.needId,quantity:1.5}]}]},now);assert.equal(bad.ok,false);assert.equal(f.store.goodsReceipts.length,0);const first=commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:3,acceptedQuantity:3,rejectedQuantity:0,acceptedNeedAllocations:[{needId:a.needId,quantity:2},{needId:b.needId,quantity:1}]}]},now);assert.equal(first.ok,true);assert.equal(needProgress(f.store,a).received,2);assert.equal(needProgress(f.store,b).received,1);assert.equal(partBalance(f.store,f.part.id),3);const second=commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:b.needId,quantity:2}]}]},now);assert.equal(second.ok,true);assert.equal(needProgress(f.store,b).received,3);assert.equal(partBalance(f.store,f.part.id),5);
});
test('receipt retry repairs a missing purchase-receipt movement without duplicating other movements',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!;const first=commitGoodsReceipt(f.store,po.poId,{receiptId:'recover-me',receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]},now);assert.equal(first.ok,true);const purchase=f.store.partMovements.find(m=>m.sourceType==='PURCHASE_RECEIPT')!;f.store.partMovements.splice(f.store.partMovements.indexOf(purchase),1);assert.equal(partBalance(f.store,f.part.id),0);const retry=commitGoodsReceipt(f.store,po.poId,{receiptId:'recover-me',receivedAt:'2026-09-28',lines:[]},now);assert.equal(retry.ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(f.store.partMovements.filter(m=>m.sourceType==='PURCHASE_RECEIPT').length,1);
});
test('receipt for a cancelled origin Job becomes ordinary stock and never advances or clears Job workflow',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]);f.job.workOrder!.status='Cancelled';const line=po.lines[0]!;const receipt=commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]},now);assert.equal(receipt.ok,true);assert.equal(po.status,'Closed');assert.equal(partBalance(f.store,f.part.id),2);assert.equal(f.store.partMovements.some(m=>m.jobId===f.job.id),false);assert.equal(f.job.operations?.waitingParts,true);assert.equal(f.job.status,'work-order');assert.equal(f.store.invoices.length,0);assert.equal(f.store.payments.length,0);
});
test('receipt stock does not issue parts to a Job or clear Waiting Parts automatically',()=>{
  const f=fixture(),n=jobNeed(f),po=issuePO(f,[n.needId]),line=po.lines[0]!;assert.equal(f.job.operations?.waitingParts,true);assert.equal(commitGoodsReceipt(f.store,po.poId,{receivedAt:'2026-09-28',lines:[{poLineId:line.lineId,deliveredQuantity:2,acceptedQuantity:2,rejectedQuantity:0,acceptedNeedAllocations:[{needId:n.needId,quantity:2}]}]},now).ok,true);assert.equal(partBalance(f.store,f.part.id),2);assert.equal(f.store.partMovements.filter(m=>m.jobId===f.job.id).length,0);assert.equal(f.job.operations?.waitingParts,true);assert.equal(f.job.status,'work-order');assert.equal(clearWaitingForParts(f.store,f.job.id),true);assert.equal(f.job.operations?.waitingParts,false);assert.equal(f.job.status,'work-order');
});
