import test from 'node:test';
import assert from 'node:assert/strict';
import { STORAGE_KEY, emptyStore, createJob, getCustomer, getVehicle, getJob, loadStore, saveStore, updateJob } from '../src/lib/workshop/store.ts';
import { calculateEstimate, emptyInspection, validateIntake, validateInspection, workDuration, qcWarning, validateOdometers } from '../src/lib/workshop/rules.ts';
import { GET as getSitemap } from '../src/pages/sitemap-0.xml.ts';

function memory(raw: string | null = null) { let value=raw; return { getItem:()=>value, setItem:(_k:string,v:string)=>{value=v;}, get value(){return value;} }; }
const intake={number:'WI-1',complaint:'Noise',accessories:['key'],conditionNotes:'',date:'2026-09-27',arrivalTime:'10:00'};
const customer={name:'Test customer',phone:'123',address:'Somewhere'};
const vehicle={type:'Motorcycle' as const,plate:'TEST 1',make:'Test',model:'One',year:2020,color:'Blue',odometer:1200};
test('store creates linked stable customer, vehicle and job IDs and reloads them',()=>{const store=emptyStore();const job=createJob(store,{customer,vehicle,intake},p=>`${p}_stable`);assert.equal(job.id,'job_stable');assert.equal(job.customerId,'customer_stable');assert.equal(job.vehicleId,'vehicle_stable');assert.equal(getCustomer(store,job)?.name,customer.name);assert.equal(getVehicle(store,job)?.plate,vehicle.plate);const disk=memory();assert.equal(saveStore(store,disk).ok,true);const loaded=loadStore(disk);assert.equal(loaded.recovered,false);assert.equal(getJob(loaded.store,job.id)?.vehicleId,job.vehicleId);});
test('store updates the same job and preserves linked references',()=>{const s=emptyStore(),j=createJob(s,{customer,vehicle,intake},p=>p);assert.ok(updateJob(s,j.id,{status:'inspection',intake:{...intake,complaint:'Updated'}}));assert.equal(getJob(s,j.id)?.status,'inspection');assert.equal(getJob(s,j.id)?.customerId,'customer');assert.equal(getJob(s,j.id)?.intake.complaint,'Updated');});
test('malformed or unknown-version data recovers without overwriting source',()=>{for(const raw of ['{bad','{"version":99,"customers":[],"vehicles":[],"jobs":[]}']){const disk=memory(raw),loaded=loadStore(disk);assert.equal(loaded.recovered,true);assert.equal(disk.value,raw);assert.equal(loaded.store.jobs.length,0);}});
test('store retains the historical namespace while versioning the record schema',()=>{assert.equal(STORAGE_KEY,'workshopgirl.workshop.operations.v1');assert.equal(emptyStore().version,2);});
test('all nine Workshop Operations routes appear exactly once in the explicit sitemap',async()=>{const xml=await getSitemap().text();for(const route of ['vehicle-intake','inspection-estimate','work-order','qc-handover','queue','parts-inventory','service-history','billing','procurement'])assert.equal(xml.split(`https://workshopgirl.com/tools/workshop/${route}/`).length-1,1,route);assert.doesNotMatch(xml,/(vehicleId|jobId|invoiceId|paymentId|warrantyId|claimId|needId|poId|receiptId)/i);});
test('intake validates required fields, year range and nonnegative odometer',()=>{assert.deepEqual(validateIntake({name:'',plate:'',year:'1800',odometer:'-1'},2026).length,4);assert.deepEqual(validateIntake({name:'A',plate:'B',year:'2027',odometer:'0'},2026),[]);});
test('inspection estimate accounts for parts, hourly and fixed labor, discount, extra costs and tax',()=>{const d=emptyInspection('Motorcycle');d.parts=[{id:'p',name:'Oil',partNumber:'',quantity:2,unit:'each',unitPrice:10}];d.labor=[{id:'l1',name:'Hourly',mode:'hourly',hours:2,rate:15,fixed:0},{id:'l2',name:'Fixed',mode:'fixed',hours:0,rate:0,fixed:5}];d.consumables=3;d.additionalCost=2;d.discount=5;d.taxRate=10;assert.deepEqual(calculateEstimate(d),{parts:20,labor:35,additional:5,discount:5,tax:5.5,total:60.5});assert.deepEqual(validateInspection(d),[]);});
test('inspection rejects negative costs, invalid quantities and tax outside range',()=>{const d=emptyInspection('Car');d.parts[0]!.quantity=0;d.parts[0]!.unitPrice=-1;d.discount=-1;d.taxRate=101;assert.ok(validateInspection(d).length>=4);});
test('work duration handles overnight shifts',()=>{assert.equal(workDuration('23:15','01:00'),'1h 45m');assert.equal(workDuration('bad','02:00'),'');});
test('QC warns when a ready job has failed or unchecked checks',()=>{assert.match(qcWarning([{name:'Brakes',result:'Needs attention',note:''}],true),/one or more required/);assert.match(qcWarning([{name:'Brakes',result:'Not checked',note:''}],true),/one or more required/);assert.equal(qcWarning([{name:'Brakes',result:'Pass',note:''}],true),'');});
test('road test odometer validation rejects negative and decreasing readings',()=>{assert.deepEqual(validateOdometers(100,90),['Odometer after road test cannot be lower than the starting odometer.']);assert.ok(validateOdometers(-1,2)[0]?.includes('zero or greater'));assert.deepEqual(validateOdometers(null,null),[]);});
test('workshop client code contains no analytics integration or record payload dispatch',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../src/components/workshop/operations.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/gtag\s*\(|zaraz\s*\.|analytics\.track/i);assert.doesNotMatch(source,/fetch\s*\(|navigator\.sendBeacon/);});
