import { test, expect } from '@playwright/test';

test('Workshop Operations connects intake, inspection, work order and QC on one local job', async ({ page }) => {
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/vehicle-intake/');
  await expect(page).toHaveTitle(/Vehicle Intake/);
  await page.getByLabel('Name *').fill('Local Test Customer');await page.getByLabel('Phone').fill('555-0100');await page.getByLabel('License plate *').fill('WG-TEST-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByLabel('Complaint / reason for visit').fill('Front brake noise');
  await page.getByRole('button',{name:'Save intake'}).click();await expect(page.locator('#next-inspection')).toBeVisible();
  const jobUrl=await page.locator('#continue-inspection').getAttribute('href');expect(jobUrl).toContain('?job=');
  const jobId=new URL(jobUrl!,'http://local').searchParams.get('job')!;await page.goto(`/tools/workshop/vehicle-intake/?job=${encodeURIComponent(jobId)}`);await expect(page.locator('[name="customerName"]')).toHaveValue('Local Test Customer');await expect(page.locator('[name="plate"]')).toHaveValue('WG-TEST-01');await page.getByRole('button',{name:'Save intake'}).click();await page.locator('#continue-inspection').click();await expect(page.locator('#workshop-job-context')).toContainText('WG-TEST-01');await expect(page.locator('#inspection-context')).toContainText('Front brake noise');
  await page.locator('[name="findings"]').fill('Brake pads worn');await page.locator('#recommended-rows input[name="name"]').first().fill('Replace front pads');await page.locator('#recommended-rows input[type="checkbox"]').check();await page.locator('#estimate-parts input[name="name"]').first().fill('Brake pad set');await page.locator('#estimate-parts input[name="unitPrice"]').first().fill('45');await expect(page.locator('#estimate-summary')).toContainText(/Total Rp\s*45/);
  await page.getByRole('button',{name:/Save inspection/}).click();await expect(page.locator('#next-work-order')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0].inspection.recommendedJobs[0])).toMatchObject({name:'Replace front pads',approved:true});await page.locator('#continue-work-order').click();await expect(page.locator('#work-order-context')).toContainText('Front brake noise');await expect(page.locator('#approved-work input[name="name"]').first()).toHaveValue('Replace front pads');
  await page.getByRole('button',{name:'Add actual work'}).click();await page.locator('#actual-work input[name="name"]').first().fill('Replaced front brake pads');await page.locator('[name="result"]').fill('Brakes operate normally');await page.getByRole('button',{name:'Save Work Order'}).click();await expect(page.locator('#next-qc')).toBeVisible();await page.locator('#continue-qc').click();await expect(page.locator('#qc-context')).toContainText('Brakes operate normally');
  await page.locator('select[name^="qccheck:"]').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLSelectElement).value='Pass'));
  await page.locator('select[name="finalStatus"]').selectOption('Ready for handover');
  await page.locator('select[name="qccheck:0"]').selectOption('Needs attention');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#qc-error')).toContainText('Complete all QC checks');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0].status)).not.toBe('completed');await page.locator('select[name="qccheck:0"]').selectOption('Pass');
  await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!));expect(stored.jobs).toHaveLength(1);expect(stored.jobs[0].status).toBe('completed');expect(stored.jobs[0].vehicleId).toBeTruthy();
  await page.reload();await expect(page.locator('#workshop-job-context')).toContainText('WG-TEST-01');await expect(page.locator('#job-completed')).toBeVisible();expect(errors).toEqual([]);
});

test('Workshop pages handle validation, invalid job links, share, print and narrow viewports',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/workshop/vehicle-intake/');
  await page.getByRole('button',{name:'Save intake'}).click();await expect(page.locator('#intake-error')).toContainText('Customer name is required');
  await page.goto('/tools/workshop/inspection-estimate/?job=missing');await expect(page.locator('#workshop-status')).toContainText(/Choose a saved local job/);await expect(page.locator('#inspection-form')).toBeHidden();
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Print Test');await page.getByLabel('License plate *').fill('PRINT-1');await page.getByRole('button',{name:'Save intake'}).click();const url=await page.locator('#continue-inspection').getAttribute('href');await page.goto(url!);
  await page.evaluate(()=>{window.print=()=>{};});await page.locator('[data-print]').click();await expect(page.locator('#print-sheet')).toBeVisible();await expect(page.locator('#print-content')).toContainText('Print Test');
  const jobId=new URL(url!, 'http://local').searchParams.get('job')!;const widths=[320,375,390,768,1440];
  for(const route of ['/tools/workshop/vehicle-intake/','/tools/workshop/inspection-estimate/','/tools/workshop/work-order/','/tools/workshop/qc-handover/'])for(const width of widths){await page.setViewportSize({width,height:900});await page.goto(`${route}?job=${encodeURIComponent(jobId)}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${route} horizontal overflow at ${width}px`).toBeTruthy();}
  await page.goto('/tools/');await expect(page.getByRole('heading',{name:'Workshop Operations'})).toBeVisible();await expect(page.locator('a[href="/tools/dsp-validation/"]')).toBeVisible();
  for(const width of widths){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`tools index horizontal overflow at ${width}px`).toBeTruthy();}
  expect(errors).toEqual([]);
});

test('Queue shares Phase 1 jobs, derives status, handles Waiting Parts, and preserves status timeline',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/queue/');await expect(page).toHaveTitle(/Queue \/ Job Status/);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('meta[name="description"]')).toHaveAttribute('content',/existing WorkshopGirl jobs/i);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href','https://workshopgirl.com/tools/workshop/queue/');await expect(page.locator('.queue-empty-state')).toContainText('No Workshop Jobs yet');
  await page.goto('/tools/workshop/queue/?job=missing');await expect(page.locator('#queue-feedback')).toContainText('no longer available');
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Queue Flow Customer');await page.getByLabel('Phone').fill('555-0101');await page.getByLabel('License plate *').fill('WG-QUEUE-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByLabel('Complaint / reason for visit').fill('Brake noise');await page.getByRole('button',{name:'Save intake'}).click();
  const intakeUrl=await page.locator('#continue-inspection').getAttribute('href');expect(intakeUrl).toContain('?job=');const jobId=new URL(intakeUrl!,'http://local').searchParams.get('job')!;
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(jobId)}`);const card=page.locator(`[data-job-id="${jobId}"]`);await expect(card).toContainText('WG-QUEUE-01');await expect(card).toContainText('Queue Flow Customer');await expect(card).toContainText('Intake');
  await page.locator('#queue-search').fill('queue flow');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-filter').selectOption('Intake');await page.locator('#queue-sort').selectOption('longest');
  const continueInspection=card.getByRole('link',{name:/Continue to Inspection/});await expect(continueInspection).toHaveAttribute('href',new RegExp(`job=${encodeURIComponent(jobId)}`));await continueInspection.click();await expect(page.locator('#workshop-job-context')).toContainText('WG-QUEUE-01');
  await page.getByRole('button',{name:/Save inspection/}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Inspection');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to Inspection/}).click();await page.locator('#inspection-checklist select').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLSelectElement).value='Good'));
  await page.locator('#recommended-rows input[name="name"]').first().fill('Replace front pads');await page.locator('#recommended-rows input[type="checkbox"]').check();await page.locator('#estimate-parts input[name="name"]').first().fill('Brake pads');await page.locator('#estimate-parts input[name="unitPrice"]').first().fill('50');await page.getByRole('button',{name:/Save inspection/}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Waiting Approval');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to Work Order/}).click();await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('In progress');await page.locator('#work-order-form input[name="mechanic"]:not([data-field])').fill('Test Technician');await page.getByRole('button',{name:'Save Work Order'}).click();await page.goto('/tools/workshop/queue/');const active=page.locator(`[data-job-id="${jobId}"]`);await expect(active.locator('.queue-status-badge')).toHaveText('Work In Progress');await expect(active).toContainText('Test Technician');
  await active.getByRole('button',{name:'Mark as Waiting Parts'}).click();await expect(active.locator('.queue-status-badge')).toHaveText('Waiting Parts');await active.locator('details').locator('summary').click();await expect(active.locator('.queue-timeline')).toContainText('Waiting for parts');await active.getByRole('button',{name:'Clear Waiting Parts'}).click();await expect(active.locator('.queue-status-badge')).toHaveText('Work In Progress');
  await active.getByRole('link',{name:/Continue to Work Order/}).click();await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Complete');await page.getByRole('button',{name:'Save Work Order'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('QC');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to QC/}).click();await page.locator('[name="finalStatus"]').selectOption('Ready for handover');await page.locator('select[name^="qccheck:"]').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLSelectElement).value='Pass'));await page.locator('select[name="qccheck:0"]').selectOption('Needs attention');await page.getByRole('button',{name:'Save QC & Handover'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('QC');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to QC/}).click();await page.locator('select[name="qccheck:0"]').selectOption('Pass');await page.getByRole('button',{name:'Save QC & Handover'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Ready for Pickup');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Open QC & Handover/}).click();await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Completed');await page.reload();await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Completed');
  const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs);expect(persisted).toHaveLength(1);expect(persisted[0].id).toBe(jobId);expect(persisted[0].operations.history.map((x:{status:string})=>x.status)).toEqual(['Intake','Inspection','Waiting Approval','Work In Progress','Waiting Parts','Work In Progress','QC','Ready for Pickup','Completed']);expect(errors).toEqual([]);
});

test('Queue direct links, filters, empty/recovery states and responsive cards remain usable',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/workshop/queue/');await expect(page.locator('.queue-empty-state')).toBeVisible();
  await page.goto('/tools/workshop/vehicle-intake/');for(const [name,value] of [['Name *','Search Customer'],['License plate *','SORT-OLD'],['Make','Toyota'],['Model','Corolla']] as const)await page.getByLabel(name).fill(value);await page.getByLabel('Arrival time').fill('08:00');await page.getByRole('button',{name:'Save intake'}).click();const older=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;
  await page.goto('/tools/workshop/vehicle-intake/');for(const [name,value] of [['Name *','Second Customer'],['License plate *','SORT-NEW'],['Make','Honda'],['Model','Civic']] as const)await page.getByLabel(name).fill(value);await page.getByLabel('Arrival time').fill('11:00');await page.getByRole('button',{name:'Save intake'}).click();const newer=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(older)}`);await expect(page.locator(`[data-job-id="${older}"]`)).toHaveClass(/is-linked-job/);await page.locator('#queue-search').fill('civic');await expect(page.locator('.queue-job')).toHaveCount(1);await expect(page.locator('.queue-job')).toContainText('Second Customer');await page.locator('#queue-search').fill('SORT-');await expect(page.locator('.queue-job')).toHaveCount(2);await page.locator('#queue-sort').selectOption('oldest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',older);await page.locator('#queue-sort').selectOption('longest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',older);await page.locator('#queue-sort').selectOption('newest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',newer);await page.locator('#queue-filter').selectOption('Intake');await expect(page.locator('.queue-job')).toHaveCount(2);await page.getByRole('button',{name:/Inspection · 0/}).click();await expect(page.locator('.queue-empty-state')).toContainText('No jobs match');await page.goto('/tools/');await expect(page.getByRole('link',{name:/Queue \/ Job Status/})).toBeVisible();
  for(const width of [320,375,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('/tools/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`tools index overflow at ${width}px`).toBeTruthy();await expect(page.getByRole('link',{name:/Sound Analyzer/}).first()).toBeVisible();await expect(page.getByRole('link',{name:/Queue \/ Job Status/})).toBeVisible();await page.goto('/tools/workshop/queue/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`queue overflow at ${width}px`).toBeTruthy();await expect(page.locator('#queue-search')).toBeVisible();await expect(page.locator('.queue-job').first()).toBeVisible();}
  await page.locator('#queue-search').focus();await expect(page.locator('#queue-search')).toBeFocused();await page.keyboard.press('Tab');await expect(page.locator('#queue-filter')).toBeFocused();await expect(page.locator('[data-status-filter="Intake"]')).toHaveAttribute('aria-pressed','false');
  expect(errors).toEqual([]);
});

test('Cancelled Work Order stays terminal through Waiting Parts, review links, and reload',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Cancelled Test Customer');await page.getByLabel('License plate *').fill('WG-CANCEL-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByRole('button',{name:'Save intake'}).click();
  const inspectionUrl=(await page.locator('#continue-inspection').getAttribute('href'))!,jobId=new URL(inspectionUrl,'http://local').searchParams.get('job')!;
  await page.goto(inspectionUrl);await page.locator('#inspection-checklist select').evaluateAll(nodes=>nodes.forEach(n=>(n as HTMLSelectElement).value='Good'));await page.getByRole('button',{name:/Save inspection/}).click();
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(jobId)}`);let card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Waiting Approval');await card.getByRole('link',{name:/Continue to Work Order/}).click();
  await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('In progress');await page.getByRole('button',{name:'Save Work Order'}).click();
  await page.goto('/tools/workshop/queue/');card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Work In Progress');await card.getByRole('button',{name:'Mark as Waiting Parts'}).click();await expect(card.locator('.queue-status-badge')).toHaveText('Waiting Parts');
  await card.getByRole('link',{name:/Continue to Work Order/}).click();await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Cancelled');await page.getByRole('button',{name:'Save Work Order'}).click();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);await expect(page.locator('#work-order-form select[name="status"]:not([data-field])')).toBeDisabled();
  await page.goto('/tools/workshop/queue/');card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Cancelled');await expect(card.getByRole('button',{name:'Mark as Waiting Parts'})).toHaveCount(0);await expect(card.getByRole('link',{name:/Review Cancelled Work Order/})).toHaveAttribute('href',new RegExp(`job=${encodeURIComponent(jobId)}`));
  await page.locator('#queue-filter').selectOption('Cancelled');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-search').fill('WG-CANCEL');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-search').fill('Cancelled Test');await expect(page.locator('.queue-job')).toHaveCount(1);
  await card.locator('details summary').click();await expect(card.locator('.queue-timeline')).toContainText('Cancelled');await expect(card.locator('.queue-timeline')).toContainText('Work Order cancelled');
  await card.getByRole('link',{name:/Review Cancelled Work Order/}).click();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);await expect(page.locator('#work-order-form select[name="status"]:not([data-field])')).toBeDisabled();await expect(page.getByRole('button',{name:'Save Work Order'})).toBeDisabled();
  await page.goto(`/tools/workshop/qc-handover/?job=${encodeURIComponent(jobId)}`);await expect(page.locator('#qc-form')).toBeHidden();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);
  await page.goto('/tools/workshop/queue/');await page.reload();card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Cancelled');await expect(card.locator('details')).toContainText('Work Order cancelled');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0]);expect(saved.workOrder.status).toBe('Cancelled');expect(saved.operations.history.at(-1).status).toBe('Cancelled');expect(errors).toEqual([]);
});

for(const route of ['/tools/workshop/vehicle-intake/','/tools/workshop/inspection-estimate/','/tools/workshop/work-order/','/tools/workshop/qc-handover/'])test(`direct load ${route}`,async({page})=>{await page.goto(route);await expect(page).toHaveTitle(/Workshop Operations/);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',`https://workshopgirl.com${route}`);await expect(page.locator('body')).not.toContainText('bisnis.cc');});
