import { test, expect, type Page } from '@playwright/test';

async function chooseAll(page:Page,selector:string,value:string){const controls=page.locator(selector);await expect(controls.first()).toBeVisible();const count=await controls.count();for(let index=0;index<count;index++)await controls.nth(index).selectOption(value);}

test('Workshop shared skip link stays hidden until keyboard focus and targets #main on every operations page', async ({ page }) => {
  // This cross-route keyboard and viewport sweep is intentionally heavier in WebKit mobile.
  test.setTimeout(60_000);
  const routes = [
    '/tools/workshop/vehicle-intake/',
    '/tools/workshop/inspection-estimate/',
    '/tools/workshop/work-order/',
    '/tools/workshop/qc-handover/',
    '/tools/workshop/queue/',
    '/tools/workshop/parts-inventory/',
    '/tools/workshop/service-history/',
    '/tools/workshop/procurement/',
  ];
  for (const route of routes) {
    await page.goto(route);
    const skip = page.getByRole('link', { name: 'Skip to workshop tool' });
    const main = page.locator('#main');
    await expect(skip).toHaveAttribute('href', '#main');
    await expect(main).toHaveCount(1);
    expect(await page.locator('[id="main"]').count()).toBe(1);
    const headerTop = await page.locator('.site-header').evaluate(node => node.getBoundingClientRect().top);
    const mainTop = await main.evaluate(node => node.getBoundingClientRect().top);
    const skipBox = await skip.boundingBox();
    expect(skipBox).not.toBeNull();
    expect(skipBox!.y + skipBox!.height).toBeLessThanOrEqual(0);
    await page.keyboard.press('Tab');
    await expect(skip).toBeFocused();
    await expect(skip).toBeInViewport();
    expect(await skip.evaluate(node => getComputedStyle(node).outlineStyle)).toBe('solid');
    expect(await page.locator('.site-header').evaluate(node => node.getBoundingClientRect().top)).toBe(headerTop);
    expect(await main.evaluate(node => node.getBoundingClientRect().top)).toBe(mainTop);
    await page.keyboard.press('Tab');
    await expect(skip).not.toBeFocused();
    const unfocusedSkipBottom=await page.evaluate(()=>{const node=document.querySelector('.skip-link');return node?.getBoundingClientRect().bottom??null;});expect(unfocusedSkipBottom===null||unfocusedSkipBottom<=0).toBeTruthy();
    await page.keyboard.press('Shift+Tab');
    await expect(skip).toBeFocused();
    await page.keyboard.press('Enter');
    expect(new URL(page.url()).pathname + new URL(page.url()).hash).toBe(`${route}#main`);
    await expect(main).toBeFocused();
    for (const width of [320, 375, 390, 768, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${route} skip link overflow at ${width}px`).toBeTruthy();
    }
  }
});

test('Workshop Operations connects intake, inspection, work order and QC on one local job', async ({ page }) => {
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/vehicle-intake/');
  await expect(page).toHaveTitle(/Vehicle Intake/);
  await page.getByLabel('Name *').fill('Local Test Customer');await page.getByLabel('Phone').fill('555-0100');await page.getByLabel('License plate *').fill('WG-TEST-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByLabel('Complaint / reason for visit').fill('Front brake noise');
  await page.getByRole('button',{name:'Save intake'}).click();await expect(page.locator('#next-inspection')).toBeVisible();
  const jobUrl=await page.locator('#continue-inspection').getAttribute('href');expect(jobUrl).toContain('?job=');
  const jobId=new URL(jobUrl!,'http://local').searchParams.get('job')!;await page.goto(`/tools/workshop/vehicle-intake/?job=${encodeURIComponent(jobId)}`);await expect(page.locator('[name="customerName"]')).toHaveValue('Local Test Customer');await expect(page.locator('[name="plate"]')).toHaveValue('WG-TEST-01');await page.getByRole('button',{name:'Save intake'}).click();await page.locator('#continue-inspection').click();await expect(page.locator('#workshop-job-context')).toContainText('WG-TEST-01');await expect(page.locator('#inspection-context')).toContainText('Front brake noise');
  await page.locator('[name="findings"]').fill('Brake pads worn');await page.locator('#recommended-rows input[name="name"]').first().fill('Replace front pads');await page.locator('#recommended-rows input[type="checkbox"]').check();await page.getByLabel('Approved by (customer / authorized contact)').fill('Local Test Customer');await page.locator('#estimate-parts input[name="name"]').first().fill('Brake pad set');await page.locator('#estimate-parts input[name="unitPrice"]').first().fill('45');await expect(page.locator('#estimate-summary')).toContainText(/Total Rp\s*45/);
  await page.getByRole('button',{name:/Save inspection/}).click();await expect(page.locator('#next-work-order')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0].inspection.recommendedJobs[0])).toMatchObject({name:'Replace front pads',approved:true});await page.locator('#continue-work-order').click();await expect(page.locator('#work-order-context')).toContainText('Front brake noise');await expect(page.locator('#approved-work input[name="name"]').first()).toHaveValue('Replace front pads');
  await page.getByRole('button',{name:'Add actual work'}).click();await page.locator('#actual-work input[name="name"]').first().fill('Replaced front brake pads');await page.locator('#actual-work select[name="status"]').first().selectOption('Complete');await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Complete');await page.locator('[name="result"]').fill('Brakes operate normally');await page.getByRole('button',{name:'Save Work Order'}).click();await expect(page.locator('#next-qc')).toBeVisible();expect(await page.evaluate(id=>{const job=JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs.find((item:{id:string})=>item.id===id);return job.workOrder.approvedWork[0].sourceRecommendationId;},jobId)).toBe((await page.evaluate(id=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs.find((item:{id:string})=>item.id===id).inspection.recommendedJobs[0].id,jobId)));await page.locator('#continue-qc').click();await expect(page.locator('#qc-context')).toContainText('Brakes operate normally');
  await chooseAll(page,'select[name^="qccheck:"]','Pass');
  await page.locator('select[name="finalStatus"]').selectOption('Ready for handover');
  await page.locator('select[name="qccheck:0"]').selectOption('Needs attention');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#qc-error')).toContainText('Pass all QC checks');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0].status)).not.toBe('completed');await page.locator('select[name="qccheck:0"]').selectOption('Pass');
  await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#qc-error')).toContainText('Record the recipient');await page.locator('[name="handoverRecipient"]').fill('Local Test Customer');await page.locator('[name="handoverStaff"]').fill('Service Advisor');await page.locator('[name="handoverDate"]').fill('2026-09-27');await page.locator('[name="handoverTime"]').fill('12:00');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!));expect(stored.jobs).toHaveLength(1);expect(stored.jobs[0].status).toBe('completed');expect(stored.jobs[0].vehicleId).toBeTruthy();
  await page.reload();await expect(page.locator('#workshop-job-context')).toContainText('WG-TEST-01');await expect(page.locator('#job-completed')).toBeVisible();await page.locator('[data-step-link="service-history"]').click();await expect(page.locator('#history-vehicle')).toHaveValue(stored.jobs[0].vehicleId);await expect(page.locator('#history-content')).toContainText('Replaced front brake pads');await expect(page.locator('[data-step-link="inspection"]')).toHaveAttribute('href', '/tools/workshop/inspection-estimate/?job='+jobId);await page.getByRole('button',{name:'Choose another vehicle',exact:true}).click();await expect(page.locator('#workshop-job-context')).toBeHidden();await expect(page.locator('[data-step-link="inspection"]')).toHaveAttribute('href', '/tools/workshop/inspection-estimate/');expect(errors).toEqual([]);
});


test('Direct QC navigation cannot complete a job without Work Order evidence',async({page})=>{
 await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('QC Gate Customer');await page.getByLabel('License plate *').fill('WG-QC-GATE');await page.getByRole('button',{name:'Save intake'}).click();const inspection=await page.locator('#continue-inspection').getAttribute('href');const jobId=new URL(inspection!,'http://local').searchParams.get('job')!;
 await page.goto(`/tools/workshop/qc-handover/?job=${encodeURIComponent(jobId)}`);await chooseAll(page,'select[name^="qccheck:"]','Pass');await page.locator('[name="finalStatus"]').selectOption('Ready for handover');await page.locator('[name="handoverRecipient"]').fill('Customer');await page.locator('[name="handoverStaff"]').fill('Advisor');await page.locator('[name="handoverDate"]').fill('2026-09-27');await page.locator('[name="handoverTime"]').fill('12:00');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#qc-error')).toContainText('Work Order');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0].status)).not.toBe('completed');
});

test('Parts Inventory issues, blocks shortage, clears Waiting Parts manually, returns stock, and persists',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Parts Test');await page.getByLabel('License plate *').fill('WG-PART-1');await page.getByRole('button',{name:'Save intake'}).click();const next=await page.locator('#continue-inspection').getAttribute('href');const jobId=new URL(next!,'http://local').searchParams.get('job')!;
 await page.goto(next!);await chooseAll(page,'#inspection-checklist select','Good');await page.getByRole('button',{name:/Save inspection/}).click();const workOrderUrl=await page.locator('#continue-work-order').getAttribute('href');expect(new URL(workOrderUrl!,'http://local').searchParams.get('job')).toBe(jobId);
 await page.goto('/tools/workshop/parts-inventory/');await page.getByLabel('Part name').fill('Oil Filter');await page.getByLabel('SKU / part number').fill('OF-100');await page.locator('#part-form [name="unit"]').fill('each');await page.getByLabel('Minimum stock').fill('1');await page.getByLabel('Opening balance').fill('1');await page.getByRole('button',{name:'Save part'}).click();await expect(page.locator('#parts-list')).toContainText('1 each');
 await page.goto(workOrderUrl!);await page.getByRole('button',{name:'Add part or material'}).click();const partId=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).parts[0].id);await page.locator('#work-parts [data-field="partId"]').last().selectOption(partId);await page.locator('#work-parts input[name="quantity"]').last().fill('2');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).partMovements.map((m:{type:string})=>m.type))).toEqual(['OPENING']);await page.getByRole('button',{name:'Save Work Order'}).click();
 await page.goto('/tools/workshop/parts-inventory/');await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-list')).toContainText('0 each');await expect(page.locator('#parts-list')).toContainText('Out of Stock');
 await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-feedback')).toContainText('Insufficient stock');
 await page.goto(`/tools/workshop/parts-inventory/?job=${encodeURIComponent(jobId)}`);await page.getByRole('button',{name:'Mark as Waiting Parts'}).click();await expect(page.locator('#job-parts')).toContainText('Waiting Parts');
 await page.locator('#movement-form [name="type"]').selectOption('STOCK_IN');await page.locator('#movement-form [name="quantity"]').fill('2');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#job-parts')).toContainText('No stock shortage remains');await expect(page.locator('#job-parts')).toContainText('Waiting Parts');await page.getByRole('button',{name:'Clear Waiting Parts'}).click();await expect(page.locator('#job-parts')).not.toContainText('Queue status: Waiting Parts');
 await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-list')).toContainText('1 each');
 await page.locator('#movement-form [name="type"]').selectOption('RETURN_FROM_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-list')).toContainText('2 each');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!));expect(saved.partMovements.map((m:{type:string})=>m.type)).toEqual(['OPENING','ISSUE_TO_JOB','STOCK_IN','ISSUE_TO_JOB','RETURN_FROM_JOB']);expect(saved.partMovements[1].jobId).toBe(jobId);await page.reload();await expect(page.locator('#parts-list')).toContainText('2 each');await expect(page.locator('#job-parts')).toContainText('requested');for(const width of [320,375,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`inventory overflow at ${width}px`).toBeTruthy();}expect(errors).toEqual([]);
});

test('Cancelled job retains its issue history, blocks new issues and allows explicit return',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Cancelled Parts');await page.getByLabel('License plate *').fill('WG-PART-CANCEL');await page.getByRole('button',{name:'Save intake'}).click();const jobId=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;
 await page.goto('/tools/workshop/parts-inventory/');await page.getByLabel('Part name').fill('Brake fluid');await page.getByLabel('SKU / part number').fill('BF-1');await page.getByLabel('Opening balance').fill('2');await page.getByRole('button',{name:'Save part'}).click();const partId=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).parts[0].id);
 await page.goto(`/tools/workshop/inspection-estimate/?job=${encodeURIComponent(jobId)}`);await chooseAll(page,'#inspection-checklist select','Good');await page.getByRole('button',{name:/Save inspection/}).click();await page.goto(`/tools/workshop/work-order/?job=${encodeURIComponent(jobId)}`);await page.getByRole('button',{name:'Add part or material'}).click();await page.locator('#work-parts [data-field="partId"]').last().selectOption(partId);await page.locator('#work-parts input[name="quantity"]').last().fill('3');await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('In progress');await page.getByRole('button',{name:'Save Work Order'}).click();
 await page.goto('/tools/workshop/parts-inventory/');await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();
 await page.goto(`/tools/workshop/work-order/?job=${encodeURIComponent(jobId)}`);await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Cancelled');await page.getByRole('button',{name:'Save Work Order'}).click();await page.goto(`/tools/workshop/parts-inventory/?job=${encodeURIComponent(jobId)}`);await expect(page.locator('#job-parts')).toContainText('Issue to job');await expect(page.getByRole('button',{name:'Mark as Waiting Parts'})).toHaveCount(0);await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(jobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-feedback')).toContainText('cancelled or completed');
 await page.locator('#movement-form [name="type"]').selectOption('RETURN_FROM_JOB');await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();await expect(page.locator('#parts-list')).toContainText('2 each');await page.reload();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!));expect(saved.partMovements.map((m:{type:string})=>m.type)).toEqual(['OPENING','ISSUE_TO_JOB','RETURN_FROM_JOB']);expect(saved.jobs[0].workOrder.status).toBe('Cancelled');expect(errors).toEqual([]);
});

test('Workshop pages handle validation, invalid job links, share, print and narrow viewports',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/workshop/vehicle-intake/');
  await page.getByRole('button',{name:'Save intake'}).click();await expect(page.locator('#intake-error')).toContainText('Customer name is required');
  await page.goto('/tools/workshop/inspection-estimate/?job=missing');await expect(page.locator('#workshop-status')).toContainText(/Choose a saved local job/);await expect(page.locator('#inspection-form')).toBeHidden();
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Print Test');await page.getByLabel('License plate *').fill('PRINT-1');await page.getByRole('button',{name:'Save intake'}).click();const url=await page.locator('#continue-inspection').getAttribute('href');await page.goto(url!);
  await page.evaluate(()=>{window.print=()=>{};});await page.locator('[data-print]').click();await expect(page.locator('#print-sheet')).toBeVisible();await expect(page.locator('#print-content')).toContainText('Print Test');
  const jobId=new URL(url!, 'http://local').searchParams.get('job')!;const widths=[320,375,390,768,1440];
  for(const route of ['/tools/workshop/vehicle-intake/','/tools/workshop/inspection-estimate/','/tools/workshop/work-order/','/tools/workshop/qc-handover/'])for(const width of widths){await page.setViewportSize({width,height:900});await page.goto(`${route}?job=${encodeURIComponent(jobId)}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`${route} horizontal overflow at ${width}px`).toBeTruthy();}
  await page.goto('/tools/');await expect(page.getByRole('heading',{name:'Workshop Operations'})).toBeVisible();await expect(page.locator('a[href="/tools/dsp-validation/"]')).toBeVisible();await expect(page.locator('a[href="/tools/workshop/service-history/"]')).toContainText('Service History & Warranty');await expect(page.locator('a[href="/tools/workshop/procurement/"]')).toContainText('Procurement');
  for(const width of widths){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`tools index horizontal overflow at ${width}px`).toBeTruthy();}
  expect(errors).toEqual([]);
});

test('Queue shares Phase 1 jobs, derives status, handles Waiting Parts, and preserves status timeline',async({page})=>{
  test.setTimeout(60_000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/queue/');await expect(page).toHaveTitle(/Queue \/ Job Status/);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('meta[name="description"]')).toHaveAttribute('content',/existing WorkshopGirl jobs/i);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href','https://workshopgirl.com/tools/workshop/queue/');await expect(page.locator('.queue-empty-state')).toContainText('No Workshop Jobs yet');
  await page.goto('/tools/workshop/queue/?job=missing');await expect(page.locator('#queue-feedback')).toContainText('no longer available');
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Queue Flow Customer');await page.getByLabel('Phone').fill('555-0101');await page.getByLabel('License plate *').fill('WG-QUEUE-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByLabel('Complaint / reason for visit').fill('Brake noise');await page.getByRole('button',{name:'Save intake'}).click();
  const intakeUrl=await page.locator('#continue-inspection').getAttribute('href');expect(intakeUrl).toContain('?job=');const jobId=new URL(intakeUrl!,'http://local').searchParams.get('job')!;
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(jobId)}`);const card=page.locator(`[data-job-id="${jobId}"]`);await expect(card).toContainText('WG-QUEUE-01');await expect(card).toContainText('Queue Flow Customer');await expect(card).toContainText('Intake');
  await page.locator('#queue-search').fill('queue flow');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-filter').selectOption('Intake');await page.locator('#queue-sort').selectOption('longest');
  const continueInspection=card.getByRole('link',{name:/Continue to Inspection/});await expect(continueInspection).toHaveAttribute('href',new RegExp(`job=${encodeURIComponent(jobId)}`));await continueInspection.click();await expect(page.locator('#workshop-job-context')).toContainText('WG-QUEUE-01');
  await page.getByRole('button',{name:/Save inspection/}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Inspection');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to Inspection/}).click();await chooseAll(page,'#inspection-checklist select','Good');
  await page.locator('#recommended-rows input[name="name"]').first().fill('Replace front pads');await page.locator('#recommended-rows input[type="checkbox"]').check();await page.getByLabel('Approved by (customer / authorized contact)').fill('Queue Flow Customer');await page.locator('#estimate-parts input[name="name"]').first().fill('Brake pads');await page.locator('#estimate-parts input[name="unitPrice"]').first().fill('50');await page.getByRole('button',{name:/Save inspection/}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Waiting Approval');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to Inspection/}).click();await page.locator('#recommended-rows input[type="checkbox"]').check();await page.getByLabel('Approved by (customer / authorized contact)').fill('Queue Flow Customer');await page.getByRole('button',{name:/Save inspection/}).click();expect(await page.evaluate(()=>{const j=JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0];return Boolean(j.inspection.approvedAt&&j.inspection.approvedBy&&j.inspection.approvedRevision===j.inspection.revision);})).toBeTruthy();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Inspection');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to Work Order/}).click();await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('In progress');await page.locator('#work-order-form input[name="mechanic"]:not([data-field])').fill('Test Technician');await page.getByRole('button',{name:'Save Work Order'}).click();await page.goto('/tools/workshop/queue/');const active=page.locator(`[data-job-id="${jobId}"]`);await expect(active.locator('.queue-status-badge')).toHaveText('Work In Progress');await expect(active).toContainText('Test Technician');
  page.once('dialog',dialog=>dialog.accept('External supplier delay'));await active.getByRole('button',{name:'Mark as Waiting Parts'}).click();await expect(active.locator('.queue-status-badge')).toHaveText('Waiting Parts');await active.locator('details').locator('summary').click();await expect(active.locator('.queue-timeline')).toContainText('Waiting for parts');await active.getByRole('button',{name:'Clear Waiting Parts'}).click();await expect(active.locator('.queue-status-badge')).toHaveText('Work In Progress');
  await active.getByRole('link',{name:/Continue to Work Order/}).click();await page.getByRole('button',{name:'Add actual work'}).click();await page.locator('#actual-work input[name="name"]').last().fill('Replace brake pads');await page.locator('#actual-work select[name="status"]').last().selectOption('Complete');await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Complete');await page.getByRole('button',{name:'Save Work Order'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('QC');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to QC/}).click();await page.locator('[name="finalStatus"]').selectOption('Ready for handover');await chooseAll(page,'select[name^="qccheck:"]','Pass');await page.locator('select[name="qccheck:0"]').selectOption('Needs attention');await page.getByRole('button',{name:'Save QC & Handover'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('QC');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Continue to QC/}).click();await page.locator('select[name="qccheck:0"]').selectOption('Pass');await page.getByRole('button',{name:'Save QC & Handover'}).click();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Ready for Pickup');
  await page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:/Open QC & Handover/}).click();await page.locator('[name="handoverRecipient"]').fill('Queue Flow Customer');await page.locator('[name="handoverStaff"]').fill('Advisor');await page.locator('[name="handoverDate"]').fill('2026-09-27');await page.locator('[name="handoverTime"]').fill('12:00');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();await page.goto('/tools/workshop/queue/');await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Completed');await expect(page.locator(`[data-job-id="${jobId}"]`).getByRole('link',{name:'View Service History'})).toHaveAttribute('href','/tools/workshop/service-history/');await page.reload();await expect(page.locator(`[data-job-id="${jobId}"] .queue-status-badge`)).toHaveText('Completed');
  const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs);expect(persisted).toHaveLength(1);expect(persisted[0].id).toBe(jobId);expect(persisted[0].operations.history.map((x:{status:string})=>x.status)).toEqual(['Intake','Inspection','Waiting Approval','Inspection','Work In Progress','Waiting Parts','Work In Progress','QC','Ready for Pickup','Completed']);expect(errors).toEqual([]);
});

test('Queue direct links, filters, empty/recovery states and responsive cards remain usable',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/workshop/queue/');await expect(page.locator('.queue-empty-state')).toBeVisible();
  await page.goto('/tools/workshop/vehicle-intake/');for(const [name,value] of [['Name *','Search Customer'],['License plate *','SORT-OLD'],['Make','Toyota'],['Model','Corolla']] as const)await page.getByLabel(name).fill(value);await page.getByLabel('Arrival time').fill('08:00');await page.getByRole('button',{name:'Save intake'}).click();const older=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;
  await page.goto('/tools/workshop/vehicle-intake/');for(const [name,value] of [['Name *','Second Customer'],['License plate *','SORT-NEW'],['Make','Honda'],['Model','Civic']] as const)await page.getByLabel(name).fill(value);await page.getByLabel('Arrival time').fill('11:00');await page.getByRole('button',{name:'Save intake'}).click();const newer=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(older)}`);await expect(page.locator(`[data-job-id="${older}"]`)).toHaveClass(/is-linked-job/);await page.locator('#queue-search').fill('civic');await expect(page.locator('.queue-job')).toHaveCount(1);await expect(page.locator('.queue-job')).toContainText('Second Customer');await page.locator('#queue-search').fill('SORT-');await expect(page.locator('.queue-job')).toHaveCount(2);await page.locator('#queue-sort').selectOption('oldest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',older);await page.locator('#queue-sort').selectOption('longest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',older);await page.locator('#queue-sort').selectOption('newest');await expect(page.locator('.queue-job').first()).toHaveAttribute('data-job-id',newer);await page.locator('#queue-filter').selectOption('Intake');await expect(page.locator('.queue-job')).toHaveCount(2);await page.getByRole('button',{name:/Inspection · 0/}).click();await expect(page.locator('.queue-empty-state')).toContainText('No jobs match');await page.goto('/tools/');await expect(page.getByRole('link',{name:/Queue \/ Job Status/})).toBeVisible();
  for(const width of [320,375,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('/tools/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`tools index overflow at ${width}px`).toBeTruthy();await expect(page.getByRole('link',{name:/Sound Analyzer/}).first()).toBeVisible();await expect(page.getByRole('link',{name:/Queue \/ Job Status/})).toBeVisible();await expect(page.getByRole('link',{name:/Service History & Warranty/})).toBeVisible();await page.goto('/tools/workshop/queue/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`queue overflow at ${width}px`).toBeTruthy();await expect(page.locator('#queue-search')).toBeVisible();await expect(page.locator('.queue-job').first()).toBeVisible();}
  await page.locator('#queue-search').focus();await expect(page.locator('#queue-search')).toBeFocused();await page.keyboard.press('Tab');await expect(page.locator('#queue-filter')).toBeFocused();await expect(page.locator('[data-status-filter="Intake"]')).toHaveAttribute('aria-pressed','false');
  expect(errors).toEqual([]);
});

test('Cancelled Work Order stays terminal through Waiting Parts, review links, and reload',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Name *').fill('Cancelled Test Customer');await page.getByLabel('License plate *').fill('WG-CANCEL-01');await page.getByLabel('Make').fill('Honda');await page.getByLabel('Model').fill('CB500');await page.getByRole('button',{name:'Save intake'}).click();
  const inspectionUrl=(await page.locator('#continue-inspection').getAttribute('href'))!,jobId=new URL(inspectionUrl,'http://local').searchParams.get('job')!;
  await page.goto(inspectionUrl);await chooseAll(page,'#inspection-checklist select','Good');await page.getByRole('button',{name:/Save inspection/}).click();
  await page.goto(`/tools/workshop/queue/?job=${encodeURIComponent(jobId)}`);let card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Inspection');await card.getByRole('link',{name:/Continue to Work Order/}).click();
  await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('In progress');await page.getByRole('button',{name:'Save Work Order'}).click();
  await page.goto('/tools/workshop/queue/');card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Work In Progress');page.once('dialog',dialog=>dialog.accept('External supplier delay'));await card.getByRole('button',{name:'Mark as Waiting Parts'}).click();await expect(card.locator('.queue-status-badge')).toHaveText('Waiting Parts');
  await card.getByRole('link',{name:/Continue to Work Order/}).click();await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Cancelled');await page.getByRole('button',{name:'Save Work Order'}).click();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);await expect(page.locator('#work-order-form select[name="status"]:not([data-field])')).toBeDisabled();
  await page.goto('/tools/workshop/queue/');card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Cancelled');await expect(card.getByRole('button',{name:'Mark as Waiting Parts'})).toHaveCount(0);await expect(card.getByRole('link',{name:/Review Cancelled Work Order/})).toHaveAttribute('href',new RegExp(`job=${encodeURIComponent(jobId)}`));
  await page.locator('#queue-filter').selectOption('Cancelled');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-search').fill('WG-CANCEL');await expect(page.locator('.queue-job')).toHaveCount(1);await page.locator('#queue-search').fill('Cancelled Test');await expect(page.locator('.queue-job')).toHaveCount(1);
  await card.locator('details summary').click();await expect(card.locator('.queue-timeline')).toContainText('Cancelled');await expect(card.locator('.queue-timeline')).toContainText('Work Order cancelled');
  await card.getByRole('link',{name:/Review Cancelled Work Order/}).click();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);await expect(page.locator('#work-order-form select[name="status"]:not([data-field])')).toBeDisabled();await expect(page.getByRole('button',{name:'Save Work Order'})).toBeDisabled();
  await page.goto(`/tools/workshop/qc-handover/?job=${encodeURIComponent(jobId)}`);await expect(page.locator('#qc-form')).toBeHidden();await expect(page.locator('#workshop-status')).toContainText(/cancelled.*read-only/i);
  await page.goto('/tools/workshop/service-history/');await page.getByLabel('Search plate, make, model or customer').fill('WG-CANCEL-01');await expect(page.getByLabel('Vehicle with completed services').locator('option')).toHaveCount(1);await expect(page.locator('#history-content')).toContainText('No completed service history found');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).warranties)).toEqual([]);
  await page.goto('/tools/workshop/queue/');await page.reload();card=page.locator(`[data-job-id="${jobId}"]`);await expect(card.locator('.queue-status-badge')).toHaveText('Cancelled');await expect(card.locator('details')).toContainText('Work Order cancelled');const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs[0]);expect(saved.workOrder.status).toBe('Cancelled');expect(saved.operations.history.at(-1).status).toBe('Cancelled');expect(errors).toEqual([]);
});

test('Service History projects actual services, supports explicit repeat visits, warranties, claims and next service',async({page})=>{
 test.setTimeout(60_000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-06-01T12:00:00Z')});
 await page.goto('/tools/workshop/vehicle-intake/');for(const [label,value]of [['Name *','History Customer'],['License plate *','WG-HISTORY-1'],['Make','Honda'],['Model','CB500'],['Odometer','1000'],['Complaint / reason for visit','Front brake noise']] as const)await page.getByLabel(label).fill(value);await page.getByRole('button',{name:'Save intake'}).click();const firstInspection=await page.locator('#continue-inspection').getAttribute('href'),firstJobId=new URL(firstInspection!,'http://local').searchParams.get('job')!;
 await page.goto(firstInspection!);await page.locator('[name="findings"]').fill('Brake pads worn');await chooseAll(page,'#inspection-checklist select','Good');await page.getByRole('button',{name:/Save inspection/}).click();const firstWorkOrder=await page.locator('#continue-work-order').getAttribute('href');
 await page.goto('/tools/workshop/parts-inventory/');await page.getByLabel('Part name').fill('Oil Filter');await page.getByLabel('SKU / part number').fill('OF-HISTORY');await page.getByLabel('Opening balance').fill('5');await page.getByRole('button',{name:'Save part'}).click();const partId=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).parts[0].id);
 await page.goto(firstWorkOrder!);await page.getByRole('button',{name:'Add part or material'}).click();await page.locator('#work-parts [data-field="partId"]').last().selectOption(partId);await page.locator('#work-parts input[name="quantity"]').last().fill('2');await page.getByRole('button',{name:'Add part or material'}).click();await page.locator('#work-parts input[name="name"]').last().fill('Shop cleaning solvent');await page.locator('#work-parts input[name="quantity"]').last().fill('1');await page.getByRole('button',{name:'Add actual work'}).click();await page.locator('#actual-work input[name="name"]').last().fill('Replace brake pads');await page.locator('#actual-work input[name="detail"]').last().fill('Front axle');await page.locator('#actual-work input[name="mechanic"]').last().fill('Alex Mechanic');await page.locator('#actual-work select[name="status"]').last().selectOption('Complete');await page.locator('#work-order-form input[name="mechanic"]:not([data-field])').fill('Workshop Lead');await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Complete');await page.getByRole('button',{name:'Save Work Order'}).click();
 await page.goto('/tools/workshop/parts-inventory/');await page.locator('#movement-form [name="type"]').selectOption('ISSUE_TO_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(firstJobId);await page.locator('#movement-form [name="quantity"]').fill('2');await page.getByRole('button',{name:'Record movement'}).click();await page.locator('#movement-form [name="type"]').selectOption('RETURN_FROM_JOB');await page.locator('#movement-form [name="jobId"]').selectOption(firstJobId);await page.locator('#movement-form [name="quantity"]').fill('1');await page.getByRole('button',{name:'Record movement'}).click();
 await page.goto(`/tools/workshop/qc-handover/?job=${encodeURIComponent(firstJobId)}`);await chooseAll(page,'select[name^="qccheck:"]','Pass');await page.locator('[name="finalStatus"]').selectOption('Ready for handover');await page.locator('[name="odometerBefore"]').fill('1000');await page.locator('[name="odometerAfter"]').fill('1010');await page.locator('[name="handoverRecipient"]').fill('History Customer');await page.locator('[name="handoverStaff"]').fill('Advisor');await page.locator('[name="handoverDate"]').fill('2026-06-01');await page.locator('[name="handoverTime"]').fill('12:00');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();await expect(page.locator('#job-completed')).toContainText('View Service History');
  const vehicleId=await page.evaluate(jobId=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!).jobs.find((j:{id:string})=>j.id===jobId).vehicleId,firstJobId);await page.goto('/tools/workshop/service-history/');await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);let service=page.locator('.history-service-card').first();await expect(service).toContainText('Replace brake pads');await expect(service).toContainText('Oil Filter × 1 each');await expect(service).toContainText('Documented free-text / non-stock materials');await expect(service).not.toContainText('Oil Filter × 2 each');await page.goto('/tools/workshop/parts-inventory/');const oilPart=page.locator('.parts-card').filter({hasText:'Oil Filter'}).first();await oilPart.getByRole('button',{name:'Edit'}).click();await page.locator('#part-form [name="name"]').fill('Oil Filter Renamed');await page.getByRole('button',{name:'Save part'}).click();await page.goto('/tools/workshop/service-history/');await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);service=page.locator('.history-service-card').first();await expect(service).toContainText('Oil Filter × 1 each');await expect(service).not.toContainText('Oil Filter Renamed');await expect(service.getByRole('link',{name:'View Completed Job'})).toHaveAttribute('href',new RegExp(`job=${encodeURIComponent(firstJobId)}`));await expect(page).toHaveURL('/tools/workshop/service-history/');await page.evaluate(()=>{window.print=()=>{document.documentElement.dataset.printed=document.querySelector('#print-title')?.textContent||'missing';};});await page.getByRole('button',{name:'Print / Save vehicle history'}).click();await expect(page.locator('html')).toHaveAttribute('data-printed',/Service History/);
 await service.locator('.history-follow-up details').first().locator('summary').click();let warrantyForm=service.locator('[data-warranty-form]');await warrantyForm.locator('[name="coverageType"]').selectOption('Labor and parts');await warrantyForm.locator('[name="coveredWork"]').check();await warrantyForm.locator('[name="coveredPartIds"]').check();await warrantyForm.locator('[name="expiryDate"]').fill('2027-06-02');await warrantyForm.locator('[name="expiryOdometer"]').fill('2000');await warrantyForm.locator('[name="terms"]').fill('Parts and labour coverage');await warrantyForm.getByRole('button',{name:'Save warranty'}).click();service=page.locator('.history-service-card').first();let warrantyCard=service.locator('.history-warranty-card');await expect(warrantyCard).toContainText('Labor and parts warranty');await expect(warrantyCard).toContainText('Active');
 await warrantyCard.locator('details summary').click();let claimForm=warrantyCard.locator('[data-claim-form]');await claimForm.locator('[name="odometer"]').fill('1020');await claimForm.locator('[name="issue"]').fill('Brake noise returned');await claimForm.locator('[name="resolution"]').fill('Adjusted caliper');await claimForm.locator('[name="claimStatus"]').selectOption('Resolved');await claimForm.getByRole('button',{name:'Save claim'}).click();service=page.locator('.history-service-card').first();warrantyCard=service.locator('.history-warranty-card');await expect(warrantyCard).toContainText('Resolved · Jun 1, 2026');await expect(warrantyCard).toContainText('Adjusted caliper');
 await service.locator('.history-follow-up details').last().locator('summary').click();let nextForm=service.locator('[data-next-service-form]');await nextForm.locator('[name="date"]').fill('2030-12-01');await nextForm.locator('[name="odometer"]').fill('1200');await nextForm.locator('[name="recommendation"]').fill('Oil service and chain check');await nextForm.getByRole('button',{name:'Save next service'}).click();service=page.locator('.history-service-card').first();await expect(service).toContainText('Upcoming');await expect(service).toContainText('Oil service and chain check');await page.reload();await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);service=page.locator('.history-service-card').first();await expect(service.locator('.history-warranty-card')).toContainText('Resolved');await expect(service).toContainText('Upcoming');
 await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Existing vehicle (optional)').selectOption(vehicleId);await expect(page.getByLabel('License plate *')).toHaveValue('WG-HISTORY-1');await page.getByLabel('Odometer').fill('1900');await page.getByLabel('Complaint / reason for visit').fill('Routine follow-up');await page.getByRole('button',{name:'Save intake'}).click();const secondInspection=await page.locator('#continue-inspection').getAttribute('href'),secondJobId=new URL(secondInspection!,'http://local').searchParams.get('job')!;const secondIdentity=await page.evaluate(({jobId,firstJobId})=>{const store=JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!);const first=store.jobs.find((j:{id:string})=>j.id===jobId);const original=store.jobs.find((j:{id:string})=>j.id===firstJobId);return {vehicleId:first.vehicleId,customerId:first.customerId,originalCustomerId:original?.customerId};},{jobId:secondJobId,firstJobId});expect(secondIdentity.vehicleId).toBe(vehicleId);expect(secondIdentity.customerId).toBe(secondIdentity.originalCustomerId);
 await page.goto(secondInspection!);await chooseAll(page,'#inspection-checklist select','Good');await page.getByRole('button',{name:/Save inspection/}).click();await page.locator('#continue-work-order').click();await page.getByRole('button',{name:'Add actual work'}).click();await page.locator('#actual-work input[name="name"]').last().fill('Adjust chain tension');await page.locator('#actual-work select[name="status"]').last().selectOption('Complete');await page.locator('#work-order-form select[name="status"]:not([data-field])').selectOption('Complete');await page.getByRole('button',{name:'Save Work Order'}).click();await page.locator('#continue-qc').click();await chooseAll(page,'select[name^="qccheck:"]','Pass');await page.locator('[name="finalStatus"]').selectOption('Ready for handover');await page.locator('[name="odometerBefore"]').fill('1900');await page.locator('[name="odometerAfter"]').fill('2001');await page.locator('[name="handoverRecipient"]').fill('History Customer');await page.locator('[name="handoverStaff"]').fill('Advisor');await page.locator('[name="handoverDate"]').fill('2026-06-02');await page.locator('[name="handoverTime"]').fill('12:00');await page.getByRole('button',{name:'Complete job'}).click();await expect(page.locator('#job-completed')).toBeVisible();
 await page.clock.setFixedTime(new Date('2026-06-02T12:00:00Z'));await page.goto('/tools/workshop/service-history/');await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);await expect(page.locator('.history-service-card')).toHaveCount(2);expect(await page.locator('.history-service-card').first().getAttribute('data-history-job')).toBe(secondJobId);await expect(page.locator('.history-service-card').first()).toContainText('Adjust chain tension');await expect(page.locator('.history-service-card').last()).toContainText('Replace brake pads');await expect(page.locator('.history-service-card').last().locator('.history-warranty-card')).toContainText('Expired');await expect(page.locator('#history-content')).toContainText('Due by Odometer');let secondService=page.locator('.history-service-card').first();await secondService.locator('.history-follow-up details').first().locator('summary').click();const secondWarrantyForm=secondService.locator('[data-warranty-form]');await secondWarrantyForm.locator('[name="coveredWork"]').check();await secondWarrantyForm.locator('[name="expiryDate"]').fill('2026-06-02');await secondWarrantyForm.locator('[name="expiryOdometer"]').fill('3000');await secondWarrantyForm.getByRole('button',{name:'Save warranty'}).click();secondService=page.locator('.history-service-card').first();await expect(secondService.locator('.history-warranty-card')).toContainText('Active');
 await page.clock.setFixedTime(new Date('2026-06-03T12:00:00Z'));await page.reload();await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);await expect(page.locator('.history-service-card').first().locator('.history-warranty-card')).toContainText('Expired');await expect(page.locator('.history-service-card').last().locator('.history-warranty-card')).toContainText('Expired');const persisted=await page.evaluate(()=>JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!));expect(persisted.warranties).toHaveLength(2);expect(persisted.warrantyClaims).toHaveLength(1);expect(persisted.nextServices).toHaveLength(1);expect(persisted.jobs.filter((j:{vehicleId:string})=>j.vehicleId===vehicleId)).toHaveLength(2);await page.goto('/tools/workshop/vehicle-intake/');await page.getByLabel('Existing vehicle (optional)').selectOption(vehicleId);await page.getByLabel('Customer record').selectOption('');await page.getByLabel('Name *').fill('Different Vehicle Owner');await page.getByLabel('Odometer').fill('2010');await page.getByLabel('Complaint / reason for visit').fill('New owner intake');await page.getByRole('button',{name:'Save intake'}).click();const changedOwnerJobId=new URL((await page.locator('#continue-inspection').getAttribute('href'))!,'http://local').searchParams.get('job')!;const changedIdentity=await page.evaluate(jobId=>{const store=JSON.parse(localStorage.getItem('workshopgirl.workshop.operations.v1')!);const job=store.jobs.find((j:{id:string})=>j.id===jobId);return {...job,customerName:store.customers.find((c:{id:string})=>c.id===job.customerId)?.name};},changedOwnerJobId);expect(changedIdentity.vehicleId).toBe(vehicleId);expect(changedIdentity.customerId).not.toBe(persisted.jobs.find((j:{id:string})=>j.id===firstJobId).customerId);expect(changedIdentity.customerName).toBe('Different Vehicle Owner');await page.goto('/tools/workshop/service-history/');await page.getByLabel('Search plate, make, model or customer').fill('WG-HISTORY-1');await page.getByLabel('Vehicle with completed services').selectOption(vehicleId);expect(persisted.partMovements.map((m:{type:string})=>m.type)).toEqual(['OPENING','ISSUE_TO_JOB','RETURN_FROM_JOB']);for(const width of [320,375,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`service history overflow at ${width}px`).toBeTruthy();}await page.locator('#history-search').focus();await expect(page.locator('#history-search')).toBeFocused();await page.keyboard.press('Tab');await expect(page.locator('#history-vehicle')).toBeFocused();expect(await page.locator('#history-vehicle').evaluate(node=>getComputedStyle(node).outlineStyle)).toBe('solid');expect(errors).toEqual([]);
});

for(const route of ['/tools/workshop/vehicle-intake/','/tools/workshop/inspection-estimate/','/tools/workshop/work-order/','/tools/workshop/qc-handover/','/tools/workshop/parts-inventory/','/tools/workshop/service-history/','/tools/workshop/procurement/'])test(`direct load ${route}`,async({page})=>{await page.goto(route);await expect(page).toHaveTitle(/Workshop|Procurement/);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('meta[name="description"]')).toHaveAttribute('content',/.+/);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',`https://workshopgirl.com${route}`);await expect(page.locator('body')).not.toContainText('bisnis.cc');});
