import test from 'node:test';
import assert from 'node:assert/strict';
import { emptyStore, createJob, loadStore, setWaitingParts, saveStore } from '../src/lib/workshop/store.ts';
import { adjustStock, createPart, deactivatePart, issueToJob, jobPartSummary, jobShortage, partBalance, returnFromJob, stockIn, stockState, updatePart, movementsForJob, clearWaitingForParts } from '../src/lib/workshop/parts.ts';
import type { WorkshopPart } from '../src/lib/workshop/model.ts';
const intake={number:'WI-1',complaint:'Test',accessories:[],conditionNotes:'',date:'2026-09-27',arrivalTime:'10:00'};
const input:Omit<WorkshopPart,'id'|'createdAt'|'updatedAt'>={sku:'OF-1',name:'Oil filter',category:'Filter',brand:'Maker',unit:'each',location:'Shelf A',supplier:'Supplier',minimumStock:1,barcode:'TEXT',compatibility:'Bike',active:true};
function fixture(){const store=emptyStore(),job=createJob(store,{customer:{name:'Test',phone:'',address:''},vehicle:{type:'Motorcycle',plate:'T-1',make:'A',model:'B',year:2020,color:'',odometer:null},intake},p=>`${p}_1`);return {store,job};}
test('part create, edit, duplicate SKU and deactivate retain movement history',()=>{const s=emptyStore();assert.equal(createPart(s,input,2).ok,true);const p=s.parts[0]!;assert.equal(partBalance(s,p.id),2);assert.equal(createPart(s,{...input,name:'Copy'}).ok,false);assert.equal(updatePart(s,p.id,{name:'Oil filter premium'}).ok,true);assert.equal(deactivatePart(s,p.id).ok,true);assert.equal(s.partMovements.length,1);assert.equal(s.parts.length,1);});
test('SKU comparison ignores case and blank SKU may repeat',()=>{const s=emptyStore();createPart(s,{...input,sku:''});assert.equal(createPart(s,{...input,sku:'',name:'Clips'}).ok,true);createPart(s,input);assert.equal(createPart(s,{...input,sku:'of-1'}).ok,false);});
test('opening, receipt, issue, return and adjustments derive balance from ledger',()=>{const {store,job}=fixture();createPart(store,input,3);const p=store.parts[0]!;assert.equal(stockIn(store,p.id,2,{note:'delivery'}).ok,true);assert.equal(issueToJob(store,p.id,job.id,2).ok,true);assert.equal(returnFromJob(store,p.id,job.id,1).ok,true);assert.equal(adjustStock(store,p.id,'in',2,'count found').ok,true);assert.equal(adjustStock(store,p.id,'out',1,'damaged').ok,true);assert.equal(partBalance(store,p.id),5);assert.deepEqual(store.partMovements.map(x=>x.type),['OPENING','STOCK_IN','ISSUE_TO_JOB','RETURN_FROM_JOB','ADJUSTMENT_IN','ADJUSTMENT_OUT']);});
test('release ledger example 10 + 5 - 3 + 1 - 2 equals 11',()=>{const {store,job}=fixture();createPart(store,input,10);const p=store.parts[0]!;stockIn(store,p.id,5);issueToJob(store,p.id,job.id,3);returnFromJob(store,p.id,job.id,1);adjustStock(store,p.id,'out',2,'count correction');assert.equal(partBalance(store,p.id),11);});
test('invalid quantity, cost, insufficient stock, and adjustment below zero are blocked',()=>{const {store,job}=fixture();createPart(store,input,1);const id=store.parts[0]!.id;assert.equal(stockIn(store,id,0).ok,false);assert.equal(stockIn(store,id,1,{unitCost:-1}).ok,false);assert.equal(issueToJob(store,id,job.id,-1).ok,false);assert.equal(issueToJob(store,id,job.id,2).ok,false);assert.equal(adjustStock(store,id,'out',2,'loss').ok,false);assert.equal(adjustStock(store,id,'out',1,'').ok,false);assert.equal(partBalance(store,id),1);});
test('issue records exact job ID and linked movements and return balance',()=>{const {store,job}=fixture();createPart(store,input,4);const id=store.parts[0]!.id;assert.equal(issueToJob(store,id,job.id,2).ok,true);assert.equal(store.partMovements.at(-1)?.jobId,job.id);assert.equal(movementsForJob(store,job.id).length,1);assert.equal(returnFromJob(store,id,job.id,3).ok,false);assert.equal(returnFromJob(store,id,job.id,1).ok,true);assert.equal(partBalance(store,id),3);});
test('cancelled and completed jobs cannot receive new issues; historical returns remain allowed',()=>{const {store,job}=fixture();createPart(store,input,4);const id=store.parts[0]!.id;assert.equal(issueToJob(store,id,job.id,1).ok,true);job.workOrder={number:'WO',date:'2026-09-27',status:'Cancelled',mechanic:'',approvedWork:[],actualWork:[],parts:[],changes:[],startTime:'',endTime:'',mechanicNotes:'',result:'',recommendations:'',signoff:''};assert.equal(issueToJob(store,id,job.id,1).ok,false);assert.equal(returnFromJob(store,id,job.id,1).ok,true);});
test('linked shortage responds to receipts and Waiting Parts can be cleared without changing work state',()=>{const {store,job}=fixture();createPart(store,input,0);const p=store.parts[0]!;job.workOrder={number:'WO',date:'2026-09-27',status:'In progress',mechanic:'',approvedWork:[],actualWork:[],parts:[{id:'row',name:p.name,partNumber:p.sku,quantity:2,unit:p.unit,notes:'',partId:p.id}],changes:[],startTime:'',endTime:'',mechanicNotes:'',result:'',recommendations:'',signoff:''};assert.equal(jobPartSummary(store,job)[0]?.shortage,2);assert.equal(jobShortage(store,job),2);assert.equal(setWaitingParts(store,job.id,true)?.operations?.waitingParts,true);assert.equal(stockIn(store,p.id,2).ok,true);assert.equal(jobShortage(store,job),0);assert.equal(clearWaitingForParts(store,job.id),true);assert.equal(job.operations?.waitingParts,false);assert.equal(job.workOrder.status,'In progress');});
test('inactive part cannot issue and status derives from ledger and minimum',()=>{const {store,job}=fixture();createPart(store,input,2);const p=store.parts[0]!;assert.equal(stockState(store,p),'In Stock');assert.equal(deactivatePart(store,p.id).ok,true);assert.equal(issueToJob(store,p.id,job.id,1).ok,false);});
test('legacy Phase 1/2A data without inventory collections loads without losing job IDs',()=>{const {store,job}=fixture();const old={version:1,customers:store.customers,vehicles:store.vehicles,jobs:store.jobs};const disk={getItem:()=>JSON.stringify(old),setItem:()=>{}};const loaded=loadStore(disk);assert.equal(loaded.recovered,false);assert.equal(loaded.store.jobs[0]?.id,job.id);assert.deepEqual(loaded.store.parts,[]);assert.deepEqual(loaded.store.partMovements,[]);assert.equal(saveStore(loaded.store,{getItem:()=>null,setItem:()=>{}}).ok,true);});
test('malformed inventory collections recover without overwriting stored data',()=>{const raw=JSON.stringify({version:1,customers:[],vehicles:[],jobs:[],parts:[{broken:true}],partMovements:[]});let written='';const loaded=loadStore({getItem:()=>raw,setItem:(_k,v)=>{written=v;}});assert.equal(loaded.recovered,true);assert.equal(written,'');});
