import test from 'node:test';
import assert from 'node:assert/strict';
import { createJob, emptyStore, loadStore } from '../src/lib/workshop/store.ts';
import { returnFromJob } from '../src/lib/workshop/parts.ts';
import { completedService, createWarranty, createWarrantyClaim, latestKnownOdometer, nextServiceStatus, saveNextService, serviceHistory, vehicleHistorySearch, warrantyStatus } from '../src/lib/workshop/history.ts';
import type { NextService, WorkshopJob, WorkshopStore } from '../src/lib/workshop/model.ts';

const date='2026-04-10',base={customer:{name:'History Customer',phone:'555',address:''},vehicle:{type:'Motorcycle' as const,plate:'HIST-1',make:'Honda',model:'CB500',year:2021,color:'Black',odometer:1000},intake:{number:'WI-HIST',complaint:'Brake noise',accessories:[],conditionNotes:'',date,arrivalTime:'10:00'}};
const qc={number:'QC-H',date,inspector:'Inspector',mechanic:'QC Tech',finalStatus:'Ready for handover' as const,checks:[{name:'Brakes',result:'Pass' as const,note:''}],unresolvedIssues:[],returnedItems:[],roadTest:'Completed' as const,roadTester:'Road Tester',odometerBefore:1000,odometerAfter:1010,roadTestNotes:'Quiet',readinessNotes:'Ready',recommendations:'',customerNotes:'Call if needed',handoverRecipient:'Customer',handoverStaff:'Desk',handoverDate:date,handoverTime:'12:00'};
function completed(store=emptyStore(),idPrefix='one',serviceDate=date){const job=createJob(store,{...base,intake:{...base.intake,date:serviceDate}},p=>`${p}_${idPrefix}`,new Date(`${serviceDate}T12:00:00Z`));job.inspection={findings:'Pads worn',checklist:[],recommendedJobs:[{id:'rec',name:'Planned recommendation',detail:'not actual',priority:'Recommended',approved:true}],parts:[],labor:[],consumables:0,additionalCost:0,discount:0,taxRate:0};job.workOrder={number:`WO-${idPrefix}`,date:serviceDate,status:'Complete',mechanic:'Primary Tech',approvedWork:[{id:'planned',name:'Planned work',detail:'',status:'Complete',mechanic:''}],actualWork:[{id:'actual',name:'Replace brake pads',detail:'Front axle',status:'Complete',mechanic:'Actual Tech'},{id:'unfinished',name:'Inspect rear tire',detail:'',status:'In progress',mechanic:'Other Tech'}],parts:[{id:'stock',name:'Oil Filter',partNumber:'OF-1',quantity:2,unit:'each',notes:'Linked',partId:'part_oil'},{id:'free',name:'Cleaning solvent',partNumber:'',quantity:1,unit:'bottle',notes:'Shop supply'}],changes:[],startTime:'10:00',endTime:'12:00',mechanicNotes:'Actual notes',result:'Repair done',recommendations:'Retorque soon',signoff:'Tech'};job.qc={...structuredClone(qc),date:serviceDate,handoverDate:serviceDate};job.status='completed';job.serviceOdometer=1010;return job;}
const partInput={sku:'OF-1',name:'Oil Filter',category:'Filter',brand:'Maker',unit:'each',location:'Shelf',supplier:'',minimumStock:0,compatibility:'',active:true};
function part(store:WorkshopStore){const at=new Date(`${date}T10:00:00Z`).toISOString();store.parts.push({...partInput,id:'part_oil',createdAt:at,updatedAt:at});store.partMovements.push({id:'opening_oil',partId:'part_oil',type:'OPENING',quantity:5,at});}
function issue(store:WorkshopStore,job:WorkshopJob,quantity:number){store.partMovements.push({id:`issue_${store.partMovements.length}`,partId:'part_oil',jobId:job.id,type:'ISSUE_TO_JOB',quantity,at:`${date}T11:00:00Z`});}
function warranty(store:WorkshopStore,job:WorkshopJob,overrides:Partial<Parameters<typeof createWarranty>[1]>={}){const coverageType=overrides.coverageType??'Labor',coversLabor=coverageType==='Labor'||coverageType==='Labor and parts',coversParts=coverageType==='Parts'||coverageType==='Labor and parts';const result=createWarranty(store,{jobId:job.id,coverageType,coveredWork:overrides.coveredWork??(coversLabor?['Replace brake pads']:[]),coveredPartIds:overrides.coveredPartIds??(coversParts?['part_oil']:[]),expiryDate:'2026-12-31',...overrides},p=>`${p}_1`,new Date('2026-04-10T12:00:00Z'));if(!result.ok)throw new Error(result.message);return result.value;}

test('history projection includes only completed QC-passed jobs and excludes cancellations and in-progress states',()=>{const s=emptyStore(),done=completed(s);const cancelled=createJob(s,base,p=>`${p}_cancel`);cancelled.workOrder={...done.workOrder!,status:'Cancelled'};const active=createJob(s,base,p=>`${p}_active`);active.status='work-order';const pickup=createJob(s,base,p=>`${p}_pickup`);pickup.qc=structuredClone(qc);assert.deepEqual(serviceHistory(s).map(x=>x.jobId),[done.id]);assert.equal(completedService(cancelled,s),null);assert.equal(completedService(active,s),null);assert.equal(completedService(pickup,s),null);});
test('projection preserves exact job and stable vehicle IDs plus customer and odometer context',()=>{const s=emptyStore(),job=completed(s);const item=serviceHistory(s)[0]!;assert.equal(item.jobId,job.id);assert.equal(item.vehicleId,job.vehicleId);assert.equal(item.customerName,'History Customer');assert.equal(item.odometer,1010);});
test('actual work excludes recommendations, planned work, and unfinished rows',()=>{const s=emptyStore(),job=completed(s);const item=completedService(job,s)!;assert.deepEqual(item.actualWork.map(x=>x.name),['Replace brake pads']);assert.equal(item.technician,'Actual Tech');});
test('actual inventory consumption is issue minus return and excludes adjustments and requested quantity',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,2);assert.equal(returnFromJob(s,'part_oil',job.id,1).ok,true);s.partMovements.push({id:'adj',partId:'part_oil',type:'ADJUSTMENT_IN',quantity:4,at:date});const item=completedService(job,s)!;assert.deepEqual(item.consumedParts.map(x=>({name:x.name,quantity:x.quantity})),[{name:'Oil Filter',quantity:1}]);});
test('zero-net issued inventory is omitted while free-text materials remain distinct',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,2);assert.equal(returnFromJob(s,'part_oil',job.id,2).ok,true);const item=completedService(job,s)!;assert.deepEqual(item.consumedParts,[]);assert.equal(item.freeTextMaterials[0]?.name,'Cleaning solvent');assert.equal(item.freeTextMaterials[0]?.quantity,1);});
test('late valid return changes the derived completed history without deleting ledger events',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,2);const first=serviceHistory(s)[0]!.consumedParts[0]!.quantity;assert.equal(first,2);returnFromJob(s,'part_oil',job.id,1);assert.equal(serviceHistory(s)[0]!.consumedParts[0]!.quantity,1);assert.deepEqual(s.partMovements.map(x=>x.type),['OPENING','ISSUE_TO_JOB','RETURN_FROM_JOB']);});
test('one stable vehicle builds a newest-first timeline across explicit repeat visits',()=>{const s=emptyStore(),first=completed(s,'first','2026-02-01');const second=createJob(s,{...base,vehicle:{...base.vehicle,odometer:1100},intake:{...base.intake,number:'WI-SECOND',date:'2026-05-01'},existingVehicleId:first.vehicleId},p=>`${p}_second`,new Date('2026-05-01T12:00:00Z'));assert.equal(second.vehicleId,first.vehicleId);second.qc={...structuredClone(qc),date:'2026-05-01',handoverDate:'2026-05-01',odometerBefore:1100,odometerAfter:1110};second.workOrder={...first.workOrder!,number:'WO-second'};second.status='completed';second.serviceOdometer=1110;const history=serviceHistory(s,first.vehicleId);assert.deepEqual(history.map(x=>x.jobId),[second.id,first.id]);assert.deepEqual(history.map(x=>x.odometer),[1110,1010]);assert.equal(latestKnownOdometer(s,first.vehicleId),1110);assert.equal(vehicleHistorySearch(s,'hist-1')[0]?.id,first.vehicleId);});
test('warranty creation requires completed service, limits duplicate warranties, and uses exact job/vehicle IDs',()=>{const s=emptyStore(),job=completed(s),draft=createJob(s,base);assert.equal(createWarranty(s,{jobId:draft.id,coverageType:'Labor',coveredWork:['Replace brake pads'],coveredPartIds:[],expiryDate:'2026-12-31'}).ok,false);const w=warranty(s,job);assert.equal(w.jobId,job.id);assert.equal(w.vehicleId,job.vehicleId);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Labor',coveredWork:['Replace brake pads'],coveredPartIds:[],expiryDate:'2026-12-31'}).ok,false);});
test('warranty validation rejects invalid date order, below-service odometer, unrelated coverage, and missing limits',()=>{const s=emptyStore(),job=completed(s);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Labor',coveredWork:['Replace brake pads'],coveredPartIds:[],expiryDate:'2026-04-09'}).ok,false);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Labor',coveredWork:['Replace brake pads'],coveredPartIds:[],expiryOdometer:1009}).ok,false);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Labor',coveredWork:['Planned recommendation'],coveredPartIds:[],expiryDate:'2026-12-31'}).ok,false);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Labor',coveredWork:['Replace brake pads'],coveredPartIds:[]}).ok,false);});
test('warranty date status is active through its expiry date and expires the day after',()=>{const s=emptyStore(),job=completed(s),w=warranty(s,job,{expiryDate:'2026-04-20'});assert.equal(warrantyStatus(w,1010,'2026-04-19'),'Active');assert.equal(warrantyStatus(w,1010,'2026-04-20'),'Active');assert.equal(warrantyStatus(w,1010,'2026-04-21'),'Expired');});
test('warranty odometer status is active below and at the limit, expired above, and unknown without a reading',()=>{const s=emptyStore(),job=completed(s),w=warranty(s,job,{expiryDate:null,expiryOdometer:1200});assert.equal(warrantyStatus(w,1199,'2026-05-01'),'Active');assert.equal(warrantyStatus(w,1200,'2026-05-01'),'Active');assert.equal(warrantyStatus(w,1201,'2026-05-01'),'Expired');assert.equal(warrantyStatus(w,null,'2026-05-01'),'Odometer unknown');});
test('date and odometer limits expire warranty if either applicable limit is exceeded',()=>{const s=emptyStore(),job=completed(s),w=warranty(s,job,{expiryDate:'2026-04-20',expiryOdometer:1200});assert.equal(warrantyStatus(w,1100,'2026-04-21'),'Expired');assert.equal(warrantyStatus(w,1201,'2026-04-19'),'Expired');});
test('parts and combined coverage can only select parts actually consumed',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,2);const w=warranty(s,job,{coverageType:'Parts',coveredWork:[],coveredPartIds:['part_oil'],expiryOdometer:1300,expiryDate:null});assert.deepEqual(w.coveredPartIds,['part_oil']);assert.equal(createWarranty(s,{jobId:job.id,coverageType:'Parts',coveredWork:[],coveredPartIds:['unrelated'],expiryDate:'2026-12-01'}).ok,false);});
test('claims persist with stable IDs and do not mutate completed jobs, inventory, or queue state',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,1);const w=warranty(s,job);const before=structuredClone(job),movements=structuredClone(s.partMovements);const result=createWarrantyClaim(s,{warrantyId:w.id,date:'2026-06-01',odometer:1050,issue:'Noise returned',notes:'Documented'},p=>`${p}_claim`,new Date('2026-06-01T12:00:00Z'));assert.equal(result.ok,true);assert.equal(s.warrantyClaims[0]?.id,'claim_claim');assert.equal(s.warrantyClaims[0]?.warrantyId,w.id);assert.deepEqual(job,before);assert.deepEqual(s.partMovements,movements);assert.equal(job.status,'completed');});
test('claim validation requires a warranty, issue, valid date, and non-regressing odometer',()=>{const s=emptyStore(),job=completed(s),w=warranty(s,job);assert.equal(createWarrantyClaim(s,{warrantyId:'missing',date:date,odometer:null,issue:'x'}).ok,false);assert.equal(createWarrantyClaim(s,{warrantyId:w.id,date:'2026-04-09',odometer:null,issue:'x'}).ok,false);assert.equal(createWarrantyClaim(s,{warrantyId:w.id,date:'2026-05-01',odometer:1009,issue:'x'}).ok,false);assert.equal(createWarrantyClaim(s,{warrantyId:w.id,date:'2026-05-01',odometer:null,issue:'  '}).ok,false);});
test('next-service status handles date, odometer, both, upcoming, and unknown mileage honestly',()=>{const item:NextService={id:'n',jobId:'j',vehicleId:'v',date:'2026-06-01',odometer:1200,recommendation:'Oil service',createdAt:'',updatedAt:''};assert.equal(nextServiceStatus(item,1100,'2026-05-01'),'Upcoming');assert.equal(nextServiceStatus(item,1200,'2026-05-01'),'Due by Odometer');assert.equal(nextServiceStatus(item,1100,'2026-06-01'),'Due by Date');assert.equal(nextServiceStatus(item,1200,'2026-06-01'),'Due');assert.equal(nextServiceStatus(item,null,'2026-05-01'),'Odometer unknown');});
test('next-service recommendation requires a completed job and validates date and odometer',()=>{const s=emptyStore(),job=completed(s),draft=createJob(s,base);assert.equal(saveNextService(s,{jobId:draft.id,date:date,odometer:null,recommendation:'Oil'}).ok,false);assert.equal(saveNextService(s,{jobId:job.id,date:'bad',odometer:null,recommendation:'Oil'}).ok,false);assert.equal(saveNextService(s,{jobId:job.id,date:null,odometer:1009,recommendation:'Oil'}).ok,false);assert.equal(saveNextService(s,{jobId:job.id,date:null,odometer:null,recommendation:''}).ok,false);});
test('next-service metadata saves once per service and updates in place',()=>{const s=emptyStore(),job=completed(s);const first=saveNextService(s,{jobId:job.id,date:'2026-06-01',odometer:1200,recommendation:'Oil service'},p=>`${p}_id`);assert.equal(first.ok,true);const again=saveNextService(s,{jobId:job.id,date:null,odometer:1250,recommendation:'Valve check'});assert.equal(again.ok,true);assert.equal(s.nextServices.length,1);assert.equal(s.nextServices[0]?.odometer,1250);});
test('Phase 1/2A/2B shaped stores initialize optional follow-up collections without changing IDs or ledger',()=>{const s=emptyStore(),job=completed(s);part(s);issue(s,job,1);const legacy={version:1,customers:s.customers,vehicles:s.vehicles,jobs:s.jobs,parts:s.parts,partMovements:s.partMovements};let raw=JSON.stringify(legacy);const storage={getItem:()=>raw,setItem:(_key:string,value:string)=>{raw=value;}};const loaded=loadStore(storage);assert.equal(loaded.recovered,false);assert.equal(loaded.store.jobs[0]?.id,job.id);assert.equal(loaded.store.vehicles[0]?.id,job.vehicleId);assert.equal(loaded.store.partMovements.length,s.partMovements.length);assert.deepEqual(loaded.store.warranties,[]);assert.deepEqual(loaded.store.warrantyClaims,[]);assert.deepEqual(loaded.store.nextServices,[]);assert.equal(serviceHistory(loaded.store)[0]?.jobId,job.id);assert.equal(JSON.parse(raw).warranties,undefined);});
test('warranty, claim, and next-service collections survive local storage reload',()=>{const s=emptyStore(),job=completed(s),w=warranty(s,job);createWarrantyClaim(s,{warrantyId:w.id,date:'2026-04-11',odometer:1011,issue:'Noise'});saveNextService(s,{jobId:job.id,date:'2026-10-10',odometer:1500,recommendation:'Oil service'});let raw=JSON.stringify(s);const loaded=loadStore({getItem:()=>raw,setItem:(_key:string,value:string)=>{raw=value;}}).store;assert.equal(loaded.warranties[0]?.id,w.id);assert.equal(loaded.warrantyClaims.length,1);assert.equal(loaded.nextServices.length,1);assert.equal(loaded.jobs[0]?.id,job.id);});
