import { selectedWorkshopJob, workshopJobParams } from '../../lib/workshop/navigation.ts';
import { selectWorkshopJob } from './navigation.ts';
import type { WorkshopInvoice, WorkshopInvoiceLine, WorkshopJob, WorkshopPayment, WorkshopPaymentMethod, WorkshopStore } from '../../lib/workshop/model.ts';
import { addManualLine, allPaymentsForInvoice, billingSummary, calculateInvoice, createDraft, createReplacementDraft, draftNeedsRefresh, eligibleForDraft, formatQuantity, invoiceDiscrepancies, issueInvoice, netPaid, outstanding, paymentBalanceAfter, paymentStatus, QUANTITY_SCALE, recordPayment, refreshDraft, reversePayment, updateDraftLine, voidInvoice } from '../../lib/workshop/billing.ts';
import { cloneStore, getCustomer, getVehicle, saveStore } from '../../lib/workshop/store.ts';
import { workflowStatus } from '../../lib/workshop/queue.ts';

const $=<T extends HTMLElement>(root:ParentNode,selector:string)=>root.querySelector<T>(selector);
const idText=(prefix:string)=>`${prefix}_${globalThis.crypto?.randomUUID?.()??`${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`}`;
const money=(value:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value);
const dateText=(value:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value));
const make=(tag:string,className?:string,text?:string):HTMLElement=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
const controlId=()=>idText('billing-control');

export function mountBilling(root:HTMLElement,initial:WorkshopStore):void {
  let store=initial,selectedId=initial.invoices.find(invoice=>invoice.jobId===selectedWorkshopJob(initial,workshopJobParams(new URL(location.href)))?.id&&invoice.status!=='Void')?.invoiceId??'',query='',filter='All';
  const status=$<HTMLElement>(root,'#billing-message')!,summary=$<HTMLElement>(root,'#billing-summary')!,jobs=$<HTMLElement>(root,'#billing-jobs')!,list=$<HTMLElement>(root,'#billing-list')!,detail=$<HTMLElement>(root,'#billing-detail')!;
  const alert=(message:string)=>{status.textContent=message;status.hidden=!message;};
  const selected=()=>store.invoices.find(i=>i.invoiceId===selectedId)??null;
  const jobFor=(invoice:WorkshopInvoice)=>store.jobs.find(j=>j.id===invoice.jobId)??null;
  const saveMutation=(action:()=>void,redraw=true):void=>{
    const before=cloneStore(store);try{action();const result=saveStore(store,window.localStorage);if(!result.ok){store=before;alert(result.message);render();return;}alert('Billing record saved locally.');if(redraw)render();else refreshVisibleCalculations();}catch(error){store=before;alert(error instanceof Error?error.message:'Billing change could not be saved.');render();}
  };
  const refreshVisibleCalculations=():void=>{const invoice=selected();if(!invoice)return;for(const card of Array.from(detail.querySelectorAll<HTMLElement>('[data-line-id]'))){const line=invoice.lines.find(item=>item.lineId===card.dataset.lineId);const amount=card.querySelector<HTMLElement>('.billing-line-total');if(line&&amount)amount.textContent=`Line total: ${money(line.lineTotal)}`;}for(const row of Array.from(detail.querySelectorAll<HTMLElement>('[data-billing-total]'))){const key=row.dataset.billingTotal as 'Subtotal'|'Discount'|'Tax'|'Total'|undefined,value=key==='Subtotal'?invoice.subtotal:key==='Discount'?invoice.discount:key==='Tax'?invoice.taxAmount:key==='Total'?invoice.grandTotal:undefined;const strong=row.querySelector('strong');if(strong&&value!==undefined)strong.textContent=money(value);}};
  const label=(title:string,control:HTMLElement):HTMLLabelElement=>{const node=document.createElement('label');node.append(make('span',undefined,title),control);return node;};
  const input=(type:string,value:string,attrs:Record<string,string>={}):HTMLInputElement=>{const node=document.createElement('input');node.type=type;node.value=value;for(const [key,val]of Object.entries(attrs))node.setAttribute(key,val);return node;};
  const button=(text:string,action:()=>void,kind='secondary'):HTMLButtonElement=>{const node=document.createElement('button');node.type='button';node.className=kind==='danger'?'button-danger':kind==='primary'?'':'button-secondary';node.textContent=text;node.addEventListener('click',action);return node;};
  function render():void {
    const invoice=selected();if(invoice)selectWorkshopJob(root,invoice.jobId);
    renderSummary();renderJobs();renderInvoices();renderDetail();
  }
  function renderSummary():void {
    const invoices=store.invoices,counts=['Draft','Unpaid','Partially Paid','Paid'].map(state=>({state,count:invoices.filter(i=>state==='Draft'?i.status==='Draft':i.status==='Issued'&&paymentStatus(store,i)===state).length}));
    summary.replaceChildren(...counts.map(row=>{const card=make('div','billing-count');card.append(make('span',undefined,row.state),make('strong',undefined,String(row.count)));return card;}));
  }
  function renderJobs():void {
    jobs.replaceChildren();
    const eligible=store.jobs.filter(job=>eligibleForDraft(job)&&!store.invoices.some(i=>i.jobId===job.id&&i.status!=='Void'));
    const cancelled=store.jobs.filter(job=>workflowStatus(job)==='Cancelled'&&!store.invoices.some(i=>i.jobId===job.id&&i.status!=='Void'));
    if(!eligible.length&&!cancelled.length){jobs.append(make('p','billing-empty','No eligible jobs without an active Invoice.'));return;}
    if(eligible.length){jobs.append(make('h3',undefined,'Ready for Billing'));for(const job of eligible){const card=jobCard(job);card.append(button('Create Draft',()=>saveMutation(()=>{const invoice=createDraft(store,job);selectedId=invoice.invoiceId;}),'primary'));jobs.append(card);}}
    if(cancelled.length){const details=document.createElement('details');details.className='billing-exception';details.append(make('summary',undefined,`Exceptional billing for Cancelled Jobs (${cancelled.length})`));const note=make('p',undefined,'Cancelled jobs are never billed from unfinished work automatically. Create a draft only for a specific, explained manual charge.');details.append(note);for(const job of cancelled){const card=jobCard(job),reason=input('text','',{required:'',maxlength:'240'});reason.id=controlId();reason.placeholder='Required billing reason';card.append(label('Reason for exceptional charge',reason),button('Create Manual Draft',()=>{if(!reason.value.trim()){reason.reportValidity();return;}saveMutation(()=>{const invoice=createDraft(store,job,new Date(),reason.value);selectedId=invoice.invoiceId;});},'primary'));details.append(card);}jobs.append(details);}
  }
  function jobCard(job:WorkshopJob):HTMLElement {
    const customer=getCustomer(store,job),vehicle=getVehicle(store,job),card=make('article','billing-job-card');card.append(make('strong',undefined,`${vehicle?.plate||'No plate'} · ${job.number}`),make('span',undefined,`${customer?.name||'Customer not recorded'} · ${workflowStatus(job)}`));return card;
  }
  function renderInvoices():void {
    list.replaceChildren();const search=document.createElement('input');search.type='search';search.value=query;search.placeholder='Invoice, customer, plate, vehicle or job';search.setAttribute('aria-label','Search invoices by number, customer, plate, vehicle or job');search.addEventListener('input',()=>{query=search.value;const cursor=search.selectionStart;renderInvoices();const replacement=$<HTMLInputElement>(list,'input[type="search"]');replacement?.focus();if(cursor!==null)replacement?.setSelectionRange(cursor,cursor);});list.append(label('Search Billing',search));
    const select=document.createElement('select');select.setAttribute('aria-label','Filter invoices');for(const value of ['All','Draft','Issued','Void']){const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option);}select.value=filter;select.addEventListener('change',()=>{filter=select.value;renderInvoices();});list.append(label('Invoice status',select));
    const needle=query.trim().toLocaleLowerCase();const matches=store.invoices.filter(invoice=>{const job=jobFor(invoice),customer=invoice.customerSnapshot??(job?getCustomer(store,job):null),vehicle=invoice.vehicleSnapshot??(job?getVehicle(store,job):null),text=[invoice.invoiceNumber,customer?.name,vehicle?.plate,vehicle?.make,vehicle?.model,invoice.jobNumberSnapshot??job?.number].filter(Boolean).join(' ').toLocaleLowerCase();return(filter==='All'||invoice.status===filter)&&(!needle||text.includes(needle));}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
    if(!matches.length){list.append(make('p','billing-empty','No invoices match this filter.'));return;}
    for(const invoice of matches){const job=jobFor(invoice),isSelected=invoice.invoiceId===selectedId,card=document.createElement('button');card.className=`billing-invoice-card${isSelected?' selected':''}`;card.type='button';card.setAttribute('aria-pressed',String(isSelected));card.append(make('strong',undefined,invoice.invoiceNumber??`Draft · ${invoice.invoiceId.slice(-8)}`),make('span',undefined,`${invoice.customerSnapshot?.name??(job?getCustomer(store,job)?.name:null)??'Customer'} · ${invoice.status}`));if(invoice.status!=='Draft'&&invoice.status!=='Void')card.append(make('span','billing-card-total',`${paymentStatus(store,invoice)} · ${money(outstanding(store,invoice))} due`));card.addEventListener('click',()=>{selectedId=invoice.invoiceId;alert('');render();});list.append(card);}
  }
  function renderDetail():void {
    detail.replaceChildren();const invoice=selected();if(!invoice){detail.append(make('div','billing-empty','Select an Invoice or create a Draft from an eligible job.'));return;}
    const job=jobFor(invoice);if(!job){detail.append(make('p','field-error','The Workshop Job linked to this Invoice is unavailable.'));return;}
    const heading=make('header','billing-detail-heading');heading.append(make('div',undefined,`${invoice.invoiceNumber??'Invoice Draft'} · ${invoice.status}`),make('p',undefined,`Job ${invoice.jobNumberSnapshot??job.number} · ${workflowStatus(job)} · Currency ${invoice.currency}`));detail.append(heading);
    const identity=invoice.customerSnapshot?`${invoice.customerSnapshot.name} · ${invoice.customerSnapshot.phone} · ${invoice.customerSnapshot.address}`:`${getCustomer(store,job)?.name??'Customer'} · ${getCustomer(store,job)?.phone??''} · ${getCustomer(store,job)?.address??''}`;const vehicle=invoice.vehicleSnapshot?`${invoice.vehicleSnapshot.plate} · ${invoice.vehicleSnapshot.make} ${invoice.vehicleSnapshot.model} · ${invoice.vehicleSnapshot.year??'Year not recorded'}`:`${getVehicle(store,job)?.plate??''} · ${getVehicle(store,job)?.make??''} ${getVehicle(store,job)?.model??''}`;
    const identityBox=make('div','billing-identity');identityBox.append(make('p',undefined,`Customer: ${identity}`),make('p',undefined,`Vehicle: ${vehicle}`));detail.append(identityBox);
    if(invoice.status==='Draft')renderDraft(invoice,job);else renderIssued(invoice,job);
  }
  function renderDraft(invoice:WorkshopInvoice,job:WorkshopJob):void {
    const note=make('p','billing-notice','Draft references may be refreshed. Enter and confirm every customer selling price before issue. Inspection estimate amounts and inventory unit costs are not final selling prices. Drafts are not customer invoices.');detail.append(note);
    if(invoice.cancelledBillingReason)detail.append(make('p','billing-exception-note',`Cancelled-job billing reason: ${invoice.cancelledBillingReason}`));
    if(invoice.replacesInvoiceId){const prior=store.invoices.find(item=>item.invoiceId===invoice.replacesInvoiceId);detail.append(make('p','billing-notice',`Replacement for ${prior?.invoiceNumber??prior?.invoiceId??'previous Void Invoice'}.`));}
    if(draftNeedsRefresh(store,job,invoice)){const warning=make('p','field-error','Operational data changed since this Draft was created. Refresh / reconcile it before Issue.');warning.setAttribute('role','alert');detail.append(warning);}
    const lines=make('section','billing-lines');lines.append(make('h2',undefined,'Review actual charges'));
    if(!invoice.lines.length)lines.append(make('p','billing-empty','No suggested work or parts. Add a transparent manual charge or explicitly confirm No Charge.'));
    invoice.lines.forEach(line=>lines.append(renderLine(line,invoice)));detail.append(lines);
    const manual=document.createElement('form');manual.className='billing-manual-form';manual.innerHTML='<h3>Add a manual charge</h3><div class="billing-form-grid"><label><span>Description / reason</span><input name="description" required maxlength="160" autocomplete="off"></label><label><span>Quantity</span><input name="quantity" type="number" min="0.001" step="0.001" value="1" required></label><label><span>Unit</span><input name="unit" value="job" required maxlength="32"></label><label><span>Selling price (Rp per unit)</span><input name="price" type="number" min="0" step="1" required></label></div><label class="billing-check"><input name="confirmed" type="checkbox" required><span>I confirm this manual selling price.</span></label><button type="submit">Add manual charge</button>';
    manual.addEventListener('submit',event=>{event.preventDefault();const form=new FormData(manual),price=Number(form.get('price'));if(!Number.isSafeInteger(price)||price<0){alert('Selling price must be a whole rupiah amount.');return;}saveMutation(()=>addManualLine(invoice,{description:String(form.get('description')||''),quantityMilli:parseQty(String(form.get('quantity')||'')),unit:String(form.get('unit')||''),unitSellingPrice:price,priceConfirmed:true}));});detail.append(manual);
    const totals=make('section','billing-totals');totals.append(make('h2',undefined,'Invoice calculation'));
    const discount=input('number',String(invoice.discount),{min:'0',step:'1'});discount.addEventListener('change',()=>saveMutation(()=>{invoice.discount=Number(discount.value);invoice.updatedAt=new Date().toISOString();recalculateLocal(invoice);},false));totals.append(label('Invoice discount (Rp)',discount));
    const tax=input('number',String(invoice.taxRateBps/100),{min:'0',max:'100',step:'0.01'});tax.addEventListener('change',()=>saveMutation(()=>{const n=Number(tax.value);if(!Number.isFinite(n)||n<0||n>100)throw new Error('Tax rate must be between 0% and 100%.');invoice.taxRateBps=Math.round(n*100);invoice.updatedAt=new Date().toISOString();recalculateLocal(invoice);},false));totals.append(label('Invoice tax rate (%)',tax));
    const noCharge=document.createElement('input');noCharge.type='checkbox';noCharge.checked=invoice.noCharge;noCharge.addEventListener('change',()=>saveMutation(()=>{invoice.noCharge=noCharge.checked;if(invoice.noCharge)invoice.discount=0;invoice.updatedAt=new Date().toISOString();recalculateLocal(invoice);},false));const check=make('label','billing-check');check.append(noCharge,make('span',undefined,'No Charge — explicitly issue this as a zero-value Invoice'));totals.append(check);
    for(const [caption,value]of [['Subtotal',invoice.subtotal],['Discount',invoice.discount],['Tax',invoice.taxAmount],['Total',invoice.grandTotal]] as const){const row=make('p','billing-total-row');row.dataset.billingTotal=caption;row.append(make('span',undefined,caption),make('strong',undefined,money(value)));if(caption==='Total')row.classList.add('grand');totals.append(row);}detail.append(totals);
    const actions=make('div','billing-actions');actions.append(button('Refresh / Reconcile Actual Data',()=>saveMutation(()=>{const result=refreshDraft(store,job,invoice);alert(result.removed?`Draft reconciled. ${result.removed} stale source line(s) were retained but excluded for review.`:'Draft reconciled with current operations.');}),'secondary'));
    actions.append(button('Issue Invoice',()=>{if(!window.confirm('Issue this Invoice? Its financial values and identity snapshot will become fixed.'))return;saveMutation(()=>issueInvoice(store,job,invoice));},'primary'));detail.append(actions);
  }
  function parseQty(value:string):number {const n=Number(value),scaled=Math.round(n*QUANTITY_SCALE);if(!Number.isFinite(n)||n<=0||!Number.isSafeInteger(scaled)||Math.abs(n*QUANTITY_SCALE-scaled)>1e-8)throw new Error('Quantity must be greater than zero with up to three decimal places.');return scaled;}
  function renderLine(line:WorkshopInvoiceLine,invoice:WorkshopInvoice):HTMLElement {
    const article=make('article','billing-line');article.dataset.lineId=line.lineId;const title=make('div','billing-line-title');title.append(make('strong',undefined,line.sourceType.replaceAll('_',' ')),make('span',undefined,line.sourceId?`Source · ${line.sourceId}`:'Manual entry'));article.append(title);
    const desc=input('text',line.description,{maxlength:'160'});desc.id=controlId();desc.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{description:desc.value,priceConfirmed:false}),false));article.append(label('Description',desc));
    const grid=make('div','billing-form-grid');const quantity=input('number',formatQuantity(line.quantityMilli),{min:'0.001',step:'0.001'});quantity.id=controlId();quantity.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{quantityMilli:parseQty(quantity.value)}),false));grid.append(label('Quantity',quantity));
    const unit=input('text',line.unit,{maxlength:'32'});unit.id=controlId();unit.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{unit:unit.value}),false));grid.append(label('Unit',unit));
    const price=input('number',line.unitSellingPrice===null?'':String(line.unitSellingPrice),{min:'0',step:'1',placeholder:'Enter customer selling price'});price.id=controlId();price.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{unitSellingPrice:price.value===''?null:Number(price.value),priceConfirmed:false}),false));grid.append(label('Selling price per unit (Rp)',price));article.append(grid);
    const include=document.createElement('input');include.type='checkbox';include.checked=line.included;include.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{included:include.checked}),false));const includeLabel=make('label','billing-check');includeLabel.append(include,make('span',undefined,line.sourceType==='NON_INVENTORY_MATERIAL'?'Confirm this material was actually used and is billable':'Include this reviewed line in the Invoice'));article.append(includeLabel);
    const confirmed=document.createElement('input');confirmed.type='checkbox';confirmed.checked=line.priceConfirmed;confirmed.addEventListener('change',()=>saveMutation(()=>updateDraftLine(invoice,line.lineId,{priceConfirmed:confirmed.checked}),false));const confirmLabel=make('label','billing-check');confirmLabel.append(confirmed,make('span',undefined,'I confirm this customer selling price'));article.append(confirmLabel);
    const subtotal=make('p','billing-line-total',`Line total: ${money(line.lineTotal)}`);article.append(subtotal);if(line.sourceType==='MANUAL')article.append(button('Remove manual line',()=>saveMutation(()=>{invoice.lines=invoice.lines.filter(x=>x.lineId!==line.lineId);invoice.updatedAt=new Date().toISOString();recalculateLocal(invoice); }),'danger'));
    return article;
  }
  function recalculateLocal(invoice:WorkshopInvoice):void {const result=calculateInvoice(invoice);if(!result)throw new Error('Invoice calculation is invalid. Check quantity, price, discount, and tax.');Object.assign(invoice,result);}
  function renderIssued(invoice:WorkshopInvoice,job:WorkshopJob):void {
    const summary=billingSummary(store,invoice);const state=make('p','billing-financial-status',`Payment status: ${summary.status} · Paid ${money(summary.paid)} · Outstanding ${money(summary.outstanding)}`);detail.append(state);
    if(invoice.status==='Void'){detail.append(make('p','billing-exception-note',`Void ${invoice.voidAt?dateText(invoice.voidAt):''}: ${invoice.voidReason??''}`));if(invoice.replacedByInvoiceId){const replacement=store.invoices.find(i=>i.invoiceId===invoice.replacedByInvoiceId);if(replacement)detail.append(button(`Open replacement ${replacement.invoiceNumber??'Draft'}`,()=>{selectedId=replacement.invoiceId;render();}));}else if(eligibleForDraft(job)||workflowStatus(job)==='Cancelled')detail.append(button('Create Replacement Draft',()=>saveMutation(()=>{const replacement=createReplacementDraft(store,job,invoice);selectedId=replacement.invoiceId;}),'primary'));return;}
    const discrepancies=invoiceDiscrepancies(store,job,invoice);if(discrepancies.length){const warning=make('section','billing-discrepancy');warning.setAttribute('role','alert');warning.append(make('h2',undefined,'Operational data changed after Invoice Issue'));for(const text of discrepancies)warning.append(make('p',undefined,text));warning.append(make('p',undefined,'The Issued Invoice remains unchanged. Reverse its Payments, then Void it and create a replacement Invoice to correct billed amounts.'));detail.append(warning);}
    const lineSection=make('section','billing-lines');lineSection.append(make('h2',undefined,'Issued Invoice lines'));for(const line of invoice.lines){const row=make('p','billing-issued-line',`${line.description} · ${formatQuantity(line.quantityMilli)} ${line.unit} × ${money(line.unitSellingPrice??0)} = ${money(line.lineTotal)}`);lineSection.append(row);}detail.append(lineSection);
    const totals=make('section','billing-totals');for(const [caption,value]of [['Subtotal',invoice.subtotal],['Discount',invoice.discount],['Tax',invoice.taxAmount],['Total',invoice.grandTotal]] as const){const row=make('p','billing-total-row');row.append(make('span',undefined,caption),make('strong',undefined,money(value)));if(caption==='Total')row.classList.add('grand');totals.append(row);}detail.append(totals);
    if(invoice.grandTotal>0&&summary.outstanding>0){const form=document.createElement('form');form.className='billing-payment-form';form.innerHTML='<h2>Record Payment</h2><div class="billing-form-grid"><label><span>Amount (whole Rp)</span><input name="amount" type="number" min="1" step="1" required></label><label><span>Method</span><select name="method"><option>Cash</option><option>Bank Transfer</option><option>Card</option><option>Digital Payment</option><option>Other</option></select></label><label><span>Payment date and time</span><input name="paidAt" type="datetime-local" required></label><label><span>Reference (optional)</span><input name="reference" maxlength="100"></label><label class="billing-span"><span>Note (optional)</span><input name="note" maxlength="200"></label></div><button type="submit">Save Payment</button>';
      const paidAt=$<HTMLInputElement>(form,'[name="paidAt"]')!;paidAt.value=new Date().toISOString().slice(0,16);form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form);saveMutation(()=>recordPayment(store,invoice,{amount:Number(data.get('amount')),method:String(data.get('method')) as WorkshopPaymentMethod,paidAt:new Date(String(data.get('paidAt'))).toISOString(),reference:String(data.get('reference')||''),note:String(data.get('note')||'') }));});detail.append(form);}
    const paymentSection=make('section','billing-payments');paymentSection.append(make('h2',undefined,'Payment history'));const payments=allPaymentsForInvoice(store,invoice.invoiceId);if(!payments.length)paymentSection.append(make('p','billing-empty','No payments recorded.'));for(const payment of payments){const row=make('article','billing-payment');const reversed=payment.kind==='Payment'&&store.payments.some(p=>p.reversalOfPaymentId===payment.paymentId);row.append(make('strong',undefined,`${payment.kind}${reversed?' · Reversed':''} · ${money(payment.amount)}`),make('span',undefined,`${payment.method??'Reversal'} · ${dateText(payment.paidAt.slice(0,10))} · Receipt ${payment.receiptNumber??'—'}`));if(payment.reference)row.append(make('span',undefined,`Reference: ${payment.reference}`));if(payment.kind==='Reversal')row.append(make('span',undefined,`Reason: ${payment.reversalReason??''}`));row.append(button('Print Receipt',()=>printReceipt(invoice,payment,store),'secondary'));if(payment.kind==='Payment'&&!reversed)row.append(button('Reverse Payment',()=>{const reason=window.prompt('Reason for reversing this Payment?')??'';if(!reason.trim())return;saveMutation(()=>reversePayment(store,payment,reason));},'danger'));paymentSection.append(row);}detail.append(paymentSection);
    if(netPaid(store,invoice.invoiceId)===0){detail.append(button('Void Invoice',()=>{const reason=window.prompt('Reason for voiding this Invoice?')??'';if(!reason.trim())return;saveMutation(()=>voidInvoice(invoice,store,reason));},'danger'));}
    if(invoice.replacesInvoiceId){const prior=store.invoices.find(i=>i.invoiceId===invoice.replacesInvoiceId);detail.append(make('p','billing-notice',`Replacement for ${prior?.invoiceNumber??prior?.invoiceId??'previous Void Invoice'}.`));}
    const print=button('Print / Save Invoice as PDF',()=>printInvoice(invoice,store),'secondary');detail.append(print);
  }
  function printInvoice(invoice:WorkshopInvoice,source:WorkshopStore):void {
    const sheet=$<HTMLElement>(root,'#print-sheet')!,title=$<HTMLElement>(root,'#print-title')!,content=$<HTMLElement>(root,'#print-content')!;title.textContent=`Invoice ${invoice.invoiceNumber??'Draft'}`;content.replaceChildren();
    const customer=invoice.customerSnapshot,vehicle=invoice.vehicleSnapshot;for(const text of [`Status: ${invoice.status}`,`Issued: ${invoice.issuedAt?dateText(invoice.issuedAt.slice(0,10)):'Not issued'}`,`Customer: ${customer?.name??''} · ${customer?.phone??''} · ${customer?.address??''}`,`Vehicle: ${vehicle?.plate??''} · ${vehicle?.type??''} ${vehicle?.make??''} ${vehicle?.model??''} ${vehicle?.year??''}`,`Workshop Job: ${invoice.jobNumberSnapshot??jobFor(invoice)?.number??''}`])content.append(make('p','print-line',text));
    const table=document.createElement('table');table.className='print-table';const head=document.createElement('thead'),headRow=document.createElement('tr');for(const text of ['Description','Qty','Unit','Unit price','Amount']){const th=document.createElement('th');th.textContent=text;headRow.append(th);}head.append(headRow);table.append(head);const body=document.createElement('tbody');for(const line of invoice.lines.filter(x=>x.included)){const row=document.createElement('tr');for(const text of [line.description,formatQuantity(line.quantityMilli),line.unit,money(line.unitSellingPrice??0),money(line.lineTotal)]){const td=document.createElement('td');td.textContent=text;row.append(td);}body.append(row);}table.append(body);content.append(table);for(const [label,value]of [['Subtotal',invoice.subtotal],['Discount',invoice.discount],['Tax',invoice.taxAmount],['Total',invoice.grandTotal],['Payment status',invoice.status==='Issued'?paymentStatus(source,invoice):invoice.status],['Outstanding',invoice.status==='Issued'?outstanding(source,invoice):0]] as const)content.append(make('p','print-line',`${label}: ${typeof value==='number'?money(value):value}`));printSheet(sheet);
  }
  function printReceipt(invoice:WorkshopInvoice,payment:WorkshopPayment,source:WorkshopStore):void {
    const sheet=$<HTMLElement>(root,'#print-sheet')!,title=$<HTMLElement>(root,'#print-title')!,content=$<HTMLElement>(root,'#print-content')!;title.textContent=`Payment Receipt ${payment.receiptNumber??''}`;content.replaceChildren();const customer=invoice.customerSnapshot,vehicle=invoice.vehicleSnapshot,reversed=payment.kind==='Payment'&&source.payments.some(p=>p.reversalOfPaymentId===payment.paymentId);if(reversed||payment.kind==='Reversal')content.append(make('p','print-warning','REVERSED — this document is retained for history and is not a valid current receipt.'));
    for(const text of [`Receipt: ${payment.receiptNumber??'Reversal record'}`,`Invoice: ${invoice.invoiceNumber??'—'}`,`Workshop Job: ${invoice.jobNumberSnapshot??'—'}`,`Customer: ${customer?.name??''}`,`Vehicle: ${vehicle?.plate??''} · ${vehicle?.make??''} ${vehicle?.model??''}`,`Amount: ${money(payment.amount)}`,`Method: ${payment.method??'Reversal'}`,`Reference: ${payment.reference??'—'}`,`Paid at: ${payment.paidAt}`,`Outstanding after this Payment: ${money(paymentBalanceAfter(source,payment))}`,`Note: ${payment.note??payment.reversalReason??'—'}`])content.append(make('p','print-line',text));printSheet(sheet);
  }
  function printSheet(sheet:HTMLElement):void {sheet.hidden=false;sheet.classList.add('is-preview');window.print();window.addEventListener('afterprint',()=>{sheet.classList.remove('is-preview');sheet.hidden=true;},{once:true});}
  render();
}
