/* eslint-disable @typescript-eslint/no-explicit-any -- heterogeneous form rows are serialized from data-field keyed controls. */
import type { Inspection, QualityCheck, WorkOrder, WorkRow, WorkshopJob } from '../../lib/workshop/model.ts';
import { emptyInspection, calculateEstimate, validateIntake, validateInspection, workDuration, qcWarning, validateOdometers } from '../../lib/workshop/rules.ts';
import { loadStore, saveStore, createJob, updateJob, getJob, getCustomer, getVehicle, makeId } from '../../lib/workshop/store.ts';

const $ = <T extends HTMLElement = HTMLElement>(root: ParentNode, selector: string) => root.querySelector<T>(selector);
const all = <T extends HTMLElement>(root: ParentNode, selector: string) => [...root.querySelectorAll<T>(selector)];
const el = <K extends keyof HTMLElementTagNameMap>(tag: K, cls?: string, txt?: string) => { const node = document.createElement(tag); if (cls) node.className = cls; if (txt !== undefined) node.textContent = txt; return node; };
const value = (root: ParentNode, name: string) => (root.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[name="${name}"]`)?.value ?? '').trim();
const num = (root: ParentNode, name: string): number | null => value(root, name) === '' ? null : Number(value(root, name));
const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const stamp = () => `${Date.now().toString(36).slice(-5).toUpperCase()}`;
function set(root: ParentNode, name: string, v: unknown) { const node = root.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[name="${name}"]`); if (node) node.value = v == null ? '' : String(v); }
function setError(root: ParentNode, selector: string, message: string) { const node = root.querySelector<HTMLElement>(selector); if (node) { node.textContent = message; node.hidden = !message; } }
function money(n: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n); }
function rows<T extends {id:string}>(host: HTMLElement, list: T[], render: (row:T)=>HTMLElement) { host.replaceChildren(...list.map(render)); }
function textRow(parent: HTMLElement, label: string, content: unknown) { const p = el('p'); const b = el('strong', undefined, `${label}: `); p.append(b, document.createTextNode(content == null || content === '' ? '—' : String(content))); parent.append(p); }
function status(root: HTMLElement, message: string) { const n = $(root, '#workshop-status'); if (n) { n.textContent = message; n.hidden = !message; } }
function save(root: HTMLElement, store: ReturnType<typeof loadStore>['store']) { try { const result = saveStore(store, window.localStorage); if (!result.ok) status(root, result.message); return result.ok; } catch { status(root,'Browser storage is unavailable. Your latest change was not saved.'); return false; } }
function context(root: HTMLElement, job: WorkshopJob | null, store: ReturnType<typeof loadStore>['store']) {
  const node = $(root, '#workshop-job-context'); if (!node) return; node.replaceChildren(); node.hidden = !job;
  if (job) { const c = getCustomer(store, job), v = getVehicle(store, job); node.append(el('strong', undefined, `${job.number} · ${job.status.replace('-', ' ')}`), el('span', undefined, `${c?.name ?? 'Customer'} · ${v?.plate ?? 'Vehicle'} · ${[v?.make,v?.model].filter(Boolean).join(' ')}`)); }
  const picker = $(root, '#workshop-job-picker'); if (!picker) return;
  if (!job && store.jobs.length) { picker.hidden = false; picker.replaceChildren(el('strong', undefined, 'Existing local jobs')); for (const j of store.jobs) { const v=getVehicle(store,j), c=getCustomer(store,j); const a=el('a',undefined,`${j.number} · ${v?.plate ?? ''} · ${c?.name ?? ''}`) as HTMLAnchorElement; a.href=`?job=${encodeURIComponent(j.id)}`; picker.append(a); } } else picker.hidden = true;
}
function jobFromUrl(store: ReturnType<typeof loadStore>['store']) { return getJob(store, new URL(location.href).searchParams.get('job')); }
function linkFor(id: string, path: string) { return `${path}?job=${encodeURIComponent(id)}`; }
function labelInput(parent: HTMLElement, label: string, name: string, type='text', val='') { const l=el('label'); l.append(el('span',undefined,label)); const i=document.createElement('input'); i.name=name; i.type=type; i.value=val; i.dataset.field=name; l.append(i); parent.append(l); return i; }
function selectField(parent: HTMLElement, label: string, name: string, choices: string[], val: string) { const l=el('label'); l.append(el('span',undefined,label)); const s=el('select'); s.name=name; s.dataset.field=name; for (const x of choices) { const o=el('option',undefined,x); o.value=x; s.append(o); } s.value=val; l.append(s); parent.append(l); return s; }

function mountIntake(root: HTMLElement, store: ReturnType<typeof loadStore>['store'], job: WorkshopJob | null) {
 const form=$<HTMLFormElement>(root,'#intake-form'); if(!form)return; const c=job?getCustomer(store,job):null,v=job?getVehicle(store,job):null,i=job?.intake;
 if(job){ for(const [n,x] of Object.entries({customerName:c?.name,phone:c?.phone,address:c?.address,vehicleType:v?.type,plate:v?.plate,make:v?.make,model:v?.model,year:v?.year,color:v?.color,odometer:v?.odometer,complaint:i?.complaint,accessories:i?.accessories.join('\n'),conditionNotes:i?.conditionNotes,date:i?.date,arrivalTime:i?.arrivalTime})) set(form,n,x); }
 else {set(form,'date',localDate());set(form,'arrivalTime',`${String(new Date().getHours()).padStart(2,'0')}:${String(new Date().getMinutes()).padStart(2,'0')}`);}
 form.addEventListener('submit',e=>{e.preventDefault(); const errors=validateIntake({name:value(form,'customerName'),plate:value(form,'plate'),year:value(form,'year'),odometer:value(form,'odometer')}); if(errors.length){setError(root,'#intake-error',errors.join(' '));return;}
 const intake={number:i?.number??`WI-${localDate().replaceAll('-','')}-${stamp()}`, complaint:value(form,'complaint'), accessories:value(form,'accessories').split(/[\n,]/).map(x=>x.trim()).filter(Boolean),conditionNotes:value(form,'conditionNotes'),date:value(form,'date')||localDate(),arrivalTime:value(form,'arrivalTime')};
 if(job){ const customer=getCustomer(store,job), vehicle=getVehicle(store,job); if(customer)Object.assign(customer,{name:value(form,'customerName'),phone:value(form,'phone'),address:value(form,'address')}); if(vehicle)Object.assign(vehicle,{type:value(form,'vehicleType'),plate:value(form,'plate'),make:value(form,'make'),model:value(form,'model'),year:num(form,'year'),color:value(form,'color'),odometer:num(form,'odometer')}); updateJob(store,job.id,{intake}); }
 else createJob(store,{customer:{name:value(form,'customerName'),phone:value(form,'phone'),address:value(form,'address')},vehicle:{type:value(form,'vehicleType')==='Car'?'Car':'Motorcycle',plate:value(form,'plate'),make:value(form,'make'),model:value(form,'model'),year:num(form,'year'),color:value(form,'color'),odometer:num(form,'odometer')},intake});
 const saved=job??store.jobs.at(-1)!; if(save(root,store)){ const next=$<HTMLElement>(root,'#next-inspection'); if(next)next.hidden=false; const a=$<HTMLAnchorElement>(root,'#continue-inspection'); if(a)a.href=linkFor(saved.id,'/tools/workshop/inspection-estimate/');setError(root,'#intake-error','');status(root,'Intake saved in this browser.'); }
 });
}

function inputRow(group: string, fields: [string,string,string?][], values: Record<string,string>={}, select?: [string,string[]][]) { const card=el('div','workshop-row'); card.dataset.row='true'; card.dataset.rowGroup=group; const grid=el('div','form-grid'); for(const [name,label,type] of fields)labelInput(grid,label, name,type??'text',values[name]??''); for(const [name,choices] of select??[])selectField(grid,name,name,choices,values[name]??choices[0]); card.append(grid); return card; }
function mountInspection(root: HTMLElement, store: ReturnType<typeof loadStore>['store'], job: WorkshopJob | null) {
 const form=$<HTMLFormElement>(root,'#inspection-form'); if(!form)return; if(!job){form.hidden=true;return;} form.hidden=false;
 const v=getVehicle(store,job), data:Inspection=job.inspection??emptyInspection(v?.type==='Car'?'Car':'Motorcycle');
 const ctx=$<HTMLElement>(root,'#inspection-context'); if(ctx){ctx.replaceChildren();textRow(ctx,'Intake complaint',job.intake.complaint);}
 set(form,'findings',data.findings); for(const n of ['consumables','additionalCost','discount','taxRate'] as const)set(form,n,data[n]);
 const checkHost=$<HTMLElement>(root,'#inspection-checklist')!; checkHost.replaceChildren(...data.checklist.map(g=>{const sec=el('fieldset');sec.append(el('legend',undefined,g.category));for(const item of g.items){const line=el('div','check-row');line.append(el('span',undefined,item.name));selectField(line,'Status',`check:${g.category}:${item.name}`,['Good','Monitor','Service','Replace','Not checked','Not applicable'],item.status);labelInput(line,'Note',`note:${g.category}:${item.name}`,'text',item.note);sec.append(line);}return sec;}));
 const recHost=$<HTMLElement>(root,'#recommended-rows')!,partHost=$<HTMLElement>(root,'#estimate-parts')!,laborHost=$<HTMLElement>(root,'#estimate-labor')!;
 const draw=()=>{rows(recHost,data.recommendedJobs,r=>{const row=inputRow('recommended',[['name','Recommended work'],['detail','Details']],{name:r.name,detail:r.detail},[['priority',['Urgent','Recommended','Can wait']]]);const s=row.querySelector('select')!;s.value=r.priority;const chk=el('label');const input=el('input');input.type='checkbox';input.checked=r.approved;input.dataset.field='approved';chk.append(input,document.createTextNode(' Customer approved'));row.append(chk);return row;}); rows(partHost,data.parts,r=>inputRow('estimate-part',[['name','Part'],['partNumber','Part number'],['quantity','Quantity','number'],['unit','Unit'],['unitPrice','Unit price','number']],r as any)); rows(laborHost,data.labor,r=>{const row=inputRow('labor',[['name','Labor'],['hours','Hours','number'],['rate','Hourly rate','number'],['fixed','Fixed cost','number']],r as any,[['mode',['fixed','hourly']]]);row.querySelector('select')!.value=r.mode;return row;}); };
 draw();
 const sync=()=>{const read=(host:HTMLElement)=>all<HTMLElement>(host,'[data-row]').map(row=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(row,'[data-field]').map(x=>[x.dataset.field!,x instanceof HTMLInputElement&&x.type==='checkbox'?x.checked:x.value]))); data.recommendedJobs=read(recHost).map((r:any)=>({id:makeId('recommendation'),name:r.name,detail:r.detail,priority:r.priority,approved:!!r.approved}));data.parts=read(partHost).map((r:any)=>({id:makeId('part'),name:r.name,partNumber:r.partNumber,quantity:Number(r.quantity),unit:r.unit,unitPrice:Number(r.unitPrice)}));data.labor=read(laborHost).map((r:any)=>({id:makeId('labor'),name:r.name,mode:r.mode,hours:Number(r.hours),rate:Number(r.rate),fixed:Number(r.fixed)}));for(const g of data.checklist)for(const x of g.items){x.status=(form.querySelector(`[name="check:${CSS.escape(g.category)}:${CSS.escape(x.name)}"]`) as HTMLSelectElement)?.value as any??x.status;x.note=(form.querySelector(`[name="note:${CSS.escape(g.category)}:${CSS.escape(x.name)}"]`) as HTMLInputElement)?.value??x.note;}data.findings=value(form,'findings');for(const k of ['consumables','additionalCost','discount','taxRate'] as const)data[k]=Number(value(form,k)||0); };
 const refresh=()=>{sync();const s=$<HTMLElement>(root,'#estimate-summary')!;const total=calculateEstimate(data);s.textContent=`Parts ${money(total.parts)} · Labor ${money(total.labor)} · Other ${money(total.additional)} · Discount ${money(total.discount)} · Tax ${money(total.tax)} · Total ${money(total.total)}`;}; form.addEventListener('input',refresh);form.addEventListener('change',refresh);
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{refresh();const key=b.dataset.addRow;if(key==='recommended')data.recommendedJobs.push({id:makeId('recommendation'),name:'',detail:'',priority:'Recommended',approved:false});if(key==='estimate-part')data.parts.push({id:makeId('part'),name:'',partNumber:'',quantity:1,unit:'each',unitPrice:0});if(key==='labor')data.labor.push({id:makeId('labor'),name:'',mode:'fixed',hours:0,rate:0,fixed:0});draw();refresh();}));refresh();
 form.addEventListener('submit',e=>{e.preventDefault();refresh();const errors=validateInspection(data);if(errors.length){setError(root,'#inspection-error',errors.join(' '));return;}updateJob(store,job.id,{inspection:data,status:'inspection'});if(save(root,store)){const box=$<HTMLElement>(root,'#next-work-order')!,a=$<HTMLAnchorElement>(root,'#continue-work-order')!;box.hidden=false;a.href=linkFor(job.id,'/tools/workshop/work-order/');setError(root,'#inspection-error','');status(root,'Inspection and estimate saved.');}});
}

function mountWorkOrder(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){const form=$<HTMLFormElement>(root,'#work-order-form');if(!form)return;if(!job){form.hidden=true;return;}form.hidden=false;const ctx=$<HTMLElement>(root,'#work-order-context')!;ctx.replaceChildren();textRow(ctx,'Customer complaint',job.intake.complaint);textRow(ctx,'Inspection findings',job.inspection?.findings);const data:WorkOrder=job.workOrder??{number:`WO-${job.number}`,date:localDate(),status:'Not started',mechanic:'',approvedWork:(job.inspection?.recommendedJobs.filter(x=>x.approved)??[]).map(x=>({id:makeId('work'),name:x.name,detail:x.detail,status:'Not started',mechanic:''})),actualWork:[],parts:[],changes:[],startTime:'',endTime:'',mechanicNotes:'',result:'',recommendations:'',signoff:''};
 for(const k of ['number','date','status','mechanic','startTime','endTime','mechanicNotes','result','recommendations','signoff'] as const)set(form,k,data[k]); const specs:[string,keyof WorkOrder,string, [string,string,string?][],any?][]=[['approved-work','approvedWork','approved-work',[['name','Work'],['detail','Details'],['mechanic','Mechanic']], [['status',['Not started','In progress','Complete','Paused','Cancelled']]]],['actual-work','actualWork','actual-work',[['name','Work performed'],['detail','Details'],['mechanic','Mechanic']], [['status',['Not started','In progress','Complete','Paused','Cancelled']]]],['work-parts','parts','work-part',[['name','Part / material'],['partNumber','Part number'],['quantity','Quantity','number'],['unit','Unit'],['notes','Notes']]],['work-changes','changes','change',[['work','Proposed change'],['reason','Reason'],['notes','Notes']], [['approval',['Awaiting approval','Approved','Deferred','Declined']]]]];
 const draw=()=>{for(const [host,key,group,fs,select] of specs){const target=$<HTMLElement>(root,`#${host}`)!;rows(target,(data[key] as any[]),r=>{const row=inputRow(group,fs,r as any,select);if(select?.length)row.querySelector('select')!.value=r.status??r.approval;return row;});}};draw();
  const sync=()=>{for(const [host,key] of specs){const target=$<HTMLElement>(root,`#${host}`)!;const list=all<HTMLElement>(target,'[data-row]').map(row=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(row,'[data-field]').map(x=>[x.dataset.field!,x.value])));if(key==='approvedWork'||key==='actualWork') (data[key] as WorkRow[]) = list.map((x:any)=>({id:makeId('work'),name:x.name,detail:x.detail,mechanic:x.mechanic,status:x.status}));else if(key==='parts')data.parts=list.map((x:any)=>({...x,id:makeId('part'),quantity:Number(x.quantity)}));else data.changes=list.map((x:any)=>({...x,id:makeId('change')}));}};
 const time=()=>{const node=$<HTMLElement>(root,'#work-duration')!;node.textContent=workDuration(value(form,'startTime'),value(form,'endTime'))?`Recorded duration: ${workDuration(value(form,'startTime'),value(form,'endTime'))}`:'';};form.addEventListener('input',time);time();
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{sync();const k=b.dataset.addRow;if(k==='approved-work'||k==='actual-work')data[k==='approved-work'?'approvedWork':'actualWork'].push({id:makeId('work'),name:'',detail:'',status:'Not started',mechanic:''});if(k==='work-part')data.parts.push({id:makeId('part'),name:'',partNumber:'',quantity:1,unit:'each',notes:''});if(k==='change')data.changes.push({id:makeId('change'),work:'',reason:'',approval:'Awaiting approval',notes:''});draw();}));
 form.addEventListener('submit',e=>{e.preventDefault();sync();data.number=value(form,'number');data.date=value(form,'date');data.status=value(form,'status') as any;data.mechanic=value(form,'mechanic');data.startTime=value(form,'startTime');data.endTime=value(form,'endTime');data.mechanicNotes=value(form,'mechanicNotes');data.result=value(form,'result');data.recommendations=value(form,'recommendations');data.signoff=value(form,'signoff');if(!data.number.trim()||data.parts.some(p=>!Number.isFinite(p.quantity)||p.quantity<=0)){setError(root,'#work-order-error','Enter a work order number and valid positive quantities for all parts.');return;}updateJob(store,job.id,{workOrder:data,status:'work-order'});if(save(root,store)){const box=$<HTMLElement>(root,'#next-qc')!;box.hidden=false;$<HTMLAnchorElement>(root,'#continue-qc')!.href=linkFor(job.id,'/tools/workshop/qc-handover/');setError(root,'#work-order-error','');status(root,'Work order saved.');}});
}

function mountQC(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){const form=$<HTMLFormElement>(root,'#qc-form');if(!form)return;if(!job){form.hidden=true;return;}form.hidden=false;if(job.status==='completed')$<HTMLElement>(root,'#job-completed')!.hidden=false;const ctx=$<HTMLElement>(root,'#qc-context')!;ctx.replaceChildren();textRow(ctx,'Work order',job.workOrder?.number);textRow(ctx,'Repair result',job.workOrder?.result);textRow(ctx,'Inspection findings',job.inspection?.findings);
 const data:QualityCheck=job.qc??{number:`QC-${job.number}`,date:localDate(),inspector:'',mechanic:job.workOrder?.mechanic??'',finalStatus:'In progress',checks:[{name:'Repair matches approved work',result:'Not checked',note:''},{name:'Parts and fasteners secured',result:'Not checked',note:''},{name:'Brakes and safety systems',result:'Not checked',note:''},{name:'Tools and protective covers removed',result:'Not checked',note:''},{name:'Vehicle clean and ready',result:'Not checked',note:''}],unresolvedIssues:[],returnedItems:[],roadTest:'Not required',roadTester:'',odometerBefore:null,odometerAfter:null,roadTestNotes:'',readinessNotes:'',recommendations:'',customerNotes:'',handoverRecipient:'',handoverStaff:'',handoverDate:'',handoverTime:''};
 for(const k of ['number','date','finalStatus','inspector','mechanic','roadTest','roadTester','odometerBefore','odometerAfter','roadTestNotes','readinessNotes','recommendations','customerNotes','handoverRecipient','handoverStaff','handoverDate','handoverTime'] as const)set(form,k,data[k]);set(form,'returnedItems',data.returnedItems.join('\n'));
 const checkHost=$<HTMLElement>(root,'#qc-checklist')!;const extra=$<HTMLElement>(root,'#qc-extra-rows')!,issues=$<HTMLElement>(root,'#qc-issues')!;
 const draw=()=>{checkHost.replaceChildren(...data.checks.filter(c=>!(c as any).extra).map((c,ix)=>{const row=el('div','check-row');row.append(el('span',undefined,c.name));selectField(row,'Result',`qccheck:${ix}`,['Pass','Needs attention','Not applicable','Not checked'],c.result);labelInput(row,'Note',`qcnote:${ix}`,'text',c.note);return row;}));rows(extra,data.checks.filter(c=>(c as any).extra) as any[],c=>{const row=inputRow('qc-check',[['name','Check'],['note','Note']],c as any,[['result',['Pass','Needs attention','Not applicable','Not checked']]]);row.querySelector('select')!.value=c.result;return row;});rows(issues,data.unresolvedIssues,x=>{const row=inputRow('qc-issue',[['issue','Issue'],['recommendation','Recommendation']],x as any,[['status',['Customer deferred','Needs follow-up']]]);row.querySelector('select')!.value=x.status;return row;});};draw();
 const sync=()=>{data.checks=data.checks.map((c,ix)=>{const s=form.querySelector(`[name="qccheck:${ix}"]`) as HTMLSelectElement;const n=form.querySelector(`[name="qcnote:${ix}"]`) as HTMLInputElement;return s?{...c,result:s.value as any,note:n?.value??''}:c;});const read=(host:HTMLElement)=>all<HTMLElement>(host,'[data-row]').map(r=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement>(r,'[data-field]').map(x=>[x.dataset.field!,x.value])));data.checks=data.checks.filter(c=>!(c as any).extra).concat(read(extra).map((x:any)=>({name:x.name,result:x.result,note:x.note,extra:true} as any)));data.unresolvedIssues=read(issues).map((x:any)=>({id:makeId('issue'),issue:x.issue,status:x.status,recommendation:x.recommendation}));for(const k of ['number','date','finalStatus','inspector','mechanic','roadTest','roadTester','roadTestNotes','readinessNotes','recommendations','customerNotes','handoverRecipient','handoverStaff','handoverDate','handoverTime'] as const)(data as any)[k]=value(form,k);data.odometerBefore=num(form,'odometerBefore');data.odometerAfter=num(form,'odometerAfter');data.returnedItems=value(form,'returnedItems').split(/[\n,]/).map(x=>x.trim()).filter(Boolean);};
 const warn=()=>{sync();const m=qcWarning(data.checks,data.finalStatus==='Ready for handover')|| (data.finalStatus==='Ready for handover'&&data.unresolvedIssues.length?'Resolve or document all unresolved issues before handover.':'');const n=$<HTMLElement>(root,'#qc-warning')!;n.textContent=m;n.hidden=!m;};form.addEventListener('input',warn);form.addEventListener('change',warn);
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{sync();if(b.dataset.addRow==='qc-check')data.checks.push({name:'',result:'Not checked',note:'',extra:true} as any);if(b.dataset.addRow==='qc-issue')data.unresolvedIssues.push({id:makeId('issue'),issue:'',status:'Needs follow-up',recommendation:''});draw();}));
 const persist=(complete:boolean)=>{sync();const errors=validateOdometers(data.odometerBefore,data.odometerAfter);if(!data.number.trim())errors.push('QC number is required.');const pending=data.checks.some(c=>c.result==='Needs attention'||c.result==='Not checked');if(complete&&(pending||data.unresolvedIssues.length||data.finalStatus!=='Ready for handover'))errors.push('Complete all QC checks, resolve outstanding issues, and select Ready for handover before completing this job.');if(errors.length){setError(root,'#qc-error',errors.join(' '));return false;}updateJob(store,job.id,{qc:data,status:complete?'completed':'qc'});if(!save(root,store))return false;setError(root,'#qc-error','');status(root,complete?'Job completed and saved in this browser.':'QC and handover saved.');if(complete)$<HTMLElement>(root,'#job-completed')!.hidden=false;return true;};form.addEventListener('submit',e=>{e.preventDefault();persist(false);});$<HTMLButtonElement>(root,'#complete-job')?.addEventListener('click',()=>persist(true));
}

function printJob(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){if(!job){status(root,'Select a saved job before printing.');return;}const sheet=$<HTMLElement>(root,'#print-sheet')!;const title=$<HTMLElement>(root,'#print-title')!;const content=$<HTMLElement>(root,'#print-content')!;const c=getCustomer(store,job),v=getVehicle(store,job),step=root.dataset.workshopStep;title.textContent=`${job.number} · ${step?.replace('-',' ')??'workshop'}`;content.replaceChildren();const details:[string,string|undefined][]=[['Customer',c?.name],['Phone',c?.phone],['Address',c?.address],['Vehicle',`${v?.plate??''} ${v?.make??''} ${v?.model??''} ${v?.year??''}`],['Odometer',v?.odometer==null?undefined:`${v.odometer.toLocaleString()} km`],['Intake complaint',job.intake.complaint],['Items received',job.intake.accessories.join(', ')],['Condition notes',job.intake.conditionNotes]];for(const [k,x] of details)if(x)textRow(content,k,x);
 const section=(name:string)=>{const h=el('h3',undefined,name);content.append(h);return el('div');};const addLines=(name:string,values:string[])=>{if(!values.length)return;const wrap=section(name);for(const item of values){const p=el('p','print-line',item);wrap.append(p);}content.append(wrap);};
 if(step==='inspection'&&job.inspection){const d=job.inspection;const total=calculateEstimate(d);textRow(content,'Inspection findings',d.findings);addLines('Inspection checklist',d.checklist.flatMap(g=>g.items.map(x=>`${g.category} · ${x.name}: ${x.status}${x.note?` — ${x.note}`:''}`)));addLines('Recommended work',d.recommendedJobs.map(x=>`${x.name} · ${x.priority} · ${x.approved?'Approved':'Not approved'}${x.detail?` — ${x.detail}`:''}`));addLines('Parts estimate',d.parts.map(x=>`${x.name} · ${x.quantity} ${x.unit} × ${money(x.unitPrice)} = ${money(x.quantity*x.unitPrice)}`));addLines('Labor estimate',d.labor.map(x=>`${x.name} · ${money(x.mode==='hourly'?x.hours*x.rate:x.fixed)}`));textRow(content,'Estimate total',money(total.total));}
 if(step==='work-order'&&job.workOrder){const d=job.workOrder;textRow(content,'Work order number',d.number);textRow(content,'Status',d.status);addLines('Approved work',d.approvedWork.map(x=>`${x.name}${x.detail?` — ${x.detail}`:''} · ${x.status}`));addLines('Work performed',d.actualWork.map(x=>`${x.name}${x.detail?` — ${x.detail}`:''} · ${x.status}${x.mechanic?` · ${x.mechanic}`:''}`));addLines('Parts and materials',d.parts.map(x=>`${x.name} · Qty ${x.quantity}${x.partNumber?` · ${x.partNumber}`:''}${x.notes?` — ${x.notes}`:''}`));addLines('Changes and approval',d.changes.map(x=>`${x.work} · ${x.approval} · ${x.reason}${x.notes?` — ${x.notes}`:''}`));textRow(content,'Mechanic notes',d.mechanicNotes);textRow(content,'Repair result',d.result);textRow(content,'Mechanic sign-off',d.signoff);}
 if(step==='qc'&&job.qc){const d=job.qc;textRow(content,'Final status',d.finalStatus);addLines('Verification checklist',d.checks.map(x=>`${x.name}: ${x.result}${x.note?` — ${x.note}`:''}`));addLines('Unresolved issues',d.unresolvedIssues.map(x=>`${x.issue} · ${x.status}${x.recommendation?` — ${x.recommendation}`:''}`));textRow(content,'Road test',`${d.roadTest}${d.odometerBefore!=null?` · Before ${d.odometerBefore}`:''}${d.odometerAfter!=null?` · After ${d.odometerAfter}`:''}`);textRow(content,'Returned items',d.returnedItems.join(', '));textRow(content,'Readiness notes',d.readinessNotes);textRow(content,'Recommendations',d.recommendations);textRow(content,'Customer notes',d.customerNotes);textRow(content,'Handover recipient',d.handoverRecipient);textRow(content,'Handover staff',d.handoverStaff);textRow(content,'Handover date / time',`${d.handoverDate} ${d.handoverTime}`);}
 sheet.hidden=false;sheet.classList.add('is-preview');window.print();window.addEventListener('afterprint',()=>{sheet.classList.remove('is-preview');sheet.hidden=true;},{once:true});}
export function mountWorkshopPage(root:HTMLElement){let loaded;try{loaded=loadStore(window.localStorage);}catch{loaded=loadStore({getItem:()=>{throw new Error('Storage unavailable');},setItem:()=>{throw new Error('Storage unavailable');}});}const {store}=loaded;const step=root.dataset.workshopStep;const job=jobFromUrl(store);if(loaded.message)status(root,loaded.message);context(root,job,store);if(step!=='intake'&&!job)status(root,'Choose a saved local job below or open this page with a valid job link.');if(step==='intake')mountIntake(root,store,job);if(step==='inspection')mountInspection(root,store,job);if(step==='work-order')mountWorkOrder(root,store,job);if(step==='qc')mountQC(root,store,job);$<HTMLButtonElement>(root,'[data-print]')?.addEventListener('click',()=>printJob(root,store,job));}
