/* eslint-disable @typescript-eslint/no-explicit-any -- heterogeneous form rows are serialized from data-field keyed controls. */
import { selectedWorkshopJob } from '../../lib/workshop/navigation.ts';
import { mountWorkshopNavigation, setWorkshopJobContext } from './navigation.ts';
import type { Inspection, OperationalStatus, QualityCheck, WorkOrder, WorkRow, WorkshopJob } from '../../lib/workshop/model.ts';
import { emptyInspection, calculateEstimate, validateIntake, validateInspection, workDuration, qcWarning, validateOdometers } from '../../lib/workshop/rules.ts';
import { loadStore, saveStore, createJob, updateJob, setWaitingParts, getJob, getCustomer, getVehicle, makeId } from '../../lib/workshop/store.ts';
import { canCompleteWorkshopJob, canSetWaitingParts, elapsedTime, estimateApprovalPending, nextWorkflowRoute, operationalStatus, validWorkOrder, workflowStatus } from '../../lib/workshop/queue.ts';
import { mountPartsInventory } from './parts-inventory.ts';
import { jobPartSummary, partBalance, stockState } from '../../lib/workshop/parts.ts';
import { latestKnownOdometer } from '../../lib/workshop/history.ts';
import { mountServiceHistory } from './service-history.ts';
import { mountBilling } from './billing.ts';
import { billingSummary } from '../../lib/workshop/billing.ts';
import { mountProcurement } from './procurement.ts';
import { needProgress } from '../../lib/workshop/procurement.ts';

const $ = <T extends HTMLElement = HTMLElement>(root: ParentNode, selector: string) => root.querySelector<T>(selector);
const all = <T extends HTMLElement>(root: ParentNode, selector: string) => [...root.querySelectorAll<T>(selector)];
const el = <K extends keyof HTMLElementTagNameMap>(tag: K, cls?: string, txt?: string) => { const node = document.createElement(tag); if (cls) node.className = cls; if (txt !== undefined) node.textContent = txt; return node; };
const value = (root: ParentNode, name: string) => (root.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[name="${name}"]`)?.value ?? '').trim();
const num = (root: ParentNode, name: string): number | null => value(root, name) === '' ? null : Number(value(root, name));
const localDate = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const stamp = () => `${Date.now().toString(36).slice(-5).toUpperCase()}`;
function set(root: ParentNode, name: string, v: unknown) { const node = root.querySelector<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>(`[name="${name}"]`); if (node) node.value = v == null ? '' : String(v); }
function setError(root: ParentNode, selector: string, message: string) { const node = root.querySelector<HTMLElement>(selector); if (node) { node.textContent = message; node.hidden = !message; } }
function money(n: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n); }
function rows<T extends {id:string}>(host: HTMLElement, list: T[], render: (row:T)=>HTMLElement) { host.replaceChildren(...list.map(render)); }
function textRow(parent: HTMLElement, label: string, content: unknown) { const p = el('p'); const b = el('strong', undefined, `${label}: `); p.append(b, document.createTextNode(content == null || content === '' ? '—' : String(content))); parent.append(p); }
function status(root: HTMLElement, message: string) { const n = $(root, '#workshop-status'); if (n) { n.textContent = message; n.hidden = !message; } }
function save(root: HTMLElement, store: ReturnType<typeof loadStore>['store']) { try { const result = saveStore(store, window.localStorage); if (!result.ok) status(root, result.message); else setWorkshopJobContext(root, store, getJob(store, root.dataset.selectedJob)); return result.ok; } catch { status(root,'Browser storage is unavailable. Your latest change was not saved.'); return false; } }
function context(root: HTMLElement, job: WorkshopJob | null, store: ReturnType<typeof loadStore>['store']) {
  setWorkshopJobContext(root, store, job);
  const picker = $(root, '#workshop-job-picker'); if (!picker) return;
  if (!job && store.jobs.length) { picker.hidden = false; picker.replaceChildren(el('strong', undefined, 'Existing local jobs')); for (const j of store.jobs) { const v=getVehicle(store,j), c=getCustomer(store,j); const a=el('a',undefined,`${j.number} · ${v?.plate ?? ''} · ${c?.name ?? ''}`) as HTMLAnchorElement; a.href=`?job=${encodeURIComponent(j.id)}`; picker.append(a); } } else picker.hidden = true;
}
function jobFromUrl(store: ReturnType<typeof loadStore>['store']) { return selectedWorkshopJob(store, new URL(location.href).searchParams); }
function linkFor(id: string, path: string) { return `${path}?job=${encodeURIComponent(id)}`; }
function labelInput(parent: HTMLElement, label: string, name: string, type='text', val='') { const l=el('label'); l.append(el('span',undefined,label)); const i=document.createElement('input'); i.name=name; i.type=type; i.value=val; i.dataset.field=name; l.append(i); parent.append(l); return i; }
function selectField(parent: HTMLElement, label: string, name: string, choices: string[], val: string) { const l=el('label'); l.append(el('span',undefined,label)); const s=el('select'); s.name=name; s.dataset.field=name; for (const x of choices) { const o=el('option',undefined,x); o.value=x; s.append(o); } s.value=val; l.append(s); parent.append(l); return s; }

function mountIntake(root: HTMLElement, store: ReturnType<typeof loadStore>['store'], job: WorkshopJob | null, onSelected: (job: WorkshopJob) => void) {
 const form=$<HTMLFormElement>(root,'#intake-form'); if(!form)return; const c=job?getCustomer(store,job):null,v=job?getVehicle(store,job):null,i=job?.intake;
 const customerPicker=form.querySelector<HTMLSelectElement>('[name="existingCustomerId"]')!;customerPicker.replaceChildren(new Option('New customer',''),...store.customers.map(customer=>new Option(`${customer.name}${customer.phone?` / ${customer.phone}`:''}`,customer.id)));const chooseCustomer=(id:string)=>{customerPicker.value=id;const selected=store.customers.find(customer=>customer.id===id);if(selected)for(const [name,value]of Object.entries({customerName:selected.name,phone:selected.phone,address:selected.address}))set(form,name,value);for(const name of ['customerName','phone','address']){const control=form.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[name="${name}"]`);if(control)control.disabled=!!selected&&!job;}};customerPicker.addEventListener('change',()=>chooseCustomer(customerPicker.value));if(job){customerPicker.value=job.customerId;customerPicker.disabled=true;}const vehiclePicker=form.querySelector<HTMLSelectElement>('[name="existingVehicleId"]')!;vehiclePicker.replaceChildren(new Option('Create a new vehicle record',''),...store.vehicles.map(vehicle=>new Option(`${vehicle.plate} · ${[vehicle.make,vehicle.model].filter(Boolean).join(' ')||vehicle.type} · last known ${latestKnownOdometer(store,vehicle.id)??'unknown'} km`,vehicle.id)));vehiclePicker.hidden=!!job;vehiclePicker.closest('label')?.toggleAttribute('hidden',!!job);vehiclePicker.addEventListener('change',()=>{const selected=store.vehicles.find(vehicle=>vehicle.id===vehiclePicker.value);if(!selected)return;for(const [name,value] of Object.entries({vehicleType:selected.type,plate:selected.plate,make:selected.make,model:selected.model,year:selected.year,color:selected.color,odometer:latestKnownOdometer(store,selected.id)}))set(form,name,value);const prior=store.jobs.filter(item=>item.vehicleId===selected.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];if(prior)chooseCustomer(prior.customerId);});
 if(job){ for(const [n,x] of Object.entries({customerName:c?.name,phone:c?.phone,address:c?.address,vehicleType:v?.type,plate:v?.plate,make:v?.make,model:v?.model,year:v?.year,color:v?.color,odometer:v?.odometer,complaint:i?.complaint,accessories:i?.accessories.join('\n'),conditionNotes:i?.conditionNotes,date:i?.date,arrivalTime:i?.arrivalTime})) set(form,n,x); }
 else {set(form,'date',localDate());set(form,'arrivalTime',`${String(new Date().getHours()).padStart(2,'0')}:${String(new Date().getMinutes()).padStart(2,'0')}`);}
 form.addEventListener('submit',e=>{e.preventDefault(); const errors=validateIntake({name:value(form,'customerName'),plate:value(form,'plate'),year:value(form,'year'),odometer:value(form,'odometer')});const selectedVehicleId=job?.vehicleId||value(form,'existingVehicleId'),knownOdometer=selectedVehicleId?latestKnownOdometer(store,selectedVehicleId):null,enteredOdometer=num(form,'odometer');if(knownOdometer!==null&&enteredOdometer!==null&&enteredOdometer<knownOdometer)errors.push(`Odometer cannot be below the last known reading of ${knownOdometer}.`); if(errors.length){setError(root,'#intake-error',errors.join(' '));return;}
 const intake={number:job?.intake.number??`WI-${localDate().replaceAll('-','')}-${stamp()}`, complaint:value(form,'complaint'), accessories:value(form,'accessories').split(/[\n,]/).map(x=>x.trim()).filter(Boolean),conditionNotes:value(form,'conditionNotes'),date:value(form,'date')||localDate(),arrivalTime:value(form,'arrivalTime')};
 if(job){ const customer=getCustomer(store,job), vehicle=getVehicle(store,job); if(customer)Object.assign(customer,{name:value(form,'customerName'),phone:value(form,'phone'),address:value(form,'address')}); if(vehicle)Object.assign(vehicle,{type:value(form,'vehicleType'),plate:value(form,'plate'),make:value(form,'make'),model:value(form,'model'),year:num(form,'year'),color:value(form,'color'),odometer:enteredOdometer===null?vehicle.odometer:Math.max(vehicle.odometer??0,enteredOdometer)}); updateJob(store,job.id,{intake}); }
 else createJob(store,{customer:{name:value(form,'customerName'),phone:value(form,'phone'),address:value(form,'address')},vehicle:{type:value(form,'vehicleType')==='Car'?'Car':'Motorcycle',plate:value(form,'plate'),make:value(form,'make'),model:value(form,'model'),year:num(form,'year'),color:value(form,'color'),odometer:num(form,'odometer')},intake,existingVehicleId:value(form,'existingVehicleId')||undefined,existingCustomerId:value(form,'existingCustomerId')||undefined});
 const saved=job??store.jobs.at(-1)!; if(save(root,store)){ job=saved; customerPicker.disabled=true; vehiclePicker.hidden=true;vehiclePicker.closest('label')?.setAttribute('hidden',''); onSelected(saved); const next=$<HTMLElement>(root,'#next-inspection'); if(next)next.hidden=false; const a=$<HTMLAnchorElement>(root,'#continue-inspection'); if(a)a.href=linkFor(saved.id,'/tools/workshop/inspection-estimate/');setError(root,'#intake-error','');status(root,'Intake saved in this browser.'); }
 });
}

function inputRow(group: string, fields: [string,string,string?][], values: Record<string,string>={}, select?: [string,string[]][]) { const card=el('div','workshop-row'); card.dataset.row='true'; card.dataset.rowGroup=group; const grid=el('div','form-grid'); for(const [name,label,type] of fields)labelInput(grid,label, name,type??'text',values[name]??''); for(const [name,choices] of select??[])selectField(grid,name,name,choices,values[name]??choices[0]); card.append(grid); return card; }
function mountInspection(root: HTMLElement, store: ReturnType<typeof loadStore>['store'], job: WorkshopJob | null) {
 const form=$<HTMLFormElement>(root,'#inspection-form'); if(!form)return; if(!job){form.hidden=true;return;} form.hidden=false;
 const v=getVehicle(store,job), data:Inspection=structuredClone(job.inspection??emptyInspection(v?.type==='Car'?'Car':'Motorcycle'));let initialScope=JSON.stringify({findings:data.findings,checklist:data.checklist,recommendedJobs:data.recommendedJobs.map(x=>({id:x.id,name:x.name,detail:x.detail,priority:x.priority})),parts:data.parts,labor:data.labor,consumables:data.consumables,additionalCost:data.additionalCost,discount:data.discount,taxRate:data.taxRate});set(form,'approvedBy',data.approvedBy??'');
 const ctx=$<HTMLElement>(root,'#inspection-context'); if(ctx){ctx.replaceChildren();textRow(ctx,'Intake complaint',job.intake.complaint);}
 set(form,'findings',data.findings); for(const n of ['consumables','additionalCost','discount','taxRate'] as const)set(form,n,data[n]);
 const checkHost=$<HTMLElement>(root,'#inspection-checklist')!; checkHost.replaceChildren(...data.checklist.map(g=>{const sec=el('fieldset');sec.append(el('legend',undefined,g.category));for(const item of g.items){const line=el('div','check-row');line.append(el('span',undefined,item.name));selectField(line,'Status',`check:${g.category}:${item.name}`,['Good','Monitor','Service','Replace','Not checked','Not applicable'],item.status);labelInput(line,'Note',`note:${g.category}:${item.name}`,'text',item.note);sec.append(line);}return sec;}));
 const recHost=$<HTMLElement>(root,'#recommended-rows')!,partHost=$<HTMLElement>(root,'#estimate-parts')!,laborHost=$<HTMLElement>(root,'#estimate-labor')!;
 const draw=()=>{rows(recHost,data.recommendedJobs,r=>{const row=inputRow('recommended',[['name','Recommended work'],['detail','Details']],{name:r.name,detail:r.detail},[['priority',['Urgent','Recommended','Can wait']]]);const s=row.querySelector('select')!;s.value=r.priority;const chk=el('label');const input=el('input');input.type='checkbox';input.checked=r.approved;input.dataset.field='approved';chk.append(input,document.createTextNode(' Customer approved'));row.append(chk);return row;}); rows(partHost,data.parts,r=>inputRow('estimate-part',[['name','Part'],['partNumber','Part number'],['quantity','Quantity','number'],['unit','Unit'],['unitPrice','Unit price','number']],r as any)); rows(laborHost,data.labor,r=>{const row=inputRow('labor',[['name','Labor'],['hours','Hours','number'],['rate','Hourly rate','number'],['fixed','Fixed cost','number']],r as any,[['mode',['fixed','hourly']]]);row.querySelector('select')!.value=r.mode;return row;}); };
 draw();
 const sync=()=>{const read=(host:HTMLElement)=>all<HTMLElement>(host,'[data-row]').map(row=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(row,'[data-field]').map(x=>[x.dataset.field!,x instanceof HTMLInputElement&&x.type==='checkbox'?x.checked:x.value]))); data.recommendedJobs=read(recHost).map((r:any,i:number)=>({...data.recommendedJobs[i],id:data.recommendedJobs[i]?.id??makeId('recommendation'),name:r.name,detail:r.detail,priority:r.priority,approved:!!r.approved}));data.parts=read(partHost).map((r:any,i:number)=>({id:data.parts[i]?.id??makeId('part'),name:r.name,partNumber:r.partNumber,quantity:Number(r.quantity),unit:r.unit,unitPrice:Number(r.unitPrice)}));data.labor=read(laborHost).map((r:any,i:number)=>({id:data.labor[i]?.id??makeId('labor'),name:r.name,mode:r.mode,hours:Number(r.hours),rate:Number(r.rate),fixed:Number(r.fixed)}));for(const g of data.checklist)for(const x of g.items){x.status=(form.querySelector(`[name="check:${CSS.escape(g.category)}:${CSS.escape(x.name)}"]`) as HTMLSelectElement)?.value as any??x.status;x.note=(form.querySelector(`[name="note:${CSS.escape(g.category)}:${CSS.escape(x.name)}"]`) as HTMLInputElement)?.value??x.note;}data.findings=value(form,'findings');for(const k of ['consumables','additionalCost','discount','taxRate'] as const)data[k]=Number(value(form,k)||0); };
 const refresh=()=>{sync();const s=$<HTMLElement>(root,'#estimate-summary')!;const total=calculateEstimate(data);s.textContent=`Parts ${money(total.parts)} · Labor ${money(total.labor)} · Other ${money(total.additional)} · Discount ${money(total.discount)} · Tax ${money(total.tax)} · Total ${money(total.total)}`;}; form.addEventListener('input',refresh);form.addEventListener('change',refresh);
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{refresh();const key=b.dataset.addRow;if(key==='recommended')data.recommendedJobs.push({id:makeId('recommendation'),name:'',detail:'',priority:'Recommended',approved:false});if(key==='estimate-part')data.parts.push({id:makeId('part'),name:'',partNumber:'',quantity:1,unit:'each',unitPrice:0});if(key==='labor')data.labor.push({id:makeId('labor'),name:'',mode:'fixed',hours:0,rate:0,fixed:0});draw();refresh();}));refresh();
 form.addEventListener('submit',e=>{e.preventDefault();refresh();const errors=validateInspection(data);if(errors.length){setError(root,'#inspection-error',errors.join(' '));return;}const scope=(x:Inspection)=>JSON.stringify({findings:x.findings,checklist:x.checklist,recommendedJobs:x.recommendedJobs.map(row=>({id:row.id,name:row.name,detail:row.detail,priority:row.priority})),parts:x.parts,labor:x.labor,consumables:x.consumables,additionalCost:x.additionalCost,discount:x.discount,taxRate:x.taxRate});const currentScope=scope(data),changed=currentScope!==initialScope;data.revision=(job.inspection?.revision??1)+(job.inspection&&changed?1:0);if(job.inspection&&changed){data.approvedAt=undefined;data.approvedBy=undefined;data.approvedRevision=undefined;data.recommendedJobs=data.recommendedJobs.map(item=>({...item,approved:false,approvedAt:undefined,approvedBy:undefined}));set(form,'approvedBy','');draw();}const required=data.recommendedJobs.filter(item=>item.name.trim());if(required.length&&required.every(item=>item.approved)){const approvedBy=value(form,'approvedBy');if(!approvedBy){setError(root,'#inspection-error','Enter the customer or authorized contact who approved this estimate.');return;}const approvedAt=new Date().toISOString();data.approvedBy=approvedBy;data.approvedAt=approvedAt;data.approvedRevision=data.revision;data.recommendedJobs=data.recommendedJobs.map(item=>item.name.trim()?({...item,approvedAt,approvedBy}):item);}const saved=updateJob(store,job.id,{inspection:data,status:'inspection'});if(!saved){setError(root,'#inspection-error','This inspection cannot be saved in the current job state.');return;}if(save(root,store)){initialScope=currentScope;const box=$<HTMLElement>(root,'#next-work-order')!,a=$<HTMLAnchorElement>(root,'#continue-work-order')!;box.hidden=false;a.href=linkFor(job.id,'/tools/workshop/work-order/');setError(root,'#inspection-error','');status(root,required.length?'Inspection saved with estimate approval evidence.':'Inspection and estimate saved.');}});
}

function mountWorkOrder(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){const form=$<HTMLFormElement>(root,'#work-order-form');if(!form)return;if(!job){form.hidden=true;return;}const ctx=$<HTMLElement>(root,'#work-order-context')!;ctx.replaceChildren();if(!job.inspection||estimateApprovalPending(job)){form.hidden=true;ctx.append(el('p','queue-feedback',!job.inspection?'Work Order is unavailable until this job has a saved inspection.':'Work Order is blocked until estimate approval is current for the saved scope.'));const link=el('a','button-link','Continue to Inspection & Estimate');link.href=linkFor(job.id,'/tools/workshop/inspection-estimate/');ctx.append(link);return;}form.hidden=false;textRow(ctx,'Customer complaint',job.intake.complaint);textRow(ctx,'Inspection findings',job.inspection.findings);const inventory=el('section','job-parts-summary');inventory.append(el('h3',undefined,'Inventory parts for this job'));const linked=jobPartSummary(store,job);if(linked.length){for(const item of linked)textRow(inventory,item.part.name,`Requested ${item.requested} ${item.part.unit} · issued ${item.issued} · available ${item.available} · shortage ${item.shortage}`);}else inventory.append(el('p',undefined,'No saved inventory-linked part rows yet. You can link a row below; stock changes only through an explicit issue.'));const inventoryLink=el('a','button-link', 'Open job parts in Parts Inventory') as HTMLAnchorElement;inventoryLink.href=linkFor(job.id,'/tools/workshop/parts-inventory/');inventory.append(inventoryLink);ctx.append(inventory);const data:WorkOrder=structuredClone(job.workOrder??{number:`WO-${job.number}`,date:localDate(),status:'Not started',mechanic:'',approvedWork:(job.inspection?.recommendedJobs.filter(x=>x.approved)??[]).map(x=>({id:makeId('work'),name:x.name,detail:x.detail,status:'Not started',mechanic:'',sourceRecommendationId:x.id})),actualWork:[],parts:[],changes:[],startTime:'',endTime:'',mechanicNotes:'',result:'',recommendations:'',signoff:''});
 for(const k of ['number','date','mechanic','startTime','endTime','mechanicNotes','result','recommendations','signoff','noRepairReason'] as const)set(form,k,data[k]);const noRepair=form.querySelector<HTMLInputElement>('[name="noRepairAcknowledged"]');if(noRepair)noRepair.checked=!!data.noRepairAcknowledged;form.querySelector<HTMLSelectElement>('select[name="status"]:not([data-field])')!.value=data.status; const specs:[string,keyof WorkOrder,string, [string,string,string?][],any?][]=[['approved-work','approvedWork','approved-work',[['name','Work'],['detail','Details'],['mechanic','Mechanic']], [['status',['Not started','In progress','Complete','Paused','Cancelled']]]],['actual-work','actualWork','actual-work',[['name','Work performed'],['detail','Details'],['mechanic','Mechanic']], [['status',['Not started','In progress','Complete','Paused','Cancelled']]]],['work-parts','parts','work-part',[['name','Part / material'],['partNumber','Part number'],['quantity','Quantity','number'],['unit','Unit'],['notes','Notes']]],['work-changes','changes','change',[['work','Proposed change'],['reason','Reason'],['notes','Notes']], [['approval',['Awaiting approval','Approved','Deferred','Declined']]]]];
 const draw=()=>{for(const [host,key,group,fs,select] of specs){const target=$<HTMLElement>(root,`#${host}`)!;rows(target,(data[key] as any[]),r=>{const row=inputRow(group,fs,r as any,select);if(key==='approvedWork'&&r.sourceRecommendationId)row.append(el('p','parts-row-hint','Approved from this inspection recommendation.'));if(key==='actualWork'){const label=el('label');label.append(el('span',undefined,'Approved scope item (optional)'));const pick=el('select');pick.dataset.field='sourceRecommendationId';pick.append(new Option('Additional / unplanned work',''));for(const approved of data.approvedWork.filter(item=>item.sourceRecommendationId))pick.append(new Option(approved.name,approved.sourceRecommendationId!));pick.value=r.sourceRecommendationId??'';label.append(pick);row.querySelector('.form-grid')?.append(label);}if(select?.length)row.querySelector('select')!.value=r.status??r.approval;if(key==='parts'){const grid=row.querySelector('.form-grid')!;const linked=el('label');linked.append(el('span',undefined,'Inventory part (optional)'));const pick=el('select');pick.dataset.field='partId';const empty=el('option',undefined,'Free-text / non-stock');empty.value='';pick.append(empty);for(const p of store.parts.filter(x=>x.active||x.id===r.partId)){const o=el('option',undefined,`${p.name} · ${p.sku||'No SKU'} · ${partBalance(store,p.id)} ${p.unit} · ${stockState(store,p)}`);o.value=p.id;pick.append(o);}pick.value=r.partId??'';linked.append(pick);grid.append(linked);if(r.partId){const p=store.parts.find(x=>x.id===r.partId);if(p){const hint=el('p','parts-row-hint',`Requested ${r.quantity} ${r.unit}; issued quantities are recorded explicitly in Parts Inventory. Available now: ${partBalance(store,p.id)} ${p.unit}.`);row.append(hint);}}}return row;});}};draw();
  const sync=()=>{for(const [host,key] of specs){const target=$<HTMLElement>(root,`#${host}`)!;const existing=data[key] as any[];const list=all<HTMLElement>(target,'[data-row]').map(row=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(row,'[data-field]').map(x=>[x.dataset.field!,x.value])));if(key==='approvedWork'||key==='actualWork') (data[key] as WorkRow[]) = list.map((x:any,i:number)=>({id:existing[i]?.id??makeId('work'),name:x.name,detail:x.detail,mechanic:x.mechanic,status:x.status,sourceRecommendationId:x.sourceRecommendationId||existing[i]?.sourceRecommendationId||undefined}));else if(key==='parts')data.parts=list.map((x:any,i:number)=>({...x,id:existing[i]?.id??makeId('part'),partId:x.partId||undefined,quantity:Number(x.quantity)}));else data.changes=list.map((x:any,i:number)=>({...x,id:existing[i]?.id??makeId('change')}));}};
 $<HTMLElement>(root,'#work-parts')!.addEventListener('change',e=>{const target=e.target as HTMLSelectElement;if(target.dataset.field!=='partId')return;const p=store.parts.find(x=>x.id===target.value),row=target.closest<HTMLElement>('[data-row]');if(p&&row){for(const [field,val]of [['name',p.name],['partNumber',p.sku],['unit',p.unit]]){const input=row.querySelector<HTMLInputElement>(`[data-field="${field}"]`);if(input)input.value=val;}}});
 const time=()=>{const node=$<HTMLElement>(root,'#work-duration')!;node.textContent=workDuration(value(form,'startTime'),value(form,'endTime'))?`Recorded duration: ${workDuration(value(form,'startTime'),value(form,'endTime'))}`:'';};form.addEventListener('input',time);time();
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{sync();const k=b.dataset.addRow;if(k==='approved-work'||k==='actual-work')data[k==='approved-work'?'approvedWork':'actualWork'].push({id:makeId('work'),name:'',detail:'',status:'Not started',mechanic:''});if(k==='work-part')data.parts.push({id:makeId('part'),name:'',partNumber:'',quantity:1,unit:'each',notes:''});if(k==='change')data.changes.push({id:makeId('change'),work:'',reason:'',approval:'Awaiting approval',notes:''});draw();}));
 form.addEventListener('submit',e=>{e.preventDefault();sync();data.number=value(form,'number');data.date=value(form,'date');data.status=form.querySelector<HTMLSelectElement>('select[name="status"]:not([data-field])')!.value as WorkOrder['status'];data.mechanic=value(form,'mechanic');data.startTime=value(form,'startTime');data.endTime=value(form,'endTime');data.mechanicNotes=value(form,'mechanicNotes');data.result=value(form,'result');data.recommendations=value(form,'recommendations');data.signoff=value(form,'signoff');data.noRepairAcknowledged=!!form.querySelector<HTMLInputElement>('[name="noRepairAcknowledged"]')?.checked;data.noRepairReason=value(form,'noRepairReason');if(!data.number.trim()||data.parts.some(p=>!Number.isFinite(p.quantity)||p.quantity<=0)){setError(root,'#work-order-error','Enter a work order number and valid positive quantities for all parts.');return;}if(data.status==='Complete'&&!validWorkOrder({...job,workOrder:data})){setError(root,'#work-order-error',data.noRepairAcknowledged?'Inspection-only completion needs a reason and no performed work rows.':'Mark each actual-work row Complete or Cancelled and record at least one completed work item, or acknowledge no repair performed.');return;}const saved=updateJob(store,job.id,{workOrder:data,status:'work-order'});if(!saved){setError(root,'#work-order-error','Work Order cannot be saved: estimate approval is pending or this job is terminal.');return;}if(save(root,store)){setError(root,'#work-order-error','');if(data.status==='Cancelled'){for(const control of all<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement|HTMLButtonElement>(form,'input,select,textarea,button'))control.disabled=true;status(root,'Work Order cancelled. This saved job is read-only and can be reviewed or printed.');return;}const box=$<HTMLElement>(root,'#next-qc')!;box.hidden=false;$<HTMLAnchorElement>(root,'#continue-qc')!.href=linkFor(job.id,'/tools/workshop/qc-handover/');status(root,'Work order saved.');}});
}

function mountQC(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){const form=$<HTMLFormElement>(root,'#qc-form');if(!form)return;if(!job){form.hidden=true;return;}form.hidden=false;if(job.status==='completed')$<HTMLElement>(root,'#job-completed')!.hidden=false;const ctx=$<HTMLElement>(root,'#qc-context')!;ctx.replaceChildren();if(!job.workOrder||!validWorkOrder(job))ctx.append(el('p','field-error','A valid completed Work Order is required before this job can become Ready for Pickup or Completed.'));textRow(ctx,'Work order',job.workOrder?.number);textRow(ctx,'Repair result',job.workOrder?.result);textRow(ctx,'Inspection findings',job.inspection?.findings);if(workflowStatus(job)==='Ready for Pickup'||workflowStatus(job)==='Completed'){const billingLink=el('a','button-link button-secondary','Create / Review Invoice') as HTMLAnchorElement;billingLink.href='/tools/workshop/billing/';ctx.append(billingLink);}
 const data:QualityCheck=structuredClone(job.qc??{number:`QC-${job.number}`,date:localDate(),inspector:'',mechanic:job.workOrder?.mechanic??'',finalStatus:'In progress',checks:[{name:'Repair matches approved work',result:'Not checked',note:''},{name:'Parts and fasteners secured',result:'Not checked',note:''},{name:'Brakes and safety systems',result:'Not checked',note:''},{name:'Tools and protective covers removed',result:'Not checked',note:''},{name:'Vehicle clean and ready',result:'Not checked',note:''}],unresolvedIssues:[],returnedItems:[],roadTest:'Not required',roadTester:'',odometerBefore:null,odometerAfter:null,roadTestNotes:'',readinessNotes:'',recommendations:'',customerNotes:'',handoverRecipient:'',handoverStaff:'',handoverDate:'',handoverTime:''});
 for(const k of ['number','date','finalStatus','inspector','mechanic','roadTest','roadTester','odometerBefore','odometerAfter','roadTestNotes','readinessNotes','recommendations','customerNotes','handoverRecipient','handoverStaff','handoverDate','handoverTime'] as const)set(form,k,data[k]);set(form,'returnedItems',data.returnedItems.join('\n'));
 const checkHost=$<HTMLElement>(root,'#qc-checklist')!;const extra=$<HTMLElement>(root,'#qc-extra-rows')!,issues=$<HTMLElement>(root,'#qc-issues')!;
 const draw=()=>{checkHost.replaceChildren(...data.checks.filter(c=>!(c as any).extra).map((c,ix)=>{const row=el('div','check-row');row.append(el('span',undefined,c.name));selectField(row,'Result',`qccheck:${ix}`,['Pass','Needs attention','Not applicable','Not checked'],c.result);labelInput(row,'Note',`qcnote:${ix}`,'text',c.note);return row;}));rows(extra,data.checks.filter(c=>(c as any).extra) as any[],c=>{const row=inputRow('qc-check',[['name','Check'],['note','Note']],c as any,[['result',['Pass','Needs attention','Not applicable','Not checked']]]);row.querySelector('select')!.value=c.result;return row;});rows(issues,data.unresolvedIssues,x=>{const row=inputRow('qc-issue',[['issue','Issue'],['recommendation','Deferral reason / follow-up plan']],x as any,[['status',['Customer deferred','Needs follow-up']]]);row.querySelector('select')!.value=x.status;return row;});};draw();
 const sync=()=>{data.checks=data.checks.map((c,ix)=>{const s=form.querySelector(`[name="qccheck:${ix}"]`) as HTMLSelectElement;const n=form.querySelector(`[name="qcnote:${ix}"]`) as HTMLInputElement;return s?{...c,result:s.value as any,note:n?.value??''}:c;});const read=(host:HTMLElement)=>all<HTMLElement>(host,'[data-row]').map(r=>Object.fromEntries(all<HTMLInputElement|HTMLSelectElement>(r,'[data-field]').map(x=>[x.dataset.field!,x.value])));data.checks=data.checks.filter(c=>!(c as any).extra).concat(read(extra).map((x:any)=>({name:x.name,result:x.result,note:x.note,extra:true} as any)));data.unresolvedIssues=read(issues).map((x:any,i:number)=>({id:data.unresolvedIssues[i]?.id??makeId('issue'),issue:x.issue,status:x.status,recommendation:x.recommendation,deferralReason:x.status==='Customer deferred'?x.recommendation:undefined}));for(const k of ['number','date','finalStatus','inspector','mechanic','roadTest','roadTester','roadTestNotes','readinessNotes','recommendations','customerNotes','handoverRecipient','handoverStaff','handoverDate','handoverTime'] as const)(data as any)[k]=value(form,k);data.odometerBefore=num(form,'odometerBefore');data.odometerAfter=num(form,'odometerAfter');data.returnedItems=value(form,'returnedItems').split(/[\n,]/).map(x=>x.trim()).filter(Boolean);};
 const warn=()=>{sync();const m=qcWarning(data.checks,data.finalStatus==='Ready for handover')|| (data.finalStatus==='Ready for handover'&&data.unresolvedIssues.some(x=>x.status==='Needs follow-up'||!x.issue.trim()||x.status==='Customer deferred'&&!(x.deferralReason??x.recommendation).trim())?'Resolve blocking follow-ups; record a reason for every customer deferral.':'');const n=$<HTMLElement>(root,'#qc-warning')!;n.textContent=m;n.hidden=!m;};form.addEventListener('input',warn);form.addEventListener('change',warn);
 all<HTMLButtonElement>(form,'[data-add-row]').forEach(b=>b.addEventListener('click',()=>{sync();if(b.dataset.addRow==='qc-check')data.checks.push({name:'',result:'Not checked',note:'',extra:true} as any);if(b.dataset.addRow==='qc-issue')data.unresolvedIssues.push({id:makeId('issue'),issue:'',status:'Needs follow-up',recommendation:''});draw();}));
 const persist=(complete:boolean)=>{sync();const errors=validateOdometers(data.odometerBefore,data.odometerAfter);if(!data.number.trim())errors.push('QC number is required.');const pending=data.checks.some(c=>c.result==='Needs attention'||c.result==='Not checked');if(complete&&(!job.workOrder||!validWorkOrder(job)))errors.push('A valid completed Work Order with actual-work evidence (or documented inspection-only/no-repair) is required.');if(complete&&(pending||data.unresolvedIssues.some(x=>x.status==='Needs follow-up'||!x.issue.trim()||x.status==='Customer deferred'&&!(x.deferralReason??x.recommendation).trim())||data.finalStatus!=='Ready for handover'))errors.push('Pass all QC checks, close blocking follow-ups, document customer deferrals, and select Ready for handover.');if(complete&&data.roadTest==='Not completed')errors.push('Complete the road test or explicitly select Not required before handover.');if(complete&&(!data.handoverRecipient.trim()||!data.handoverStaff.trim()||!data.handoverDate.trim()||!data.handoverTime.trim()))errors.push('Record the recipient, handing-over staff member, handover date, and time to confirm actual handover.');if(complete&&!canCompleteWorkshopJob({...job,status:'qc',qc:data}))errors.push('The job has not passed every operational completion requirement.');const vehicle=getVehicle(store,job),last=latestKnownOdometer(store,job.vehicleId),captured=data.odometerAfter??data.odometerBefore??vehicle?.odometer??null;if(complete&&last!==null&&captured!==null&&captured<last)errors.push(`Completion odometer cannot be below the last known reading of ${last}.`);if(errors.length){setError(root,'#qc-error',errors.join(' '));return false;}if(complete&&vehicle&&captured!==null)vehicle.odometer=Math.max(vehicle.odometer??0,captured);const updated=updateJob(store,job.id,{qc:data,status:complete?'completed':'qc',...(complete?{serviceOdometer:captured}:{})});if(!updated){setError(root,'#qc-error','The job is blocked by an unmet Work Order, QC, road-test, or handover requirement.');return false;}if(!save(root,store))return false;setError(root,'#qc-error','');status(root,complete?'Job completed and saved in this browser.':'QC and handover saved.');if(complete){$<HTMLElement>(root,'#job-completed')!.hidden=false;}return true;};form.addEventListener('submit',e=>{e.preventDefault();persist(false);});$<HTMLButtonElement>(root,'#complete-job')?.addEventListener('click',()=>persist(true));
}

function printJob(root:HTMLElement,store:ReturnType<typeof loadStore>['store'],job:WorkshopJob|null){if(!job){status(root,'Select a saved job before printing.');return;}const sheet=$<HTMLElement>(root,'#print-sheet')!;const title=$<HTMLElement>(root,'#print-title')!;const content=$<HTMLElement>(root,'#print-content')!;const c=getCustomer(store,job),v=getVehicle(store,job),step=root.dataset.workshopStep;title.textContent=`${job.number} · ${step?.replace('-',' ')??'workshop'}`;content.replaceChildren();const details:[string,string|undefined][]=[['Customer',c?.name],['Phone',c?.phone],['Address',c?.address],['Vehicle',`${v?.plate??''} ${v?.make??''} ${v?.model??''} ${v?.year??''}`],['Odometer',v?.odometer==null?undefined:`${v.odometer.toLocaleString()} km`],['Intake complaint',job.intake.complaint],['Items received',job.intake.accessories.join(', ')],['Condition notes',job.intake.conditionNotes]];for(const [k,x] of details)if(x)textRow(content,k,x);
 const section=(name:string)=>{const h=el('h3',undefined,name);content.append(h);return el('div');};const addLines=(name:string,values:string[])=>{if(!values.length)return;const wrap=section(name);for(const item of values){const p=el('p','print-line',item);wrap.append(p);}content.append(wrap);};
 if(step==='inspection'&&job.inspection){const d=job.inspection;const total=calculateEstimate(d);textRow(content,'Inspection findings',d.findings);addLines('Inspection checklist',d.checklist.flatMap(g=>g.items.map(x=>`${g.category} · ${x.name}: ${x.status}${x.note?` — ${x.note}`:''}`)));addLines('Recommended work',d.recommendedJobs.map(x=>`${x.name} · ${x.priority} · ${x.approved?'Approved':'Not approved'}${x.detail?` — ${x.detail}`:''}`));addLines('Parts estimate',d.parts.map(x=>`${x.name} · ${x.quantity} ${x.unit} × ${money(x.unitPrice)} = ${money(x.quantity*x.unitPrice)}`));addLines('Labor estimate',d.labor.map(x=>`${x.name} · ${money(x.mode==='hourly'?x.hours*x.rate:x.fixed)}`));textRow(content,'Estimate total',money(total.total));}
 if(step==='work-order'&&job.workOrder){const d=job.workOrder;textRow(content,'Work order number',d.number);textRow(content,'Status',d.status);addLines('Approved work',d.approvedWork.map(x=>`${x.name}${x.detail?` — ${x.detail}`:''} · ${x.status}`));addLines('Work performed',d.actualWork.map(x=>`${x.name}${x.detail?` — ${x.detail}`:''} · ${x.status}${x.mechanic?` · ${x.mechanic}`:''}`));addLines('Parts and materials',d.parts.map(x=>`${x.name} · Qty ${x.quantity}${x.partNumber?` · ${x.partNumber}`:''}${x.notes?` — ${x.notes}`:''}`));addLines('Changes and approval',d.changes.map(x=>`${x.work} · ${x.approval} · ${x.reason}${x.notes?` — ${x.notes}`:''}`));textRow(content,'Mechanic notes',d.mechanicNotes);textRow(content,'Repair result',d.result);textRow(content,'Mechanic sign-off',d.signoff);}
 if(step==='qc'&&job.qc){const d=job.qc;textRow(content,'Final status',d.finalStatus);addLines('Verification checklist',d.checks.map(x=>`${x.name}: ${x.result}${x.note?` — ${x.note}`:''}`));addLines('Unresolved issues',d.unresolvedIssues.map(x=>`${x.issue} · ${x.status}${x.recommendation?` — ${x.recommendation}`:''}`));textRow(content,'Road test',`${d.roadTest}${d.odometerBefore!=null?` · Before ${d.odometerBefore}`:''}${d.odometerAfter!=null?` · After ${d.odometerAfter}`:''}`);textRow(content,'Returned items',d.returnedItems.join(', '));textRow(content,'Readiness notes',d.readinessNotes);textRow(content,'Recommendations',d.recommendations);textRow(content,'Customer notes',d.customerNotes);textRow(content,'Handover recipient',d.handoverRecipient);textRow(content,'Handover staff',d.handoverStaff);textRow(content,'Handover date / time',`${d.handoverDate} ${d.handoverTime}`);}
 sheet.hidden=false;sheet.classList.add('is-preview');window.addEventListener('afterprint',()=>{sheet.classList.remove('is-preview');sheet.hidden=true;},{once:true});window.print();}
function queueArrival(job: WorkshopJob): Date {
  const value = `${job.intake.date}T${job.intake.arrivalTime || '00:00'}`;
  const arrival = new Date(value);
  return Number.isFinite(arrival.getTime()) ? arrival : new Date(job.createdAt);
}

function mountWorkshopQueue(root: HTMLElement, store: ReturnType<typeof loadStore>['store']): void {
  const summary = $(root, '#queue-summary')!, toolbar = $(root, '#queue-toolbar')!, list = $(root, '#queue-list')!, feedback = $(root, '#queue-feedback')!;
  const statuses: OperationalStatus[] = ['Intake','Inspection','Waiting Approval','Work In Progress','Waiting Parts','QC','Ready for Pickup','Completed','Cancelled'];
  const rank = new Map(statuses.map((item, index) => [item, index]));
  const state = { query: '', status: 'All', sort: 'newest' };
  const params = new URL(location.href).searchParams;
  const linkedJob = selectedWorkshopJob(store, params)?.id ?? null;
  if (params.has('job') && !linkedJob) { feedback.textContent = 'That job link is no longer available in this browser. Showing the saved queue.'; feedback.hidden = false; }
  const searchLabel = el('label', 'queue-search-label', 'Search jobs');
  const search = el('input'); search.type = 'search'; search.id = 'queue-search'; search.placeholder = 'Plate, customer, make or model'; search.autocomplete = 'off'; search.setAttribute('aria-label', 'Search by plate, customer, make or model'); searchLabel.append(search);
  const filterLabel = el('label', undefined, 'Filter by status'); const filter = el('select'); filter.id = 'queue-filter'; filter.setAttribute('aria-label', 'Filter jobs by status');
  for (const item of ['All', ...statuses]) { const option = el('option', undefined, item); option.value = item; filter.append(option); } filterLabel.append(filter);
  const sortLabel = el('label', undefined, 'Sort jobs'); const sort = el('select'); sort.id = 'queue-sort'; sort.setAttribute('aria-label', 'Sort workshop jobs');
  for (const [value,label] of [['newest','Newest intake'],['oldest','Oldest intake'],['longest','Longest waiting'],['status','Current status']] as const) { const option=el('option',undefined,label); option.value=value; sort.append(option); } sort.value=state.sort; sortLabel.append(sort);
  toolbar.replaceChildren(searchLabel, filterLabel, sortLabel);
  const render = (): void => {
    const now = new Date();
    const counts = new Map<OperationalStatus, number>(statuses.map(item => [item,0]));
    for (const job of store.jobs) { const status = operationalStatus(job); counts.set(status, (counts.get(status) ?? 0) + 1); }
    const allButton = el('button','queue-count',`All jobs · ${store.jobs.length}`); allButton.type='button'; allButton.dataset.statusFilter='All';allButton.setAttribute('aria-pressed',String(state.status==='All')); allButton.addEventListener('click',()=>{state.status='All';filter.value='All';render();$(root,'[data-status-filter="All"]')?.focus();});
    summary.replaceChildren(allButton,...statuses.map(item=>{const button=el('button','queue-count',`${item} · ${counts.get(item)??0}`);button.type='button';button.dataset.statusFilter=item;button.setAttribute('aria-pressed',String(state.status===item));button.addEventListener('click',()=>{state.status=item;filter.value=item;render();$(root,`[data-status-filter="${item}"]`)?.focus();});return button;}));
    const query = state.query.trim().toLocaleLowerCase();
    const jobs = store.jobs.filter(job=>{
      const status=operationalStatus(job), customer=getCustomer(store,job), vehicle=getVehicle(store,job);
      const text=[vehicle?.plate,customer?.name,vehicle?.make,vehicle?.model].filter(Boolean).join(' ').toLocaleLowerCase();
      return (state.status==='All'||status===state.status)&&(!query||text.includes(query));
    });
    jobs.sort((a,b)=>{
      const byArrival=queueArrival(a).getTime()-queueArrival(b).getTime();
      if(state.sort==='oldest'||state.sort==='longest')return byArrival;
      if(state.sort==='status')return (rank.get(operationalStatus(a))??0)-(rank.get(operationalStatus(b))??0)||byArrival;
      return -byArrival;
    });
    if(!jobs.length){const empty=el('div','queue-empty-state');empty.append(el('h2',undefined,store.jobs.length?'No jobs match these filters':'No Workshop Jobs yet'),el('p',undefined,store.jobs.length?'Try a different search or status filter.':'Start an intake; its Workshop Job will appear here automatically.'));if(!store.jobs.length){const link=el('a','button-link','Start Vehicle Intake →');link.href='/tools/workshop/vehicle-intake/';empty.append(link);}list.replaceChildren(empty);return;}
    list.replaceChildren(...jobs.map(job=>{
      const customer=getCustomer(store,job), vehicle=getVehicle(store,job), current=operationalStatus(job), underlying=workflowStatus(job), arrival=queueArrival(job);
      const article=el('article','queue-job');article.dataset.jobId=job.id;if(job.id===linkedJob)article.classList.add('is-linked-job');
      const heading=el('div','queue-job-heading');const vehicleName=[vehicle?.make,vehicle?.model].filter(Boolean).join(' ')||'Vehicle';heading.append(el('h2',undefined,vehicleName),el('span','queue-status-badge',current));article.append(heading);
      const plate=el('p','queue-plate',vehicle?.plate||'Plate not recorded');article.append(plate);
      const context=el('dl','queue-job-details');for(const [label,value] of [['Customer',customer?.name||'Not recorded'],['Workshop Job',job.number],['Arrived',new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(arrival)],['Waiting',elapsedTime(arrival.toISOString(),now)],['Primary technician',job.workOrder?.mechanic||'Not assigned']] as const){const dt=el('dt',undefined,label),dd=el('dd',undefined,value);if(label==='Waiting')dd.dataset.elapsedSince=arrival.toISOString();context.append(dt,dd);}article.append(context);
      if(current==='Waiting Parts'){article.append(el('p','queue-underlying',`Workflow status underneath: ${underlying}`));if(job.operations?.waitingPartsReason)article.append(el('p','queue-underlying',`Reason: ${job.operations.waitingPartsReason}`));const needs=store.purchaseNeeds.filter(n=>n.jobId===job.id),summary=needs.map(n=>`${n.partNameSnapshot}: ${needProgress(store,n).state}${needProgress(store,n).open>0?` · open ${needProgress(store,n).open} ${n.unitSnapshot}`:''}`).join(' · ');if(summary){article.append(el('p','queue-underlying',`Procurement: ${summary}`));const procurementLink=el('a','button-link button-secondary','Open Procurement →') as HTMLAnchorElement;procurementLink.href='/tools/workshop/procurement/';article.append(procurementLink);}}
      const timeline=el('details','queue-timeline');const history=job.operations?.history??[];timeline.append(el('summary',undefined,`Status timeline (${history.length})`));const entries=el('ol');for(const event of [...history].reverse()){const li=el('li');li.append(el('strong',undefined,event.status),el('time',undefined,`${new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.at))}${event.reason?` · ${event.reason}`:''}`));entries.append(li);}timeline.append(entries);article.append(timeline);
      const actions=el('div','queue-job-actions'),route=nextRoute(current,job);const next=el('a','button-link',nextAction(route,current));next.href=jobHref(job.id,route);actions.append(next);
      if(current==='Ready for Pickup'||current==='Completed'){const invoices=store.invoices.filter(i=>i.jobId===job.id),active=invoices.find(i=>i.status!=='Void'),billingText=!active?(invoices.length?'Void / Replacement Needed':'No Invoice'):active.status==='Draft'?'Draft':billingSummary(store,active).status;const billingLink=el('a','button-link button-secondary',`Billing · ${billingText}`) as HTMLAnchorElement;billingLink.href='/tools/workshop/billing/';actions.append(billingLink);}
      if(current==='Waiting Parts'){const clear=el('button','button-secondary','Clear Waiting Parts');clear.type='button';clear.addEventListener('click',()=>changeWaitingParts(job,false));actions.append(clear);}
      else if(canSetWaitingParts(job)){const wait=el('button','button-secondary','Mark as Waiting Parts');wait.type='button';wait.addEventListener('click',()=>changeWaitingParts(job,true));actions.append(wait);}
      article.append(actions);if(current==='Completed'){const historyLink=el('a','button-link button-secondary','View Service History') as HTMLAnchorElement;historyLink.href='/tools/workshop/service-history/';actions.append(historyLink);}return article;
    }));
  };
  const changeWaitingParts=(job:WorkshopJob, waiting:boolean):void=>{
    const shortage=jobPartSummary(store,job).reduce((sum,row)=>sum+row.shortage,0);const manualReason=waiting&&shortage===0?window.prompt('No inventory shortage is recorded. Add a short reason for Waiting Parts (external supplier, special order, customer-supplied part):')?.trim()??'':'';if(waiting&&shortage===0&&!manualReason){feedback.textContent='A reason is required when marking Waiting Parts without an inventory shortage.';feedback.hidden=false;return;}const before=structuredClone(job), result=setWaitingParts(store,job.id,waiting,new Date(),manualReason);
    if(!result){feedback.textContent='Waiting Parts is only available for an unfinished job.';feedback.hidden=false;return;}
    const saved=saveStore(store,window.localStorage);
    if(!saved.ok){Object.assign(job,before);feedback.textContent=saved.message;feedback.hidden=false;return;}
    feedback.textContent=waiting?'Job marked as Waiting Parts. The underlying workflow is unchanged.':'Waiting Parts cleared; the job returned to its derived workflow status.';feedback.hidden=false;render();
  };
  search.addEventListener('input',()=>{state.query=search.value;render();const next=$<HTMLInputElement>(root,'#queue-search');next?.focus();next?.setSelectionRange(next.value.length,next.value.length);});
  filter.addEventListener('change',()=>{state.status=filter.value;render();});
  sort.addEventListener('change',()=>{state.sort=sort.value;render();});
  render();
  if(linkedJob&&getJob(store,linkedJob))requestAnimationFrame(()=>root.querySelector<HTMLElement>('[data-job-id="'+CSS.escape(linkedJob)+'"]')?.scrollIntoView({block:'center'}));
  window.setInterval(()=>{for(const node of all<HTMLElement>(root,'[data-elapsed-since]'))node.textContent=elapsedTime(node.dataset.elapsedSince??'');},60_000);
}

function nextRoute(status: OperationalStatus, job: WorkshopJob): string {
  if(status==='Cancelled')return '/tools/workshop/work-order/';
  if(status==='Waiting Parts')return nextWorkflowRoute(job);
  if(status==='Intake')return '/tools/workshop/inspection-estimate/';if(status==='Inspection')return nextWorkflowRoute(job);
  if(status==='Waiting Approval'||status==='Work In Progress')return nextWorkflowRoute(job);
  return '/tools/workshop/qc-handover/';
}
function nextAction(route: string, status: OperationalStatus): string {
  if(status==='Cancelled')return 'Review Cancelled Work Order →';
  if(route.endsWith('inspection-estimate/'))return 'Continue to Inspection & Estimate →';
  if(route.endsWith('work-order/'))return 'Continue to Work Order →';
  return status==='Completed'?'Review Completed Job →':status==='Ready for Pickup'?'Open QC & Handover →':'Continue to QC & Handover →';
}
function jobHref(id:string,route:string):string{return `${route}?job=${encodeURIComponent(id)}`;}

export function mountWorkshopPage(root: HTMLElement) {
  if (root.dataset.workshopMounted === 'true') return;
  root.dataset.workshopMounted = 'true';
  let loaded;
  try { loaded = loadStore(window.localStorage); }
  catch { loaded = loadStore({ getItem: () => { throw new Error('Storage unavailable'); }, setItem: () => { throw new Error('Storage unavailable'); } }); }
  const { store } = loaded, step = root.dataset.workshopStep;
  if (loaded.message) status(root, loaded.message);
  mountWorkshopNavigation(root, store);
  const empty = root.querySelector<HTMLElement>('#workshop-empty')!;
  const noRecords = step === 'parts-inventory' ? !store.parts.length : step === 'procurement' ? !store.purchaseNeeds.length && !store.purchaseOrders.length : step === 'billing' ? !store.invoices.length : step === 'service-history' ? !store.jobs.some(job => workflowStatus(job) === 'Completed') : step !== 'intake' && !store.jobs.length;
  if (noRecords) {
    empty.hidden = false;
    const message = el('p', undefined, step === 'parts-inventory' ? 'No parts yet. Add a part below to begin your local inventory.' : step === 'procurement' ? 'No purchase needs or orders yet. Add a need below or review shortages in Parts Inventory.' : step === 'billing' ? 'No invoices yet. Billing starts from jobs ready for pickup or completed after QC.' : step === 'service-history' ? 'No service history yet. Completed jobs appear here after QC and handover.' : 'No local jobs yet. Start intake before continuing the service workflow.');
    const link = el('a', 'button-link', 'Start a Workshop Job'); link.href = '/tools/workshop/vehicle-intake/'; empty.append(message, link);
  }
  const print = $<HTMLButtonElement>(root, '[data-print]');
  if (step === 'queue' || step === 'parts-inventory') {
    print?.addEventListener('click', () => printOperationalSummary(root, store, step));
  }
  if (step === 'billing') { mountBilling(root, store); return; }
  if (step === 'procurement') { mountProcurement(root, store); return; }
  if (step === 'service-history') { mountServiceHistory(root); return; }
  if (step === 'parts-inventory') { mountPartsInventory(root, store); return; }
  if (step === 'queue') { mountWorkshopQueue(root, store); return; }
  let job = jobFromUrl(store);
  context(root, job, store);
  if (step !== 'intake' && !job) status(root, 'Choose a saved local job below or open this page with a valid job link.');
  if (step === 'intake') mountIntake(root, store, job, saved => {
    job = saved;
    context(root, saved, store);
    setWorkshopJobContext(root, store, saved, true);
  });
  if (step === 'inspection') mountInspection(root, store, job);
  if (step === 'work-order') mountWorkOrder(root, store, job);
  if (step === 'qc') mountQC(root, store, job);
  if (job?.status === 'completed' || job?.workOrder?.status === 'Cancelled') {
    status(root, job.workOrder?.status === 'Cancelled' ? 'This Work Order is cancelled. The saved job is read-only and can be reviewed or printed.' : 'This completed job is read-only. You can review or print its saved workflow.');
    if (job.workOrder?.status === 'Cancelled' && step === 'qc') $<HTMLFormElement>(root, '#qc-form')?.setAttribute('hidden', '');
    for (const form of all<HTMLFormElement>(root, 'form')) for (const control of all<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement | HTMLButtonElement>(form, 'input,select,textarea,button')) control.disabled = true;
  }
  print?.addEventListener('click', () => printJob(root, store, job));
}

function printOperationalSummary(root: HTMLElement, store: ReturnType<typeof loadStore>['store'], step: 'queue' | 'parts-inventory'): void {
  const sheet = $<HTMLElement>(root, '#print-sheet')!, content = $<HTMLElement>(root, '#print-content')!;
  $<HTMLElement>(root, '#print-title')!.textContent = step === 'queue' ? 'All local jobs · Queue summary' : 'All local parts · Inventory summary';
  content.replaceChildren();
  textRow(content, 'Printed', new Date().toLocaleString());
  const records = step === 'queue'
    ? store.jobs.map(job => `${job.number} · ${getVehicle(store, job)?.plate ?? 'Vehicle'} · ${operationalStatus(job)}`)
    : store.parts.map(part => `${part.name} · ${part.sku || 'No SKU'} · ${partBalance(store, part.id)} ${part.unit} · ${part.active ? stockState(store, part) : 'Inactive'}`);
  for (const record of records) content.append(el('p', 'print-line', record));
  if (!records.length) content.append(el('p', undefined, step === 'queue' ? 'No local jobs recorded.' : 'No local parts recorded.'));
  sheet.hidden = false;
  sheet.classList.add('is-preview');
  window.addEventListener('afterprint', () => { sheet.hidden = true; sheet.classList.remove('is-preview'); }, { once: true });
  window.print();
}
