import type { WorkshopStore } from '../../lib/workshop/model.ts';
import { adjustStock, clearWaitingForParts, createPart, deactivatePart, issueToJob, jobPartSummary, jobShortage, markWaitingForParts, partBalance, returnFromJob, stockIn, stockState, updatePart } from '../../lib/workshop/parts.ts';
import { saveStore } from '../../lib/workshop/store.ts';
import { canSetWaitingParts, operationalStatus } from '../../lib/workshop/queue.ts';
import { onOrderQuantity } from '../../lib/workshop/procurement.ts';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const $=<T extends HTMLElement>(root:ParentNode,sel:string)=>root.querySelector<T>(sel)!;
const text=(root:HTMLElement,msg:string)=>{const x=$<HTMLElement>(root,'#parts-feedback');x.textContent=msg;x.hidden=false;};
const options=(items:{value:string;label:string}[])=>items.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('');
const at=(x:string)=>new Date(x).toLocaleString();
const names:Record<string,string>={OPENING:'Opening balance',STOCK_IN:'Stock in',ISSUE_TO_JOB:'Issue to job',RETURN_FROM_JOB:'Return from job',ADJUSTMENT_IN:'Adjustment in',ADJUSTMENT_OUT:'Adjustment out'};
export function mountPartsInventory(root:HTMLElement,store:WorkshopStore):void {
 const list=$<HTMLElement>(root,'#parts-list'),form=$<HTMLFormElement>(root,'#part-form'),movement=$<HTMLFormElement>(root,'#movement-form');
 const jobId=new URL(location.href).searchParams.get('job');
 const save=()=>{const r=saveStore(store,localStorage);text(root,r.ok?'Inventory saved in this browser.':r.message);return r.ok;};
 const render=()=>{
  const q=$<HTMLInputElement>(root,'#part-search').value.trim().toLocaleLowerCase(),filter=$<HTMLSelectElement>(root,'#part-filter').value,sort=$<HTMLSelectElement>(root,'#part-sort').value;
  let parts=store.parts.filter(p=>(filter==='inactive'?!p.active:p.active)&&(!q||[p.name,p.sku,p.category,p.location].some(x=>x.toLocaleLowerCase().includes(q)))&&(filter==='low'?stockState(store,p)==='Low Stock':filter==='out'?stockState(store,p)==='Out of Stock':true));
  parts.sort((a,b)=>sort==='stock'?partBalance(store,a.id)-partBalance(store,b.id):sort==='recent'?b.updatedAt.localeCompare(a.updatedAt):a.name.localeCompare(b.name));
  list.innerHTML=parts.length?parts.map(p=>`<article class="parts-card"><header><div><h2>${esc(p.name)}</h2><p>${esc(p.sku||'No SKU')} · ${esc(p.category||'Uncategorised')}</p></div><span class="parts-state">${p.active?stockState(store,p):'Inactive'}</span></header><p><strong>${partBalance(store,p.id)} ${esc(p.unit)}</strong> on hand · minimum ${p.minimumStock} · ${esc(p.location||'No location')}</p><p><strong>${onOrderQuantity(store,p.id)} ${esc(p.unit)}</strong> on order · not included in available stock.</p><p>${esc(p.brand)} ${p.supplier?`· Supplier note: ${esc(p.supplier)}`:''}</p><div class="parts-actions"><button type="button" data-edit="${esc(p.id)}">Edit</button><button type="button" data-history="${esc(p.id)}">Movement history</button>${p.active?`<button type="button" data-deactivate="${esc(p.id)}">Deactivate</button>`:''}</div><div data-ledger="${esc(p.id)}" hidden></div></article>`).join(''):'<p class="parts-empty">No matching parts. Create a part to start the inventory ledger.</p>';
  const jobs=store.jobs;
  const supplierSelect=form.querySelector<HTMLSelectElement>('[name="defaultSupplierId"]'),previousSupplier=supplierSelect?.value??'';if(supplierSelect){supplierSelect.innerHTML=options([{value:'',label:'No default Supplier'},...store.suppliers.filter(s=>s.active).map(s=>({value:s.supplierId,label:s.name}))]);if(store.suppliers.some(s=>s.supplierId===previousSupplier&&s.active))supplierSelect.value=previousSupplier;}
  const partSelect=movement.querySelector<HTMLSelectElement>('[name="partId"]')!,jobSelect=movement.querySelector<HTMLSelectElement>('[name="jobId"]')!,previousPart=partSelect.value,previousJob=jobSelect.value;
  partSelect.innerHTML=options(store.parts.map(p=>({value:p.id,label:`${p.name}${p.active?'':' · Inactive'} · ${p.sku||'No SKU'}`})));if(store.parts.some(p=>p.id===previousPart))partSelect.value=previousPart;
  jobSelect.innerHTML=options([{value:'',label:'Select workshop job'},...jobs.map(j=>({value:j.id,label:`${j.number} · ${j.intake.number}`}))]);if(jobs.some(j=>j.id===previousJob))jobSelect.value=previousJob;
  if(jobId)renderJob(jobId);
 };
 function renderJob(id:string){const host=$<HTMLElement>(root,'#job-parts');const job=store.jobs.find(j=>j.id===id);if(!job){host.hidden=true;return;}host.hidden=false;const summary=jobPartSummary(store,job),shortage=jobShortage(store,job),mayWait=canSetWaitingParts(job),isWaiting=operationalStatus(job)==='Waiting Parts';host.innerHTML=`<h2>Job parts · ${esc(job.number)}</h2><p>Queue status: ${esc(operationalStatus(job))}</p>${summary.length?summary.map(s=>`<p><strong>${esc(s.part.name)}</strong> · requested ${s.requested}, issued ${s.issued}, available ${s.available}, shortage ${s.shortage}</p>`).join(''):'<p>No inventory-linked Work Order parts.</p>'}<p>${shortage?`Shortage remaining: ${shortage}`:'No stock shortage remains.'}</p><p class="parts-actions"><a class="button-link" href="/tools/workshop/work-order/?job=${encodeURIComponent(job.id)}">Open Work Order</a>${shortage&&mayWait&&!job.operations?.waitingParts?'<button type="button" data-wait>Mark as Waiting Parts</button>':''}${!shortage&&isWaiting?'<button type="button" data-clear>Clear Waiting Parts</button>':''}</p><h3>Job movement history</h3><ul>${store.partMovements.filter(m=>m.jobId===id).sort((a,b)=>a.at.localeCompare(b.at)).map(m=>`<li>${esc(at(m.at))} · ${esc(names[m.type])} · ${m.quantity} ${esc(store.parts.find(p=>p.id===m.partId)?.unit||'')} · ${esc(m.note||m.reference||'')}</li>`).join('')||'<li>No inventory movements for this job.</li>'}</ul>`;
  host.querySelector('[data-wait]')?.addEventListener('click',()=>{if(markWaitingForParts(store,id)&&save())render();});host.querySelector('[data-clear]')?.addEventListener('click',()=>{if(clearWaitingForParts(store,id)&&save())render();});
 }
 root.querySelectorAll('#part-search,#part-filter,#part-sort').forEach(x=>x.addEventListener('input',render));root.querySelectorAll('#part-filter,#part-sort').forEach(x=>x.addEventListener('change',render));
  form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),id=String(fd.get('id')||''),defaultSupplierId=String(fd.get('defaultSupplierId')||'')||undefined;if(defaultSupplierId&&!store.suppliers.some(s=>s.supplierId===defaultSupplierId&&s.active)){text(root,'Choose an active Supplier as the default.');return;}const data={sku:String(fd.get('sku')||''),name:String(fd.get('name')||''),category:String(fd.get('category')||''),brand:String(fd.get('brand')||''),unit:String(fd.get('unit')||'each'),location:String(fd.get('location')||''),supplier:String(fd.get('supplier')||''),minimumStock:Number(fd.get('minimumStock')||0),barcode:String(fd.get('barcode')||''),compatibility:String(fd.get('compatibility')||''),active:id?(store.parts.find(p=>p.id===id)?.active??false):true,defaultSupplierId};const res=id?updatePart(store,id,data):createPart(store,id?data:{...data,defaultSupplierId},Number(fd.get('opening')||0));if(!res.ok){text(root,res.message);return;}form.reset();form.querySelector<HTMLInputElement>('[name="id"]')!.value='';$<HTMLElement>(root,'#opening-wrap').hidden=false;text(root,'Part saved.');save();render();});
 movement.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(movement),type=String(fd.get('type')),partId=String(fd.get('partId')),qty=Number(fd.get('quantity')),note=String(fd.get('note')||''),extra={note,reference:String(fd.get('reference')||''),supplier:String(fd.get('supplier')||'')};let res;
  if(type==='STOCK_IN')res=stockIn(store,partId,qty,{...extra,unitCost:fd.get('unitCost')?Number(fd.get('unitCost')):undefined});else if(type==='ISSUE_TO_JOB')res=issueToJob(store,partId,String(fd.get('jobId')||''),qty,extra);else if(type==='RETURN_FROM_JOB')res=returnFromJob(store,partId,String(fd.get('jobId')||''),qty,extra);else res=adjustStock(store,partId,type==='ADJUSTMENT_IN'?'in':'out',qty,note);
  if(!res.ok){text(root,res.message);return;}movement.reset();text(root,`${names[type]} recorded.`);save();render();});
 list.addEventListener('click',e=>{const target=e.target as HTMLElement,p=store.parts.find(x=>x.id===target.dataset.edit||x.id===target.dataset.deactivate||x.id===target.dataset.history);if(!p)return;if(target.dataset.edit){for(const [k,v]of Object.entries(p)){const input=form.elements.namedItem(k) as HTMLInputElement|null;if(input)input.value=String(v??'');}form.querySelector<HTMLInputElement>('[name="id"]')!.value=p.id;$<HTMLElement>(root,'#opening-wrap').hidden=true;form.scrollIntoView({behavior:'smooth',block:'start'});}if(target.dataset.deactivate){deactivatePart(store,p.id);save();render();}if(target.dataset.history){const panel=list.querySelector<HTMLElement>(`[data-ledger="${CSS.escape(p.id)}"]`)!;panel.hidden=!panel.hidden;panel.innerHTML=`<ol class="parts-ledger">${store.partMovements.filter(m=>m.partId===p.id).sort((a,b)=>a.at.localeCompare(b.at)).map(m=>`<li><time>${esc(at(m.at))}</time><strong>${esc(names[m.type])} · ${m.type==='ISSUE_TO_JOB'||m.type==='ADJUSTMENT_OUT'?'−':'+'}${m.quantity} ${esc(p.unit)}</strong><span>${m.jobId?`Job ${esc(store.jobs.find(j=>j.id===m.jobId)?.number||m.jobId)}`:''} ${esc([m.supplier,m.reference,m.note].filter(Boolean).join(' · '))}</span></li>`).join('')||'<li>No movements recorded.</li>'}</ol>`;}});
 render();
}
