import type { PurchaseNeed, PurchaseOrder, PurchaseOrderLine, WorkshopStore } from '../../lib/workshop/model.ts';
import { cancelPurchaseNeed, cancelPurchaseOrder, closePurchaseOrder, commitGoodsReceipt, createPurchaseNeed, createPurchaseOrderDraft, createSupplier, defaultReceiptAllocations, issuePurchaseOrder, needProgress, needWorkOrderMismatch, poLineProgress, poProgress, purchaseLineTotal, purchaseOrderTotal, shortageSuggestions, supplierFor, updateDraftPO, updateSupplier } from '../../lib/workshop/procurement.ts';
import { partBalance } from '../../lib/workshop/parts.ts';
import { saveStore } from '../../lib/workshop/store.ts';
import { operationalStatus } from '../../lib/workshop/queue.ts';

const esc=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(x:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(x);
const $=<T extends HTMLElement>(root:ParentNode,s:string)=>root.querySelector<T>(s)!;
const msg=(root:HTMLElement,s:string)=>{const n=$<HTMLElement>(root,'#procurement-feedback');n.textContent=s;n.hidden=!s;};
const num=(root:ParentNode,name:string)=>Number(root.querySelector<HTMLInputElement>(`[name="${CSS.escape(name)}"]`)?.value??'0');
const field=(parent:ParentNode,name:string)=>parent.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(`[name="${CSS.escape(name)}"]`)?.value.trim()??'';
const label=(s:string,n:string,v='')=>`<label>${esc(s)}<input name="${esc(n)}" value="${esc(v)}"></label>`;
const dateLabel=(s:string,n:string,v='')=>`<label>${esc(s)}<input type="date" name="${esc(n)}" value="${esc(v)}"></label>`;
const quantityLabel=(s:string,n:string,v:number)=>`<label>${esc(s)}<input type="number" min="0" step="any" name="${esc(n)}" value="${esc(v)}"></label>`;
const moneyLabel=(s:string,n:string,v='')=>`<label>${esc(s)} (Rp)<input type="number" min="0" step="1" name="${esc(n)}" value="${esc(v)}"></label>`;
  const textArea=(s:string,n:string,v='')=>`<label>${esc(s)}<textarea name="${esc(n)}">${esc(v)}</textarea></label>`;

export function mountProcurement(root:HTMLElement,store:WorkshopStore){
  const host=$<HTMLElement>(root,'#procurement-root');
  let lastSaved=structuredClone(store);
  const persist=(success:string)=>{try{const res=saveStore(store,localStorage);if(res.ok)lastSaved=structuredClone(store);else Object.assign(store,structuredClone(lastSaved));msg(root,res.ok?success:res.message);return res.ok;}catch{Object.assign(store,structuredClone(lastSaved));msg(root,'Browser storage is unavailable. Your latest change was not saved.');return false;}};
  const needRows=(filter:(n:PurchaseNeed)=>boolean)=>store.purchaseNeeds.filter(filter);
  const render=()=>{
    const suggestions=shortageSuggestions(store);const openNeeds=needRows(n=>!n.cancelledAt&&needProgress(store,n).open>1e-8);
    const partOptions=store.parts.filter(p=>p.active).map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.sku||'No SKU')} · ${partBalance(store,p.id)} ${esc(p.unit)}</option>`).join('');
    host.innerHTML=`
      <section class="workshop-card procurement-section" aria-labelledby="proc-shortages"><h2 id="proc-shortages">Shortage suggestions</h2><p>Suggestions are derived from active Jobs. A Purchase Need is saved only when you confirm it.</p>${suggestions.length?suggestions.map(s=>`<article class="proc-card"><h3>${esc(s.part.name)} · ${esc(s.part.sku||'No SKU')}</h3><p><a href="/tools/workshop/work-order/?job=${encodeURIComponent(s.job.id)}">Job ${esc(s.job.number)} · ${esc(store.vehicles.find(v=>v.id===s.job.vehicleId)?.plate||'')}</a> · ${esc(operationalStatus(s.job))}${operationalStatus(s.job)==='Cancelled'?' (cancelled)':''}</p><p>Requested ${s.requested} · issued ${s.issued} · on hand ${s.available} ${esc(s.part.unit)} · shortage ${s.shortage} · existing procurement coverage ${s.covered}</p>${s.suggested>0?`<button type="button" data-action="shortage-need" data-job="${esc(s.job.id)}" data-part="${esc(s.part.id)}" data-qty="${s.suggested}">Create Purchase Need · ${s.suggested} ${esc(s.part.unit)}</button>`:''}</article>`).join(''):'<p>No uncovered active Job shortages.</p>'}</section>
      <section class="workshop-card procurement-section" aria-labelledby="proc-needs"><h2 id="proc-needs">Purchase Needs</h2><form id="need-form" class="proc-form"><label>Source<select name="source"><option value="REPLENISHMENT">Replenishment</option><option value="MANUAL">Manual</option></select></label><label>Active Part<select name="partId" required><option value="">Choose a Part</option>${partOptions}</select></label>${quantityLabel('Quantity','quantity',1)}${dateLabel('Required by (optional)','requiredBy')}${textArea('Reason','reason')}<button type="submit">Create Purchase Need</button></form><div class="proc-list">${store.purchaseNeeds.length?store.purchaseNeeds.map(n=>{const p=needProgress(store,n),job=n.jobId&&store.jobs.find(j=>j.id===n.jobId),mismatch=needWorkOrderMismatch(store,n);return `<article class="proc-card"><h3>${esc(n.partNameSnapshot)} · ${esc(n.skuSnapshot||'No SKU')} <span class="proc-status">${p.state}</span></h3><p>${esc(n.source)} · requested ${n.requestedQuantity} ${esc(n.unitSnapshot)} · received ${p.received} · ordered outstanding ${p.ordered} · draft allocated ${p.draftAllocated} · open ${p.open}</p>${job?`<p><a href="/tools/workshop/work-order/?job=${encodeURIComponent(job.id)}">Job ${esc(job.number)} · ${esc(store.vehicles.find(v=>v.id===job.vehicleId)?.plate||'')}</a> · ${esc(operationalStatus(job))}${operationalStatus(job)==='Cancelled'?' — originating Job is cancelled; procurement remains unchanged.':''}</p>`:''}${n.requiredBy?`<p>Required by ${esc(n.requiredBy)}</p>`:''}${n.reason?`<p>${esc(n.reason)}</p>`:''}${mismatch!==null?`<p class="proc-warning" role="status">Work Order quantity changed. Current request is ${mismatch} ${esc(n.unitSnapshot)}; this Need remains ${n.requestedQuantity}. Review, cancel, or create an additional Need.</p>`:''}${!n.cancelledAt&&p.received<n.requestedQuantity?`<button type="button" class="button-secondary" data-action="cancel-need" data-id="${esc(n.needId)}">Cancel Need</button>`:''}</article>`;}).join(''):'<p>No Purchase Needs yet.</p>'}</div><fieldset class="proc-select"><legend>Select open Needs for a Draft PO</legend>${openNeeds.length?openNeeds.map(n=>`<label><input type="checkbox" data-select-need="${esc(n.needId)}"> ${esc(n.partNameSnapshot)} · ${needProgress(store,n).open} ${esc(n.unitSnapshot)} · ${esc(n.source)}</label>`).join(''):'<p>No open Need quantity.</p>'}<button type="button" data-action="create-po">Create Draft PO from selected Needs</button></fieldset></section>
      <section class="workshop-card procurement-section" aria-labelledby="proc-suppliers"><h2 id="proc-suppliers">Suppliers</h2><form id="supplier-form" class="proc-form"><input type="hidden" name="supplierId">${label('Name *','name')}${label('Phone','phone')}${label('Email','email')}${label('Contact person','contactPerson')}${label('Address','address')}${textArea('Notes','notes')}<button type="submit">Save Supplier</button><button type="button" class="button-secondary" data-action="supplier-reset">Clear form</button></form><div class="proc-list">${store.suppliers.length?store.suppliers.map(s=>{const orders=store.purchaseOrders.filter(p=>p.supplierId===s.supplierId).length,defaultParts=store.parts.filter(p=>p.defaultSupplierId===s.supplierId).length;return `<article class="proc-card"><h3>${esc(s.name)} <span class="proc-status">${s.active?'Active':'Inactive'}</span></h3><p>${esc([s.contactPerson,s.phone,s.email,s.address].filter(Boolean).join(' · ')||'No contact details')}</p><p>Historical Purchase Orders ${orders} · Parts using as default suggestion ${defaultParts}</p>${s.notes?`<p>${esc(s.notes)}</p>`:''}<button type="button" class="button-secondary" data-action="edit-supplier" data-id="${esc(s.supplierId)}">Edit</button><button type="button" class="button-secondary" data-action="${s.active?'deactivate-supplier':'activate-supplier'}" data-id="${esc(s.supplierId)}">${s.active?'Deactivate':'Reactivate'}</button></article>`;}).join(''):'<p>No Suppliers saved.</p>'}</div></section>
      <section class="workshop-card procurement-section" aria-labelledby="proc-pos"><h2 id="proc-pos">Purchase Orders</h2>${store.purchaseOrders.length?store.purchaseOrders.map(po=>renderPO(store,po)).join(''):'<p>No Purchase Orders saved.</p>'}</section>
      <section class="workshop-card procurement-section" aria-labelledby="proc-receipts"><h2 id="proc-receipts">Goods Receipt history</h2>${store.goodsReceipts.length?[...store.goodsReceipts].reverse().map(r=>`<article class="proc-card"><h3>${esc(r.receiptNumber)} · ${esc(r.receivedAt)}</h3><p>PO ${esc(store.purchaseOrders.find(p=>p.poId===r.poId)?.poNumber||'Draft/unknown')}</p>${r.supplierDeliveryNote?`<p>Delivery note ${esc(r.supplierDeliveryNote)}</p>`:''}${r.lines.map(l=>`<p>${esc(l.partNameSnapshot)} · delivered ${l.deliveredQuantity}, accepted ${l.acceptedQuantity}, rejected ${l.rejectedQuantity} ${esc(l.unitSnapshot)}${l.actualUnitCost!==undefined?` · actual cost ${money(l.actualUnitCost)}`:''}${l.rejectionNote?` · ${esc(l.rejectionNote)}`:''}</p>`).join('')}</article>`).join(''):'<p>No Goods Receipts saved.</p>'}</section>
      <section id="procurement-print" hidden aria-label="Printable Purchase Order"></section>`;
  };
  const renderPO=(s:WorkshopStore,po:PurchaseOrder)=>{
    const prog=poProgress(s,po);const receipts=s.goodsReceipts.filter(r=>r.poId===po.poId);
    const selectedSupplierOptions=s.suppliers.filter(x=>x.active).map(x=>`<option value="${esc(x.supplierId)}" ${po.supplierId===x.supplierId?'selected':''}>${esc(x.name)}</option>`).join('');
    const header=`<div class="proc-po-heading"><h3>${esc(po.poNumber||'Draft Purchase Order')} <span class="proc-status">${esc(po.status)}</span></h3><p>${esc(po.supplierSnapshot?.name||supplierFor(s,po.supplierId||'')?.name||'Supplier not selected')} · ${esc(prog)} · ${po.expectedDate?`Expected ${esc(po.expectedDate)}`:'No expected date'}</p></div>`;
    if(po.status==='Draft')return `<article class="proc-card proc-po">${header}<form class="proc-form proc-po-form" data-po="${esc(po.poId)}"><label>Supplier<select name="supplierId"><option value="">Choose active Supplier</option>${selectedSupplierOptions}</select></label>${dateLabel('Order date','orderDate',po.orderDate)}${dateLabel('Expected date','expectedDate',po.expectedDate||'')}${textArea('PO notes','notes',po.notes||'')}<div class="proc-lines">${po.lines.map(l=>`<div class="proc-line"><h4>${esc(l.partNameSnapshot)} · ${esc(l.skuSnapshot||'No SKU')} · ${esc(l.unitSnapshot)}</h4><p>Ordered quantity is the sum of source allocations.</p>${l.sourceAllocations.map(a=>{const n=s.purchaseNeeds.find(x=>x.needId===a.needId);return n?quantityLabel(`Need ${n.source}${n.jobId?` · Job ${s.jobs.find(j=>j.id===n.jobId)?.number||''}`:''} · allocation (${n.unitSnapshot})`,`alloc-${l.lineId}-${a.needId}`,a.quantity):'';}).join('')}${moneyLabel('Agreed supplier purchase cost per unit',`cost-${l.lineId}`,String(l.agreedUnitCost))}<p>Line total: ${money(purchaseLineTotal(l.orderedQuantity,l.agreedUnitCost)??0)}</p></div>`).join('')||'<p>No lines. Add an open Need below.</p>'}</div><p><strong>PO total: ${money(purchaseOrderTotal(po)??0)}</strong></p><button type="submit">Save Draft PO</button></form><form class="proc-form proc-add-needs" data-add-po="${esc(po.poId)}"><fieldset><legend>Add open Needs to this Draft</legend>${needRows(n=>!n.cancelledAt&&needProgress(s,n).open>1e-8&&!po.lines.some(l=>l.sourceAllocations.some(a=>a.needId===n.needId))).map(n=>`<label><input type="checkbox" name="addNeed" value="${esc(n.needId)}"> ${esc(n.partNameSnapshot)} · ${needProgress(s,n).open} ${esc(n.unitSnapshot)}</label>`).join('')||'<p>No other open Need.</p>'}<button type="submit">Add selected Needs</button></fieldset></form><div class="proc-actions"><button type="button" data-action="issue-po" data-id="${esc(po.poId)}">Issue PO</button><button type="button" class="button-secondary" data-action="print-po" data-id="${esc(po.poId)}">Print / Save as PDF</button></div></article>`;
    const receiving=po.status==='Issued'?`<form class="proc-form proc-receive-form" data-receive-po="${esc(po.poId)}"><h4>Record a delivery</h4>${dateLabel('Received date','receivedAt',new Date().toISOString().slice(0,10))}${label('Supplier delivery note','supplierDeliveryNote')}${label('Supplier invoice reference (traceability only)','supplierInvoiceReference')}${label('Received by','receivedBy')}${textArea('Receipt notes','notes')}${po.lines.filter(l=>poLineProgress(s,l).remaining>1e-8).map(l=>{const remaining=poLineProgress(s,l).remaining;const allocations=defaultReceiptAllocations(s,po,l,remaining);return `<fieldset class="proc-line"><legend>${esc(l.partNameSnapshot)} · ordered ${l.orderedQuantity} · accepted ${poLineProgress(s,l).accepted} · remaining ${remaining} ${esc(l.unitSnapshot)}</legend>${quantityLabel('Delivered now',`delivered-${l.lineId}`,remaining)}${quantityLabel('Accepted now',`accepted-${l.lineId}`,remaining)}${quantityLabel('Rejected now',`rejected-${l.lineId}`,0)}${moneyLabel('Actual received unit cost (optional)',`actual-${l.lineId}`)}<p>PO agreed unit cost: ${money(l.agreedUnitCost)}. A different actual cost requires confirmation.</p>${l.sourceAllocations.map(a=>{const n=s.purchaseNeeds.find(x=>x.needId===a.needId);const defaultQty=allocations.find(x=>x.needId===a.needId)?.quantity??0;return quantityLabel(`Accepted allocation · Need ${n?.partNameSnapshot||''}${n?.jobId?` · Job ${s.jobs.find(j=>j.id===n.jobId)?.number||''}`:''}`,`recvalloc-${l.lineId}-${a.needId}`,defaultQty);}).join('')}${label('Rejected quantity reason',`reject-note-${l.lineId}`)}</fieldset>`;}).join('')}<button type="submit">Save Goods Receipt + Stock In</button></form>`:'';
    return `<article class="proc-card proc-po">${header}<p>Supplier snapshot: ${esc(po.supplierSnapshot?.name||'—')} · ${esc([po.supplierSnapshot?.contactPerson,po.supplierSnapshot?.phone,po.supplierSnapshot?.email,po.supplierSnapshot?.address].filter(Boolean).join(' · '))}</p><p>Order date ${esc(po.orderDate)}${po.poNumber?` · ${esc(po.poNumber)}`:''}</p><ul class="proc-lines">${po.lines.map(l=>{const p=poLineProgress(s,l);return `<li><strong>${esc(l.partNameSnapshot)}</strong> · ordered ${l.orderedQuantity}, accepted ${p.accepted}, outstanding ${p.remaining} ${esc(l.unitSnapshot)} · ${money(l.agreedUnitCost)} / unit · ${p.state}<ul>${l.sourceAllocations.map(a=>{const n=s.purchaseNeeds.find(x=>x.needId===a.needId);return `<li>Need ${esc(n?.partNameSnapshot||a.needId)}${n?.jobId?` · Job ${esc(s.jobs.find(j=>j.id===n.jobId)?.number||'')}`:''}: ${a.quantity} · received ${s.goodsReceipts.filter(r=>r.poId===po.poId).flatMap(r=>r.lines.filter(x=>x.poLineId===l.lineId)).flatMap(x=>x.acceptedNeedAllocations.filter(x=>x.needId===a.needId)).reduce((n,x)=>n+x.quantity,0)}</li>`;}).join('')}</ul></li>`;}).join('')}</ul><p><strong>Total ${money(purchaseOrderTotal(po)??0)}</strong> · Receipt progress: ${esc(prog)}</p>${receipts.map(r=>`<p>Receipt ${esc(r.receiptNumber)} · ${esc(r.receivedAt)}${r.supplierDeliveryNote?` · delivery note ${esc(r.supplierDeliveryNote)}`:''}</p>`).join('')}${receiving}${po.status==='Issued'?`<div class="proc-actions"><button type="button" class="button-secondary" data-action="cancel-po" data-id="${esc(po.poId)}">Cancel PO</button><button type="button" class="button-secondary" data-action="close-po" data-id="${esc(po.poId)}">Close PO</button><button type="button" class="button-secondary" data-action="print-po" data-id="${esc(po.poId)}">Print / Save as PDF</button></div>`:''}${po.status==='Cancelled'||po.status==='Closed'?`<p>${po.status==='Cancelled'?`Cancellation reason: ${esc(po.cancelReason||'')}`:`Close reason: ${esc(po.closeReason||'Fully received')}`}</p>`:''}</article>`;
  };
  render();
  host.addEventListener('submit',e=>{const form=e.target;if(!(form instanceof HTMLFormElement))return;e.preventDefault();
    if(form.id==='supplier-form'){const supplierId=field(form,'supplierId'),data={name:field(form,'name'),phone:field(form,'phone')||undefined,email:field(form,'email')||undefined,contactPerson:field(form,'contactPerson')||undefined,address:field(form,'address')||undefined,notes:field(form,'notes')||undefined,active:true};const r=supplierId?updateSupplier(store,supplierId,data):createSupplier(store,data);if(!r.ok){msg(root,r.message);return;}persist('Supplier saved locally.');render();return;}
    if(form.id==='need-form'){const partId=field(form,'partId'),source=field(form,'source') as 'MANUAL'|'REPLENISHMENT',r=createPurchaseNeed(store,{source,partId,quantity:num(form,'quantity'),requiredBy:field(form,'requiredBy')||undefined,reason:field(form,'reason')||undefined});if(!r.ok){msg(root,r.message);return;}persist('Purchase Need saved locally.');render();return;}
    const poId=form.dataset.po;if(poId){const po=store.purchaseOrders.find(x=>x.poId===poId)!;const lines:PurchaseOrderLine[]=[];for(const line of po.lines){const sourceAllocations=line.sourceAllocations.map(a=>({needId:a.needId,quantity:num(form,`alloc-${line.lineId}-${a.needId}`)})).filter(a=>a.quantity>0);if(!sourceAllocations.length)continue;lines.push({...line,orderedQuantity:sourceAllocations.reduce((n,a)=>n+a.quantity,0),agreedUnitCost:num(form,`cost-${line.lineId}`),sourceAllocations});}const r=updateDraftPO(store,poId,{supplierId:field(form,'supplierId')||undefined,orderDate:field(form,'orderDate'),expectedDate:field(form,'expectedDate')||undefined,notes:field(form,'notes'),lines});if(!r.ok){msg(root,r.message);return;}persist('Draft Purchase Order saved.');render();return;}
    const addPoId=form.dataset.addPo;if(addPoId){const ids=[...form.querySelectorAll<HTMLInputElement>('input[name="addNeed"]:checked')].map(x=>x.value);if(!ids.length){msg(root,'Select at least one open Need to add.');return;}const po=store.purchaseOrders.find(x=>x.poId===addPoId)!;const additions:PurchaseOrderLine[]=[];for(const needId of ids){const n=store.purchaseNeeds.find(x=>x.needId===needId)!;const part=store.parts.find(x=>x.id===n.partId)!;const target=po.lines.find(l=>l.partId===part.id)||additions.find(l=>l.partId===part.id);if(target){const q=needProgress(store,n).open;target.sourceAllocations.push({needId,quantity:q});target.orderedQuantity+=q;}else additions.push({lineId:`po-line_${crypto.randomUUID()}`,...{partId:part.id,partNameSnapshot:part.name,skuSnapshot:part.sku,unitSnapshot:part.unit},orderedQuantity:needProgress(store,n).open,agreedUnitCost:0,sourceAllocations:[{needId,quantity:needProgress(store,n).open}]});}const r=updateDraftPO(store,addPoId,{lines:[...po.lines,...additions]});if(!r.ok){msg(root,r.message);return;}persist('Selected Needs added to Draft PO.');render();return;}
    const receivePoId=form.dataset.receivePo;if(receivePoId){const po=store.purchaseOrders.find(x=>x.poId===receivePoId)!;const inputLines=po.lines.filter(l=>poLineProgress(store,l).remaining>1e-8).map(l=>({poLineId:l.lineId,deliveredQuantity:num(form,`delivered-${l.lineId}`),acceptedQuantity:num(form,`accepted-${l.lineId}`),rejectedQuantity:num(form,`rejected-${l.lineId}`),actualUnitCost:field(form,`actual-${l.lineId}`)===''?undefined:num(form,`actual-${l.lineId}`),rejectionNote:field(form,`reject-note-${l.lineId}`)||undefined,acceptedNeedAllocations:l.sourceAllocations.map(a=>({needId:a.needId,quantity:num(form,`recvalloc-${l.lineId}-${a.needId}`)})).filter(a=>a.quantity>0)})).filter(l=>l.deliveredQuantity>0);if(!inputLines.length){msg(root,'Enter a delivered quantity for at least one PO line.');return;}const before=structuredClone(store);const receiptId=`receipt_${crypto.randomUUID()}`;let r=commitGoodsReceipt(store,receivePoId,{receiptId,receivedAt:field(form,'receivedAt'),supplierDeliveryNote:field(form,'supplierDeliveryNote'),supplierInvoiceReference:field(form,'supplierInvoiceReference'),receivedBy:field(form,'receivedBy'),notes:field(form,'notes'),lines:inputLines});if(!r.ok&&r.message.includes('variance')&&confirm(`${r.message}\n\nPO and actual received cost differ. Confirm this actual purchase cost?`))r=commitGoodsReceipt(store,receivePoId,{receiptId,receivedAt:field(form,'receivedAt'),supplierDeliveryNote:field(form,'supplierDeliveryNote'),supplierInvoiceReference:field(form,'supplierInvoiceReference'),receivedBy:field(form,'receivedBy'),notes:field(form,'notes'),confirmCostVariance:true,lines:inputLines});if(!r.ok){Object.assign(store,before);msg(root,r.message);return;}const saved=persist(`Goods Receipt ${r.value.receiptNumber} and Stock In saved.`);if(!saved)Object.assign(store,before);render();return;}
  });
  host.addEventListener('input',e=>{const target=e.target;if(!(target instanceof HTMLInputElement)||!target.name.startsWith('accepted-'))return;const form=target.closest<HTMLFormElement>('form[data-receive-po]');if(!form)return;const po=store.purchaseOrders.find(x=>x.poId===form.dataset.receivePo);const line=po?.lines.find(x=>target.name===`accepted-${x.lineId}`);if(!po||!line)return;const suggestions=defaultReceiptAllocations(store,po,line,Math.max(0,Number(target.value)||0));for(const a of line.sourceAllocations){const input=form.querySelector<HTMLInputElement>(`[name="recvalloc-${CSS.escape(line.lineId)}-${CSS.escape(a.needId)}"]`);if(input)input.value=String(suggestions.find(x=>x.needId===a.needId)?.quantity??0);}});
  host.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]');if(!b)return;const action=b.dataset.action!,id=b.dataset.id||'';
    if(action==='shortage-need'){const s=shortageSuggestions(store).find(x=>x.job.id===b.dataset.job&&x.part.id===b.dataset.part);if(!s)return;const r=createPurchaseNeed(store,{source:'JOB_SHORTAGE',jobId:s.job.id,partId:s.part.id,quantity:s.suggested,reason:`Work Order shortage for Job ${s.job.number}`});if(!r.ok)msg(root,r.message);else{persist('Purchase Need confirmed and saved.');render();}}
    if(action==='create-po'){const ids=[...host.querySelectorAll<HTMLInputElement>('[data-select-need]:checked')].map(x=>x.dataset.selectNeed!);const defaults=[...new Set(ids.map(x=>store.parts.find(p=>p.id===store.purchaseNeeds.find(n=>n.needId===x)?.partId)?.defaultSupplierId).filter(Boolean))];const r=createPurchaseOrderDraft(store,ids,defaults.length===1?defaults[0]:undefined);if(!r.ok)msg(root,r.message);else{persist('Draft Purchase Order created.');render();}}
    if(action==='cancel-need'){const reason=prompt('Reason for cancelling this Purchase Need:');if(reason===null)return;const r=cancelPurchaseNeed(store,id,reason);if(!r.ok)msg(root,r.message);else{persist('Purchase Need cancelled; procurement history retained.');render();}}
    if(action==='edit-supplier'){const s=store.suppliers.find(x=>x.supplierId===id);if(!s)return;const form=$<HTMLFormElement>(host,'#supplier-form');for(const k of ['supplierId','name','phone','email','contactPerson','address','notes']){const x=form.elements.namedItem(k) as HTMLInputElement|HTMLTextAreaElement|null;if(x)x.value=String(s[k as keyof typeof s]??'');}const save=form.querySelector<HTMLButtonElement>('button[type="submit"]');if(save)save.textContent='Update Supplier';form.scrollIntoView({behavior:'smooth',block:'center'});}
    if(action==='supplier-reset'){const form=$<HTMLFormElement>(host,'#supplier-form');form.reset();(form.elements.namedItem('supplierId') as HTMLInputElement).value='';const save=form.querySelector<HTMLButtonElement>('button[type="submit"]');if(save)save.textContent='Save Supplier';}
    if(action==='deactivate-supplier'){const r=updateSupplier(store,id,{active:false});if(!r.ok)msg(root,r.message);else{persist('Supplier deactivated. Historical PO snapshots remain.');render();}}
    if(action==='activate-supplier'){const r=updateSupplier(store,id,{active:true});if(!r.ok)msg(root,r.message);else{persist('Supplier reactivated for new Purchase Orders.');render();}}
    if(action==='issue-po'){const r=issuePurchaseOrder(store,id);if(!r.ok)msg(root,r.message);else{persist(`Purchase Order ${r.value.poNumber} issued. Inventory is unchanged.`);render();}}
    if(action==='cancel-po'){const reason=prompt('Reason for cancelling this Purchase Order:');if(reason===null)return;const r=cancelPurchaseOrder(store,id,reason);if(!r.ok)msg(root,r.message);else{persist('Purchase Order cancelled; received stock remains in the ledger.');render();}}
    if(action==='close-po'){const reason=prompt('Reason for closing this Purchase Order (required if quantity remains outstanding):')??'';const r=closePurchaseOrder(store,id,reason);if(!r.ok)msg(root,r.message);else{persist('Purchase Order closed; outstanding Need quantity is open again.');render();}}
    if(action==='print-po'){printPO(store,id);}
  });
  function printPO(s:WorkshopStore,poId:string){const po=s.purchaseOrders.find(x=>x.poId===poId);if(!po)return;const target=$<HTMLElement>(host,'#procurement-print');const supplier=po.supplierSnapshot||supplierFor(s,po.supplierId||'');target.innerHTML=`<h1>Purchase Order ${esc(po.poNumber||'Draft')}</h1><p>Order date ${esc(po.orderDate)}${po.expectedDate?` · Expected ${esc(po.expectedDate)}`:''}</p><section><h2>Supplier</h2><p>${esc(supplier?.name||'—')}<br>${esc(supplier?.contactPerson||'')} ${esc(supplier?.phone||'')}<br>${esc(supplier?.email||'')}<br>${esc(supplier?.address||'')}</p></section><table><thead><tr><th>Part / SKU</th><th>Need / Job allocation</th><th>Qty</th><th>Unit</th><th>Agreed unit cost</th><th>Total</th></tr></thead><tbody>${po.lines.map(l=>`<tr><td>${esc(l.partNameSnapshot)} · ${esc(l.skuSnapshot)}</td><td>${l.sourceAllocations.map(a=>{const n=s.purchaseNeeds.find(x=>x.needId===a.needId),job=n?.jobId?s.jobs.find(x=>x.id===n.jobId):undefined;return `${esc(n?.source||'Need')}${job?` · Job ${esc(job.number)}`:''}: ${a.quantity} ${esc(l.unitSnapshot)}`;}).join('<br>')}</td><td>${l.orderedQuantity}</td><td>${esc(l.unitSnapshot)}</td><td>${money(l.agreedUnitCost)}</td><td>${money(purchaseLineTotal(l.orderedQuantity,l.agreedUnitCost)??0)}</td></tr>`).join('')}</tbody></table><p><strong>Total ${money(purchaseOrderTotal(po)??0)}</strong></p><p>${esc(po.notes||'')}</p>`;document.body.classList.add('print-procurement');window.print();window.setTimeout(()=>{document.body.classList.remove('print-procurement');target.hidden=true;},1000);target.hidden=false;}
}
