import type { NextService, WorkshopStore, WorkshopWarranty } from '../../lib/workshop/model.ts';
import { loadStore, saveStore } from '../../lib/workshop/store.ts';
import { completedService, createWarranty, createWarrantyClaim, latestKnownOdometer, localDate, nextServiceForVehicle, nextServiceStatus, saveNextService, serviceHistory, vehicleHistorySearch, warrantyStatusForVehicle } from '../../lib/workshop/history.ts';

const $=<T extends HTMLElement>(root:ParentNode,selector:string)=>root.querySelector<T>(selector)!;
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat('en',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):'Not recorded';
const number=(value:number|null)=>value===null?'Not recorded':new Intl.NumberFormat('en').format(value);
function load(){try{return loadStore(window.localStorage);}catch{return loadStore({getItem:()=>{throw new Error('Storage unavailable');},setItem:()=>{throw new Error('Storage unavailable');}});}}
export function mountServiceHistory(root:HTMLElement):void{
 const search=$<HTMLInputElement>(root,'#history-search'),picker=$<HTMLSelectElement>(root,'#history-vehicle'),content=$<HTMLElement>(root,'#history-content'),feedback=$<HTMLElement>(root,'#history-feedback');let {store}=load(),selectedId='';
 if(!store.warranties)store.warranties=[];if(!store.warrantyClaims)store.warrantyClaims=[];if(!store.nextServices)store.nextServices=[];
 const message=(text:string,error=false)=>{feedback.textContent=text;feedback.hidden=!text;feedback.dataset.kind=error?'error':'success';};
 const persistMutation=<T,>(form:HTMLFormElement,mutate:()=>{ok:boolean;value?:T;message?:string})=>{const before=structuredClone(store),result=mutate();if(!result.ok){formError(form,result.message??'The change could not be saved.');return null;}const saved=saveStore(store,window.localStorage);if(!saved.ok){store=before;formError(form,saved.message);return null;}message('Service history information saved in this browser.');return result.value??true;};
 const choices=()=>vehicleHistorySearch(store,search.value);
 const render=()=>{
  const vehicles=choices();picker.replaceChildren(new Option('Choose a vehicle',''),...vehicles.map(v=>new Option(`${v.plate} · ${[v.make,v.model].filter(Boolean).join(' ')||v.type}`,v.id)));
  if(vehicles.some(v=>v.id===selectedId))picker.value=selectedId;else{selectedId='';picker.value='';}
  if(!selectedId){content.replaceChildren();content.innerHTML=vehicles.length?'<section class="workshop-card"><h2>Select a vehicle</h2><p>Choose one saved vehicle to view its completed service timeline.</p></section>':'<section class="workshop-card"><h2>No completed service history found</h2><p>Completed Workshop Jobs will appear here automatically. Incomplete and cancelled jobs are excluded.</p><a class="button-link" href="/tools/workshop/vehicle-intake/">Start Vehicle Intake →</a></section>';return;}
  const vehicle=store.vehicles.find(v=>v.id===selectedId);if(!vehicle){selectedId='';render();return;}
  const history=serviceHistory(store,vehicle.id),odometer=latestKnownOdometer(store,vehicle.id),warranties=store.warranties.filter(w=>w.vehicleId===vehicle.id),activeCount=warranties.filter(w=>warrantyStatusForVehicle(store,w)==='Active').length,next=nextServiceForVehicle(store,vehicle.id),nextStatus=next?nextServiceStatus(next,odometer):null;
  content.innerHTML=`<section class="workshop-card vehicle-history-summary"><h2>Vehicle summary</h2><dl class="history-summary-grid"><div><dt>Plate</dt><dd>${esc(vehicle.plate)}</dd></div><div><dt>Vehicle</dt><dd>${esc([vehicle.make,vehicle.model].filter(Boolean).join(' ')||vehicle.type)}</dd></div><div><dt>Year</dt><dd>${esc(vehicle.year??'Not recorded')}</dd></div><div><dt>Last known odometer</dt><dd>${number(odometer)} km</dd></div><div><dt>Completed services</dt><dd>${history.length}</dd></div><div><dt>Last service</dt><dd>${dateLabel(history[0]?.serviceDate??null)}</dd></div><div><dt>Active warranties</dt><dd>${activeCount}</dd></div><div><dt>Next service</dt><dd>${next?`${esc(nextStatus)} · ${esc(next.recommendation||'Recommendation recorded')}`:'No recommendation recorded'}</dd></div></dl><p>Odometer is the latest known local reading, not a live vehicle reading.</p><div class="button-row"><button id="print-service-history" type="button">Print / Save vehicle history</button><button id="clear-history-selection" class="button-secondary" type="button">Choose another vehicle</button></div></section><section class="history-timeline" aria-labelledby="history-timeline-heading"><h2 id="history-timeline-heading">Completed services</h2><ol>${history.map(item=>renderService(item,store)).join('')}</ol></section>`;
  content.querySelector('#clear-history-selection')?.addEventListener('click',()=>{selectedId='';render();picker.focus();});content.querySelector('#print-service-history')?.addEventListener('click',()=>printVehicleHistory(root,vehicle,history,store));
  for(const form of content.querySelectorAll<HTMLFormElement>('[data-warranty-form]'))form.addEventListener('submit',event=>submitWarranty(event,form));
  for(const form of content.querySelectorAll<HTMLFormElement>('[data-claim-form]'))form.addEventListener('submit',event=>submitClaim(event,form));
  for(const form of content.querySelectorAll<HTMLFormElement>('[data-next-service-form]'))form.addEventListener('submit',event=>submitNextService(event,form));
 };
 function renderService(item:NonNullable<ReturnType<typeof completedService>>,state:WorkshopStore):string{
  const warranties=state.warranties.filter(w=>w.jobId===item.jobId),next=state.nextServices.find(n=>n.jobId===item.jobId),known=latestKnownOdometer(state,item.vehicleId);
  const parts=item.consumedParts.length?item.consumedParts.map(p=>`<li>${esc(p.name)} × ${p.quantity} ${esc(p.unit)}${p.sku?` · ${esc(p.sku)}`:''}</li>`).join(''):'<li>No net inventory parts consumed.</li>';
  const work=item.actualWork.length?item.actualWork.map(w=>`<li><strong>${esc(w.name)}</strong>${w.detail?` — ${esc(w.detail)}`:''}${w.mechanic?` · ${esc(w.mechanic)}`:''} · ${w.sourceRecommendationId?'Approved inspection scope':'Additional / unplanned work'}</li>`).join(''):'<li>No completed actual-work rows recorded.</li>';
  const free=item.freeTextMaterials.length?`<section><h4>Documented free-text / non-stock materials</h4><p>These Work Order notes are not inventory consumption.</p><ul>${item.freeTextMaterials.map(p=>`<li>${esc(p.name)} · ${p.quantity} ${esc(p.unit)}${p.partNumber?` · ${esc(p.partNumber)}`:''}${p.notes?` — ${esc(p.notes)}`:''}</li>`).join('')}</ul></section>`:'';
  return `<li><article class="history-service-card" data-history-job="${esc(item.jobId)}"><header><h3>${esc(dateLabel(item.serviceDate))}</h3><span class="history-status">${item.status}</span></header><p><strong>Odometer:</strong> ${number(item.odometer)} km</p><p><strong>Workshop Job:</strong> ${esc(item.jobNumber)} · <strong>Complaint:</strong> ${esc(item.complaint||'Not recorded')}</p><section><h4>Actual work performed</h4><ul>${work}</ul></section><section><h4>Inventory parts consumed</h4><ul>${parts}</ul></section><details><summary>Inspection, technician and handover details</summary><p><strong>Work performed by:</strong> ${esc(item.technicians.join(', ')||'Not recorded')}</p><p><strong>QC inspector:</strong> ${esc(item.qcInspector||'Not recorded')}</p><p><strong>Inspection findings:</strong> ${esc(item.findings||'Not recorded')}</p><p><strong>QC:</strong> ${esc(item.qcResult)}</p><p><strong>Handover to:</strong> ${esc(item.handoverRecipient||'Not recorded')}</p><p><strong>Handover notes:</strong> ${esc(item.handoverNotes||'Not recorded')}</p>${item.deferredIssues.length?`<p><strong>Customer-deferred work:</strong> ${item.deferredIssues.map(x=>`${esc(x.issue)} — ${esc(x.reason)}`).join('; ')}</p>`:''}${free}</details><a class="button-link button-secondary" href="/tools/workshop/work-order/?job=${encodeURIComponent(item.jobId)}">View Completed Job</a><section class="history-follow-up"><h4>Warranty</h4>${warranties.length?warranties.map(w=>renderWarranty(w,state,known)).join(''):`<p>No Warranty recorded for this service.</p><details><summary>Add warranty</summary>${warrantyForm(item)}</details>`}<h4>Next Service</h4>${next?`<p><strong>${esc(nextServiceStatus(next,known))}</strong> · ${dateLabel(next.date)} · ${next.odometer===null?'Odometer not set':`${number(next.odometer)} km`}${next.recommendation?` · ${esc(next.recommendation)}`:''}</p><details><summary>Update recommendation</summary>${nextServiceForm(item,next)}</details>`:`<p>No recommendation recorded.</p><details><summary>Record next service recommendation</summary>${nextServiceForm(item,null)}</details>`}</section></article></li>`;
 }
 function warrantyForm(item:NonNullable<ReturnType<typeof completedService>>):string{
  const actual=item.actualWork.map(x=>`<label class="history-option"><input type="checkbox" name="coveredWork" value="${esc(x.name)}"><span>${esc(x.name)}</span></label>`).join('')||'<p>No completed work is eligible for labor coverage.</p>';
  const parts=item.consumedParts.map(p=>`<label class="history-option"><input type="checkbox" name="coveredPartIds" value="${esc(p.partId)}"><span>${esc(p.name)} · consumed ${p.quantity} ${esc(p.unit)}</span></label>`).join('')||'<p>No consumed inventory parts are eligible for parts coverage.</p>';
  return `<form class="workshop-form history-form" data-warranty-form data-job-id="${esc(item.jobId)}"><label><span>Coverage type</span><select name="coverageType"><option>Labor</option><option>Parts</option><option>Labor and parts</option></select></label><fieldset><legend>Actual work covered</legend>${actual}</fieldset><fieldset><legend>Consumed inventory parts covered</legend>${parts}</fieldset><label><span>Warranty start date</span><input name="startDate" type="date" value="${esc(item.serviceDate)}" required></label><label><span>Expiry date (optional if expiry odometer is set)</span><input name="expiryDate" type="date"></label><label><span>Expiry odometer in km (optional if expiry date is set)</span><input name="expiryOdometer" type="number" min="0"></label><label><span>Terms / notes</span><textarea name="terms"></textarea></label><p class="field-error" data-form-error role="alert" hidden></p><button type="submit">Save warranty</button></form>`;
 }
 function renderWarranty(w:WorkshopWarranty,state:WorkshopStore,known:number|null):string{
  const status=warrantyStatusForVehicle(state,w),coveredWork=w.coveredWork.length?w.coveredWork.map(esc).join(', '):'None recorded',coveredParts=w.coveredPartIds.map(id=>esc(state.parts.find(p=>p.id===id)?.name??'Inventory part')).join(', ')||'None recorded',claims=state.warrantyClaims.filter(c=>c.warrantyId===w.id);
  return `<article class="history-warranty-card"><h5>${esc(w.coverageType)} warranty · <span>${esc(status)}</span></h5><p>Start ${dateLabel(w.startDate)} · expiry ${dateLabel(w.expiryDate)} · expiry odometer ${w.expiryOdometer===null?'Not set':`${number(w.expiryOdometer)} km`}</p><p><strong>Last known odometer:</strong> ${number(known)} km. ${status==='Odometer unknown'?'Mileage-based validity cannot be confirmed from saved readings.':''}</p><p><strong>Covered work:</strong> ${coveredWork}</p><p><strong>Covered parts:</strong> ${coveredParts}</p><p><strong>Terms:</strong> ${esc(w.terms||'Not recorded')}</p><h6>Warranty claims (${claims.length})</h6>${claims.length?`<ol class="history-claims">${claims.map(c=>`<li><strong>${esc(c.status)} · ${dateLabel(c.date)}</strong> · ${esc(c.issue)}${c.odometer===null?'':` · ${number(c.odometer)} km`}${c.resolution?` · ${esc(c.resolution)}`:''}${c.notes?` · ${esc(c.notes)}`:''}</li>`).join('')}</ol>`:'<p>No claims documented.</p>'}<details><summary>Record claim</summary>${claimForm(w,known,claims)}</details></article>`;
 }
 function claimForm(w:WorkshopWarranty,known:number|null,claims:WorkshopStore['warrantyClaims']):string{const last=claims.filter(c=>c.odometer!==null).sort((a,b)=>b.date.localeCompare(a.date))[0]?.odometer??known;return `<form class="workshop-form history-form" data-claim-form data-warranty-id="${esc(w.id)}"><label><span>Claim date</span><input name="date" type="date" value="${localDate()}" required></label><label><span>Claim odometer (last known ${number(last)} km)</span><input name="odometer" type="number" min="0"></label><label><span>Issue / complaint</span><textarea name="issue" required></textarea></label><label><span>Resolution / result</span><textarea name="resolution"></textarea></label><label><span>Claim status</span><select name="claimStatus"><option>Open</option><option>Resolved</option><option>Declined</option></select></label><label><span>Notes</span><textarea name="notes"></textarea></label><p class="field-error" data-form-error role="alert" hidden></p><button type="submit">Save claim</button></form>`;}
 function nextServiceForm(item:NonNullable<ReturnType<typeof completedService>>,next:NextService|null):string{return `<form class="workshop-form history-form" data-next-service-form data-job-id="${esc(item.jobId)}"><label><span>Recommended next service date</span><input name="date" type="date" value="${esc(next?.date??'')}"></label><label><span>Recommended odometer in km</span><input name="odometer" type="number" min="0" value="${esc(next?.odometer??'')}"></label><label><span>Recommended work / note</span><textarea name="recommendation">${esc(next?.recommendation??'')}</textarea></label><p class="field-error" data-form-error role="alert" hidden></p><button type="submit">Save next service</button></form>`;}
 function formValues(form:HTMLFormElement,name:string){return String(new FormData(form).get(name)??'').trim();}
 function formError(form:HTMLFormElement,text:string){const node=form.querySelector<HTMLElement>('[data-form-error]')!;node.textContent=text;node.hidden=!text;}
 function submitWarranty(event:SubmitEvent,form:HTMLFormElement){event.preventDefault();const data=new FormData(form),expiryOdo=String(data.get('expiryOdometer')??'').trim(),expiry=String(data.get('expiryDate')??'').trim();const result=persistMutation(form,()=>createWarranty(store,{jobId:form.dataset.jobId!,coverageType:formValues(form,'coverageType') as WorkshopWarranty['coverageType'],coveredWork:data.getAll('coveredWork').map(String),coveredPartIds:data.getAll('coveredPartIds').map(String),startDate:formValues(form,'startDate'),expiryDate:expiry||null,expiryOdometer:expiryOdo===''?null:Number(expiryOdo),terms:formValues(form,'terms')}));if(result){selectedId=String((result as WorkshopWarranty).vehicleId);render();}}
 function submitClaim(event:SubmitEvent,form:HTMLFormElement){event.preventDefault();const odo=formValues(form,'odometer');const result=persistMutation(form,()=>createWarrantyClaim(store,{warrantyId:form.dataset.warrantyId!,date:formValues(form,'date'),odometer:odo===''?null:Number(odo),issue:formValues(form,'issue'),resolution:formValues(form,'resolution'),notes:formValues(form,'notes'),status:formValues(form,'claimStatus') as WorkshopStore['warrantyClaims'][number]['status']}));if(result)render();}
 function submitNextService(event:SubmitEvent,form:HTMLFormElement){event.preventDefault();const odo=formValues(form,'odometer');const result=persistMutation(form,()=>saveNextService(store,{jobId:form.dataset.jobId!,date:formValues(form,'date')||null,odometer:odo===''?null:Number(odo),recommendation:formValues(form,'recommendation')}));if(result)render();}
 function printVehicleHistory(pageRoot:HTMLElement,vehicle:WorkshopStore['vehicles'][number],history:ReturnType<typeof serviceHistory>,state:WorkshopStore){const sheet=$<HTMLElement>(pageRoot,'#print-sheet'),title=$<HTMLElement>(pageRoot,'#print-title'),body=$<HTMLElement>(pageRoot,'#print-content');title.textContent=`Service History · ${vehicle.plate} · ${[vehicle.make,vehicle.model].filter(Boolean).join(' ')}`;body.replaceChildren();const summary=document.createElement('p');summary.textContent=`Year ${vehicle.year??'not recorded'} · last known odometer ${number(latestKnownOdometer(state,vehicle.id))} km · completed services ${history.length}`;body.append(summary);for(const item of history){const article=document.createElement('section');article.className='print-line';const heading=document.createElement('h3');heading.textContent=`${dateLabel(item.serviceDate)} · ${item.jobNumber}`;article.append(heading);for(const [label,text]of [['Odometer',`${number(item.odometer)} km`],['Complaint',item.complaint],['Actual work',item.actualWork.map(w=>w.name).join('; ')||'None recorded'],['Inventory parts consumed',item.consumedParts.map(p=>`${p.name} × ${p.quantity} ${p.unit}`).join('; ')||'None'],['Technician',item.technician||'Not recorded'],['QC',item.qcResult],['Handover',item.handoverNotes||'Not recorded']] as const){const p=document.createElement('p');p.textContent=`${label}: ${text}`;article.append(p);}body.append(article);}sheet.removeAttribute('hidden');sheet.classList.add('is-preview');window.print();setTimeout(()=>{sheet.classList.remove('is-preview');sheet.setAttribute('hidden','');},500);}
 search.addEventListener('input',()=>{selectedId='';render();});picker.addEventListener('change',()=>{selectedId=picker.value;render();});render();
}
