import type { GoodsReceipt, GoodsReceiptLine, PartMovement, PurchaseNeed, PurchaseNeedAllocation, PurchaseNeedState, PurchaseOrder, PurchaseOrderLine, SupplierSnapshot, WorkshopJob, WorkshopPart, WorkshopStore, WorkshopSupplier } from './model.ts';
import { jobPartSummary } from './parts.ts';
import { operationalStatus } from './queue.ts';

export type ProcurementResult<T> = { ok: true; value: T } | { ok: false; message: string };
const fail = <T>(message: string): ProcurementResult<T> => ({ ok: false, message });
const id = (prefix: string) => `${prefix}_${globalThis.crypto?.randomUUID?.() ?? `${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 12)}`}`;
const stamp = (date: Date) => date.toISOString();
const positive = (n: number) => Number.isFinite(n) && n > 0;
const money = (n: number) => Number.isSafeInteger(n) && n >= 0;
const dateOnly = (s: string) => /^\d{4}-\d{2}-\d{2}$/.test(s) && !Number.isNaN(Date.parse(`${s}T00:00:00Z`)) && new Date(`${s}T00:00:00Z`).toISOString().slice(0,10) === s;
const partSnapshot = (p: WorkshopPart) => ({ partId:p.id, partNameSnapshot:p.name, skuSnapshot:p.sku, unitSnapshot:p.unit });
const supplierSnapshot = (s: WorkshopSupplier): SupplierSnapshot => ({ name:s.name, phone:s.phone, email:s.email, address:s.address, contactPerson:s.contactPerson });
const activePO = (po: PurchaseOrder) => po.status === 'Issued';

export interface NeedProgress { requested:number; received:number; ordered:number; draftAllocated:number; open:number; state:PurchaseNeedState }
export interface ShortageSuggestion { job:WorkshopJob; part:WorkshopPart; requested:number; issued:number; available:number; shortage:number; covered:number; suggested:number }
export interface ReceiptLineInput { poLineId:string; deliveredQuantity:number; acceptedQuantity:number; rejectedQuantity:number; actualUnitCost?:number; rejectionNote?:string; acceptedNeedAllocations:PurchaseNeedAllocation[] }
export interface ReceiptInput { receiptId?:string; receivedAt:string; supplierDeliveryNote?:string; supplierInvoiceReference?:string; receivedBy?:string; notes?:string; confirmCostVariance?:boolean; lines:ReceiptLineInput[] }

export function getPurchaseNeed(store:WorkshopStore,needId:string){return store.purchaseNeeds.find(x=>x.needId===needId);}
export function getPurchaseOrder(store:WorkshopStore,poId:string){return store.purchaseOrders.find(x=>x.poId===poId);}
export function getPart(store:WorkshopStore,partId:string){return store.parts.find(x=>x.id===partId);}
export function supplierFor(store:WorkshopStore,supplierId:string){return store.suppliers.find(x=>x.supplierId===supplierId);}

function receiptAllocations(store:WorkshopStore,needId:string){return store.goodsReceipts.flatMap(r=>r.lines).flatMap(l=>l.acceptedNeedAllocations.filter(a=>a.needId===needId)).reduce((n,a)=>n+a.quantity,0);}
function poLineReceipts(store:WorkshopStore,lineId:string){return store.goodsReceipts.flatMap(r=>r.lines.filter(l=>l.poLineId===lineId)).reduce((n,l)=>n+l.acceptedQuantity,0);}
function needPOAllocations(store:WorkshopStore,needId:string,statuses:PurchaseOrder['status'][]){return store.purchaseOrders.filter(p=>statuses.includes(p.status)).flatMap(p=>p.lines).flatMap(l=>l.sourceAllocations.filter(a=>a.needId===needId)).reduce((n,a)=>n+a.quantity,0);}
export function needProgress(store:WorkshopStore,need:PurchaseNeed):NeedProgress{
  const received=receiptAllocations(store,need.needId),ordered=Math.max(0,needPOAllocations(store,need.needId,['Issued'])-received),draftAllocated=needPOAllocations(store,need.needId,['Draft']),open=Math.max(0,need.requestedQuantity-received-ordered-draftAllocated);
  const state:PurchaseNeedState=need.cancelledAt?'Cancelled':received>=need.requestedQuantity?'Fulfilled':received>0?'Partially Received':ordered>=need.requestedQuantity?'Ordered':'Open';
  return {requested:need.requestedQuantity,received,ordered,draftAllocated,open,state};
}
export function shortageSuggestions(store:WorkshopStore):ShortageSuggestion[]{
  const output:ShortageSuggestion[]=[];
  for(const job of store.jobs){if(['Cancelled','Completed'].includes(operationalStatus(job)))continue;for(const row of jobPartSummary(store,job))if(row.shortage>0){
    const covered=store.purchaseNeeds.filter(n=>!n.cancelledAt&&n.source==='JOB_SHORTAGE'&&n.jobId===job.id&&n.partId===row.part.id).reduce((sum,n)=>sum+Math.max(0,n.requestedQuantity-needProgress(store,n).received),0);
    output.push({job,part:row.part,requested:row.requested,issued:row.issued,available:row.available,shortage:row.shortage,covered,suggested:Math.max(0,row.shortage-covered)});
  }}return output.filter(x=>x.part.active&&x.suggested>1e-8);
}
export function needWorkOrderMismatch(store:WorkshopStore,need:PurchaseNeed):number|null{
  if(need.source!=='JOB_SHORTAGE'||!need.jobId)return null;const job=store.jobs.find(x=>x.id===need.jobId);if(!job)return need.requestedQuantity;
  const requested=(job.workOrder?.parts??[]).filter(x=>x.partId===need.partId).reduce((n,x)=>n+x.quantity,0);
  return need.jobRequestedQuantitySnapshot!==undefined&&Math.abs(requested-need.jobRequestedQuantitySnapshot)>1e-8?requested:null;
}
export function createPurchaseNeed(store:WorkshopStore,input:{source:PurchaseNeed['source'];partId:string;quantity:number;jobId?:string;requiredBy?:string;reason?:string},now=new Date()):ProcurementResult<PurchaseNeed>{
  const part=getPart(store,input.partId);if(!part||!part.active)return fail('Choose an active inventory Part.');if(!positive(input.quantity))return fail('Quantity must be greater than zero.');if(input.requiredBy&&!dateOnly(input.requiredBy))return fail('Enter a valid required-by date.');
  if(input.source==='JOB_SHORTAGE'){const job=input.jobId&&store.jobs.find(j=>j.id===input.jobId);if(!job||['Cancelled','Completed'].includes(operationalStatus(job)))return fail('Choose an active unfinished Workshop Job.');const row=jobPartSummary(store,job).find(x=>x.part.id===part.id);if(!row||row.shortage<=0)return fail('The Job no longer has a shortage for this Part.');const covered=store.purchaseNeeds.filter(n=>!n.cancelledAt&&n.source==='JOB_SHORTAGE'&&n.jobId===job.id&&n.partId===part.id).reduce((sum,n)=>sum+Math.max(0,n.requestedQuantity-needProgress(store,n).received),0);if(input.quantity>Math.max(0,row.shortage-covered)+1e-8)return fail('Need quantity exceeds the uncovered Job shortage.');}
  if(input.source!=='JOB_SHORTAGE'&&input.source!=='REPLENISHMENT'&&input.source!=='MANUAL')return fail('Choose a valid Purchase Need source.');
  if(input.source==='MANUAL'&&!input.reason?.trim())return fail('A reason is required for a manual Purchase Need.');
  const linkedJob=input.source==='JOB_SHORTAGE'?store.jobs.find(j=>j.id===input.jobId):undefined;const requestedForJob=linkedJob?.workOrder?.parts.filter(x=>x.partId===part.id).reduce((sum,x)=>sum+x.quantity,0);
  const n:PurchaseNeed={needId:id('need'),source:input.source,...partSnapshot(part),requestedQuantity:input.quantity,...(input.source==='JOB_SHORTAGE'?{jobId:input.jobId,jobRequestedQuantitySnapshot:requestedForJob??0}:{}),...(input.requiredBy?{requiredBy:input.requiredBy}:{}),...(input.reason?.trim()?{reason:input.reason.trim()}:{}),createdAt:stamp(now)};store.purchaseNeeds.push(n);return {ok:true,value:n};
}
export function cancelPurchaseNeed(store:WorkshopStore,needId:string,reason:string,now=new Date()):ProcurementResult<PurchaseNeed>{const n=getPurchaseNeed(store,needId);if(!n)return fail('Purchase Need not found.');if(n.cancelledAt)return fail('Purchase Need is already cancelled.');if(!reason.trim())return fail('Enter a cancellation reason.');const p=needProgress(store,n);if(p.received>=n.requestedQuantity)return fail('A fulfilled Purchase Need cannot be cancelled.');n.cancelledAt=stamp(now);n.cancelReason=reason.trim();return {ok:true,value:n};}

export function createSupplier(store:WorkshopStore,input:Omit<WorkshopSupplier,'supplierId'|'createdAt'|'updatedAt'>,now=new Date()):ProcurementResult<WorkshopSupplier>{if(!input.name.trim())return fail('Supplier name is required.');const s:WorkshopSupplier={supplierId:id('supplier'),...input,name:input.name.trim(),createdAt:stamp(now),updatedAt:stamp(now)};store.suppliers.push(s);return {ok:true,value:s};}
export function updateSupplier(store:WorkshopStore,supplierId:string,patch:Partial<Omit<WorkshopSupplier,'supplierId'|'createdAt'|'updatedAt'>>,now=new Date()):ProcurementResult<WorkshopSupplier>{const s=supplierFor(store,supplierId);if(!s)return fail('Supplier not found.');const next={...s,...patch};if(!next.name.trim())return fail('Supplier name is required.');Object.assign(s,next,{name:next.name.trim(),updatedAt:stamp(now)});return {ok:true,value:s};}
export function setPartDefaultSupplier(store:WorkshopStore,partId:string,supplierId:string|undefined):ProcurementResult<WorkshopPart>{const p=getPart(store,partId);if(!p)return fail('Part not found.');if(supplierId){const s=supplierFor(store,supplierId);if(!s?.active)return fail('Default supplier must be active.');p.defaultSupplierId=supplierId;}else delete p.defaultSupplierId;p.updatedAt=new Date().toISOString();return {ok:true,value:p};}

export function createPurchaseOrderDraft(store:WorkshopStore,needIds:string[],supplierId:string|undefined,now=new Date()):ProcurementResult<PurchaseOrder>{
  const ids=[...new Set(needIds)];if(!ids.length)return fail('Select at least one Purchase Need.');if(supplierId&&!supplierFor(store,supplierId)?.active)return fail('Choose an active Supplier.');
  const grouped=new Map<string,{part:WorkshopPart;allocations:PurchaseNeedAllocation[]}>();
  for(const needId of ids){const n=getPurchaseNeed(store,needId);if(!n||n.cancelledAt)return fail('A selected Purchase Need is unavailable.');const p=getPart(store,n.partId);if(!p||!p.active)return fail(`Part ${n.partNameSnapshot} is not active.`);const prog=needProgress(store,n);const qty=prog.open;if(!positive(qty))return fail(`No open quantity remains for ${n.partNameSnapshot}.`);const entry=grouped.get(n.partId)??{part:p,allocations:[]};entry.allocations.push({needId,quantity:qty});grouped.set(n.partId,entry);}
  const lines:PurchaseOrderLine[]=[...grouped.values()].map(x=>({lineId:id('po-line'),...partSnapshot(x.part),orderedQuantity:x.allocations.reduce((n,a)=>n+a.quantity,0),agreedUnitCost:0,sourceAllocations:x.allocations}));
  const po:PurchaseOrder={poId:id('po'),status:'Draft',...(supplierId?{supplierId}:{}),orderDate:now.toISOString().slice(0,10),lines,createdAt:stamp(now),updatedAt:stamp(now)};store.purchaseOrders.push(po);return {ok:true,value:po};
}
export function updateDraftPO(store:WorkshopStore,poId:string,patch:{supplierId?:string;expectedDate?:string;notes?:string;lines?:PurchaseOrderLine[];orderDate?:string},now=new Date()):ProcurementResult<PurchaseOrder>{const po=getPurchaseOrder(store,poId);if(!po||po.status!=='Draft')return fail('Only a Draft Purchase Order can be edited.');if(patch.supplierId&&!supplierFor(store,patch.supplierId)?.active)return fail('Choose an active Supplier.');if(patch.orderDate&&!dateOnly(patch.orderDate))return fail('Enter a valid order date.');if(patch.expectedDate&&!dateOnly(patch.expectedDate))return fail('Enter a valid expected date.');if(patch.lines){for(const line of patch.lines){if(!getPart(store,line.partId)?.active||line.sourceAllocations.length===0&&line.orderedQuantity>0||!positive(line.orderedQuantity)||!money(line.agreedUnitCost)||Math.abs(line.orderedQuantity-line.sourceAllocations.reduce((n,a)=>n+a.quantity,0))>1e-8)return fail('Each PO line must have an active Part, valid cost, and fully allocated quantity.');}const check=validateDraftAllocations(store,poId,patch.lines);if(!check.ok)return check;if(purchaseOrderTotal({...po,lines:patch.lines})===null)return fail('PO total exceeds the safe IDR amount range.');}if(patch.supplierId!==undefined)po.supplierId=patch.supplierId;if(patch.expectedDate!==undefined)po.expectedDate=patch.expectedDate||undefined;if(patch.notes!==undefined)po.notes=patch.notes;if(patch.orderDate)po.orderDate=patch.orderDate;if(patch.lines)po.lines=structuredClone(patch.lines);po.updatedAt=stamp(now);return {ok:true,value:po};}
function validateDraftAllocations(store:WorkshopStore,poId:string,lines:PurchaseOrderLine[]):ProcurementResult<true>{const own=getPurchaseOrder(store,poId), allocation=new Map<string,number>();for(const line of lines)for(const a of line.sourceAllocations){if(!positive(a.quantity))return fail('Need allocation quantities must be greater than zero.');const n=getPurchaseNeed(store,a.needId);if(!n||n.cancelledAt||n.partId!==line.partId)return fail('PO allocation must reference an active Need for the same Part.');allocation.set(a.needId,(allocation.get(a.needId)??0)+a.quantity);}for(const [needId,qty]of allocation){const n=getPurchaseNeed(store,needId)!;const otherDraft=needPOAllocations(store,needId,['Draft'])-(own?.lines.flatMap(l=>l.sourceAllocations).filter(a=>a.needId===needId).reduce((s,a)=>s+a.quantity,0)??0);const ordered=needPOAllocations(store,needId,['Issued'])-receiptAllocations(store,needId);const remaining=Math.max(0,n.requestedQuantity-receiptAllocations(store,needId)-ordered-Math.max(0,otherDraft));if(qty>remaining+1e-8)return fail(`Allocation exceeds the open quantity for ${n.partNameSnapshot} (${remaining}).`);}return {ok:true,value:true};}
function nextNumber(prefix:string,existing:string[],date:string){const day=date.replaceAll('-','');const used=new Set(existing);let n=1;while(used.has(`${prefix}-${day}-${String(n).padStart(4,'0')}`))n++;return `${prefix}-${day}-${String(n).padStart(4,'0')}`;}
export function issuePurchaseOrder(store:WorkshopStore,poId:string,now=new Date()):ProcurementResult<PurchaseOrder>{const po=getPurchaseOrder(store,poId);if(!po||po.status!=='Draft')return fail('Only a Draft Purchase Order can be issued.');const supplier=po.supplierId?supplierFor(store,po.supplierId):undefined;if(!supplier?.active)return fail('Select an active Supplier before issuing.');if(!dateOnly(po.orderDate))return fail('Enter a valid order date.');if(!po.lines.length)return fail('Add at least one PO line.');const valid=validateDraftAllocations(store,poId,po.lines);if(!valid.ok)return valid;for(const l of po.lines)if(!getPart(store,l.partId)?.active||!money(l.agreedUnitCost)||Math.abs(l.orderedQuantity-l.sourceAllocations.reduce((n,a)=>n+a.quantity,0))>1e-8)return fail('Review invalid PO line quantity, cost, or allocations.');if(purchaseOrderTotal(po)===null)return fail('PO total exceeds the safe IDR amount range.');po.supplierSnapshot=supplierSnapshot(supplier);for(const line of po.lines){const p=getPart(store,line.partId)!;Object.assign(line,partSnapshot(p));}po.poNumber=nextNumber('PO',store.purchaseOrders.flatMap(x=>x.poNumber?[x.poNumber]:[]),po.orderDate);po.status='Issued';po.issuedAt=stamp(now);po.updatedAt=stamp(now);return {ok:true,value:po};}
export function cancelPurchaseOrder(store:WorkshopStore,poId:string,reason:string,now=new Date()):ProcurementResult<PurchaseOrder>{const po=getPurchaseOrder(store,poId);if(!po||po.status!=='Issued')return fail('Only an Issued Purchase Order can be cancelled.');if(!reason.trim())return fail('Enter a cancellation reason.');po.status='Cancelled';po.cancelReason=reason.trim();po.cancelledAt=stamp(now);po.updatedAt=stamp(now);return {ok:true,value:po};}
export function closePurchaseOrder(store:WorkshopStore,poId:string,reason:string,now=new Date()):ProcurementResult<PurchaseOrder>{const po=getPurchaseOrder(store,poId);if(!po||po.status!=='Issued')return fail('Only an Issued Purchase Order can be closed.');const outstanding=po.lines.some(l=>l.orderedQuantity-poLineReceipts(store,l.lineId)>1e-8);if(outstanding&&!reason.trim())return fail('Enter a reason for closing with outstanding quantity.');po.status='Closed';po.closeReason=outstanding?reason.trim():undefined;po.closedAt=stamp(now);po.updatedAt=stamp(now);return {ok:true,value:po};}
export function poLineProgress(store:WorkshopStore,line:PurchaseOrderLine){const accepted=poLineReceipts(store,line.lineId);return {ordered:line.orderedQuantity,accepted,remaining:Math.max(0,line.orderedQuantity-accepted),state:accepted<=0?'Not Received':accepted+1e-8>=line.orderedQuantity?'Fully Received':'Partially Received'} as const;}
export function poProgress(store:WorkshopStore,po:PurchaseOrder){if(!po.lines.length)return 'Not Received';const rows=po.lines.map(l=>poLineProgress(store,l));return rows.every(x=>x.state==='Fully Received')?'Fully Received':rows.some(x=>x.accepted>0)?'Partially Received':'Not Received';}
export function onOrderQuantity(store:WorkshopStore,partId:string){return store.purchaseOrders.filter(activePO).flatMap(po=>po.lines.filter(l=>l.partId===partId).map(l=>Math.max(0,l.orderedQuantity-poLineReceipts(store,l.lineId)))).reduce((n,x)=>n+x,0);}
export function receivedAllocationForLine(store:WorkshopStore,po:PurchaseOrder,line:PurchaseOrderLine,needId:string){const ordered=line.sourceAllocations.filter(a=>a.needId===needId).reduce((n,a)=>n+a.quantity,0);const already=store.goodsReceipts.filter(r=>r.poId===po.poId).flatMap(r=>r.lines.filter(x=>x.poLineId===line.lineId)).flatMap(x=>x.acceptedNeedAllocations.filter(a=>a.needId===needId)).reduce((n,a)=>n+a.quantity,0);return Math.max(0,ordered-already);}
export function defaultReceiptAllocations(store:WorkshopStore,po:PurchaseOrder,line:PurchaseOrderLine,accepted:number):PurchaseNeedAllocation[]{let left=accepted;const out:PurchaseNeedAllocation[]=[];for(const a of line.sourceAllocations){const qty=Math.min(left,receivedAllocationForLine(store,po,line,a.needId));if(qty>0){out.push({needId:a.needId,quantity:qty});left-=qty;}if(left<=1e-8)break;}return out;}
export function commitGoodsReceipt(store:WorkshopStore,poId:string,input:ReceiptInput,now=new Date()):ProcurementResult<GoodsReceipt>{
  const existing=input.receiptId&&store.goodsReceipts.find(r=>r.receiptId===input.receiptId);if(existing){const po=getPurchaseOrder(store,existing.poId);if(!po)return fail('Saved receipt has no Purchase Order.');for(const line of existing.lines){if(line.acceptedQuantity<=0||store.partMovements.some(m=>m.sourceType==='PURCHASE_RECEIPT'&&m.sourceId===line.receiptLineId))continue;const part=getPart(store,line.partId);if(!part)return fail('Saved receipt Part is missing; inventory recovery needs review.');const movement:PartMovement={id:id('movement'),partId:line.partId,type:'STOCK_IN',quantity:line.acceptedQuantity,at:new Date(`${existing.receivedAt}T12:00:00`).toISOString(),partNameSnapshot:line.partNameSnapshot,partSkuSnapshot:line.skuSnapshot,partUnitSnapshot:line.unitSnapshot,...(line.actualUnitCost!==undefined?{unitCost:line.actualUnitCost}:{}),supplier:po.supplierSnapshot?.name??'',reference:po.poNumber??'',note:`Goods Receipt ${existing.receiptNumber}`,sourceType:'PURCHASE_RECEIPT',sourceId:line.receiptLineId,poId:po.poId,poNumber:po.poNumber,receiptId:existing.receiptId,receiptNumber:existing.receiptNumber,receiptLineId:line.receiptLineId};line.stockMovementId=movement.id;store.partMovements.push(movement);}return {ok:true,value:existing};}
  const po=getPurchaseOrder(store,poId);if(!po||po.status!=='Issued')return fail('Goods can only be received against an Issued Purchase Order.');if(!dateOnly(input.receivedAt))return fail('Enter a valid receipt date.');if(!input.lines.length)return fail('Add at least one receipt line.');
  const receiptId=input.receiptId||id('receipt'),receiptNumber=nextNumber('GR',store.goodsReceipts.map(r=>r.receiptNumber),input.receivedAt);const receiptLines:GoodsReceiptLine[]=[];const movements:PartMovement[]=[];const seen=new Set<string>();
  for(const row of input.lines){if(seen.has(row.poLineId))return fail('A PO line can appear only once in a receipt.');seen.add(row.poLineId);const line=po.lines.find(l=>l.lineId===row.poLineId);if(!line)return fail('Receipt line does not belong to this PO.');const remaining=poLineProgress(store,line).remaining;if(!positive(row.deliveredQuantity)||!Number.isFinite(row.acceptedQuantity)||row.acceptedQuantity<0||!Number.isFinite(row.rejectedQuantity)||row.rejectedQuantity<0||Math.abs(row.deliveredQuantity-row.acceptedQuantity-row.rejectedQuantity)>1e-8)return fail('Delivered quantity must equal accepted plus rejected quantity.');if(row.acceptedQuantity>remaining+1e-8)return fail(`Accepted quantity exceeds the remaining PO quantity (${remaining}).`);if(row.acceptedQuantity>0&&!getPart(store,line.partId)?.active)return fail('The received Part is inactive. Reactivate it before receiving stock.');if(row.actualUnitCost!==undefined&&!money(row.actualUnitCost))return fail('Actual received unit cost must be a whole non-negative IDR amount.');if(row.actualUnitCost!==undefined&&row.actualUnitCost!==line.agreedUnitCost&&!input.confirmCostVariance)return fail('Confirm the purchase-cost variance before saving this receipt.');if(row.rejectedQuantity>0&&!row.rejectionNote?.trim())return fail('Add a reason for rejected/damaged quantity.');const allocations=row.acceptedNeedAllocations??[];if(Math.abs(allocations.reduce((n,a)=>n+a.quantity,0)-row.acceptedQuantity)>1e-8)return fail('Accepted Need allocations must exactly equal accepted quantity.');const byNeed=new Map<string,number>();for(const a of allocations){if(!positive(a.quantity)||!line.sourceAllocations.some(x=>x.needId===a.needId))return fail('Receipt allocation exceeds this PO line’s remaining Need allocation.');byNeed.set(a.needId,(byNeed.get(a.needId)??0)+a.quantity);}for(const [needId,quantity]of byNeed)if(quantity>receivedAllocationForLine(store,po,line,needId)+1e-8)return fail('Receipt allocation exceeds this PO line’s remaining Need allocation.');
    const part=getPart(store,line.partId)!;const receiptLine:GoodsReceiptLine={receiptLineId:id('receipt-line'),poLineId:line.lineId,...partSnapshot(part),deliveredQuantity:row.deliveredQuantity,acceptedQuantity:row.acceptedQuantity,rejectedQuantity:row.rejectedQuantity,...(row.actualUnitCost!==undefined?{actualUnitCost:row.actualUnitCost}:{}),...(row.rejectionNote?.trim()?{rejectionNote:row.rejectionNote.trim()}:{}),acceptedNeedAllocations:structuredClone(allocations)};receiptLines.push(receiptLine);
    if(row.acceptedQuantity>0)movements.push({id:id('movement'),partId:part.id,type:'STOCK_IN',quantity:row.acceptedQuantity,at:new Date(`${input.receivedAt}T12:00:00`).toISOString(),partNameSnapshot:part.name,partSkuSnapshot:part.sku,partUnitSnapshot:part.unit,...(row.actualUnitCost!==undefined?{unitCost:row.actualUnitCost}:{}),supplier:po.supplierSnapshot?.name??'',reference:po.poNumber??'',note:`Goods Receipt ${receiptNumber}`,sourceType:'PURCHASE_RECEIPT',sourceId:receiptLine.receiptLineId,poId:po.poId,poNumber:po.poNumber,receiptId,receiptNumber,receiptLineId:receiptLine.receiptLineId});
  }
  const receipt:GoodsReceipt={receiptId,receiptNumber,poId,receivedAt:input.receivedAt,...(input.supplierDeliveryNote?.trim()?{supplierDeliveryNote:input.supplierDeliveryNote.trim()}:{}),...(input.supplierInvoiceReference?.trim()?{supplierInvoiceReference:input.supplierInvoiceReference.trim()}:{}),...(input.receivedBy?.trim()?{receivedBy:input.receivedBy.trim()}:{}),...(input.notes?.trim()?{notes:input.notes.trim()}:{}),lines:receiptLines,createdAt:stamp(now)};
  // The controller persists receipt + all stock movements together in one localStorage write.
  for(const movement of movements)if(store.partMovements.some(m=>m.sourceType==='PURCHASE_RECEIPT'&&m.sourceId===movement.sourceId))return fail('A stock movement already exists for this receipt line.');
  for(const line of receiptLines){const movement=movements.find(m=>m.sourceId===line.receiptLineId);if(movement)line.stockMovementId=movement.id;}
  store.goodsReceipts.push(receipt);for(const movement of movements){store.partMovements.push(movement);const part=getPart(store,movement.partId);if(part)part.updatedAt=stamp(now);}
  if(poProgress(store,po)==='Fully Received'){po.status='Closed';po.closedAt=stamp(now);po.updatedAt=stamp(now);}
  return {ok:true,value:receipt};
}
export function purchaseLineTotal(quantity:number,unitCost:number):number|null{if(!Number.isFinite(quantity)||quantity<0||!money(unitCost))return null;const units=Math.round(quantity*1_000_000);if(!Number.isSafeInteger(units))return null;const total=(BigInt(units)*BigInt(unitCost)+500_000n)/1_000_000n;return total<=BigInt(Number.MAX_SAFE_INTEGER)?Number(total):null;}
export function purchaseOrderTotal(po:PurchaseOrder):number|null{let total=0;for(const line of po.lines){const amount=purchaseLineTotal(line.orderedQuantity,line.agreedUnitCost);if(amount===null||!Number.isSafeInteger(total+amount))return null;total+=amount;}return total;}
export function draftLine(part:WorkshopPart,allocations:PurchaseNeedAllocation[]):PurchaseOrderLine{return {lineId:id('po-line'),...partSnapshot(part),orderedQuantity:allocations.reduce((n,a)=>n+a.quantity,0),agreedUnitCost:0,sourceAllocations:structuredClone(allocations)};}
export function activeJobsForPart(store:WorkshopStore,partId:string){return store.jobs.filter(j=>!['Cancelled','Completed'].includes(operationalStatus(j))&&jobPartSummary(store,j).some(x=>x.part.id===partId&&x.shortage>0));}
